### ISSUE TITLE
Have a clear process for maintenance/contribution

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1004]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I proposed a pull request.

### Here is what I expected to happen:

To have an answer.

### Here is what actually happened:

Nothing.

### Here is data (or links to it) that can help you reproduce this issue:

https://github.com/openfisca/openfisca-core/pulls

Something like https://numpy.org/doc/stable/dev/governance/governance.html

## Context

I identify more as a:

- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.
- Lobbyist _(I model reforms to make them exist)_.

**Comment by MattiSG** [comment]
I'm not sure I really understand the content of this issue, which seems to be only the default issue template…? 🤔

**Comment by maukoquiroga** [comment]
Thanks @MattiSG 😱 ! Clearly description was not saved... I'll fix it soon.

**Comment by bonjourmauko** [comment]
I'm closing in favour of other emergent RFCs since then.
