### ISSUE TITLE
Automatically validate parameter declaration dates

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#1005]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

- Make a mistake in describing parameters: invert month and day numbers in dates (https://github.com/openfisca/openfisca-france/pull/1522).

### Here is what I expected to happen:

- Automated tests tell me that month number `31` doesn't exist in a year and that I probably inverted day and month in my date declaration.

### Here is what actually happened:

- Tests passed and we deployed a broken country package version.

### Here is data (or links to it) that can help you reproduce this issue:

https://github.com/openfisca/openfisca-france/pull/1522

## Context

I identify more as a:

- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by maukoquiroga** [comment]
Reproduced [here](https://github.com/openfisca/openfisca-core/compare/validate-wrong-period?expand=1).

**Comment by maukoquiroga** [comment]
Sorry and I think this is a bug actually, not a new feature, as it should already be checked [here](https://github.com/openfisca/openfisca-core/blob/6c053490f887c58e70d045ac71db9812400e2d55/openfisca_core/parameters/parameter.py#L68-L76)
