### ISSUE TITLE
OpenFisca-Core seems to depend on numpy 1.20 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#1009]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I modified [openfisca-survey-manager](https://github.com/openfisca/openfisca-survey-manager/pull/198) 

### Here is what I expected to happen:

Nothing new

### Here is what actually happened:

[Tests not passing](https://app.circleci.com/pipelines/github/openfisca/openfisca-survey-manager/534/workflows/9c9e4f2c-6a8f-4768-baa9-54f1923edd90/jobs/689)

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

(remove this line as well as all items in the list that don't fit your situation)

**Comment by maukoquiroga** [comment]
Thanks @benjello ! As discussed already in #1010, forcing users to upgrade to NumPy 1.20.0+ its a non-intended consequence of #990, so clearly a bug IMHO.
