### ISSUE TITLE
Support references in enums

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#1011]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

Create an enum with a `reference = 'https://legifrance.gouv.fr/…'` field.

### Here is what I expected to happen:

The enum is created and the reference is exposed in the API.

### Here is what actually happened:

I got an error `TypeError: member order does not match _order_`.

If I remove the `_order_` member, which was apparently necessary only for Python 2, then the reference is parsed but it is added as an enum member.

### Here is data (or links to it) that can help you reproduce this issue:

Example context of usage: https://github.com/openfisca/openfisca-france/pull/1501/files#diff-1e2118ecd1488d876f733cfef213de9c4b2f617293aa9ced93fcad5a7e344704R11-R20

## Context

I identify more as a:

- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by maukoquiroga** [comment]
Hello @MattiSG, and thanks for your request.

I have a technical question and a domain question:

1. Technically, an `Enum` is a class factory.

So `class TypesNiveauDiplome(Enum)` translates to something like `enum("TypesNiveauDiplome", (Enum,), {})`.

Your example is theoretically possible to achieve, but strange: we would have to tell to our factory to ignore `reference` as a member, while keeping the same syntax for members, and instead do either:

a. Add a `reference` attribute to any of the defined members. For example `TypesNiveauDiplome.niveau_1.reference`.

b. Add a `reference` attribute to the factory itself (per creation of a custom `EnumMeta` class). Then we will be able to do something like `TypesNiveauDiplome.reference`.

Which one is the one you intend here?

2. In terms of domain, I don't understand what it is for an `Enum`, which is basically a data class, to have a `reference`, which is a domain element of the legislation.

We could say that a `Variable` is an algorithm, described by a piece of legislation with a reference X, that prescribes the way of transforming some input data.

In similar fashion, we could argue that a `Parameter` is data embedded into a piece of legislation with a reference Y.

What does it semantically mean an `Enum` in terms of any given piece of legislation?

**Comment by maukoquiroga** [comment]
> I'm not sure exactly how stranger it is than having fields such as “description” or “label” that are part of a DSL and thus interpreted and overriding standard Python behaviour 😉

What I mean is that with a normal class, like a `Variable`, when using `=` then for example `description =` is an attribute of that class.

`Enum` is not a class, but a class factory, that creates several classes at runtime. So when we use `=` then for example `description =` becomes a singleton instance of a dynamically generated class `Description(MyEnum)`.

To sum up the behaviour of using `=` is not the same with normal Python classes and with `Enum` in particular.

I have no idea why do we use `Enum` instead of something simpler, like a `tuple`, `NamedTuple`, or `dataclass` (I guess it is because of the indexing, in order to keep both named and numbered indexes).

> Good question. I thought about having one reference for the entire Enum, as it made sense to add it as a member, but it might be useful to add a reference to each member in the Enum. I am not sure how that would look like in terms of DSL though.

None of them will work without adding an exception to what `=` means for a specific reserved keyword like `reference`, although the latter is more common —the former requires literally implementing our own "meta class" that will tell Python how our `Enum` factory class should go creating all of our singleton member class instances, and yes it is as complicated as it sounds... the latter should be easier as we can add an attribute to the `Enum`'s `__init__` method (as it is a factory, that attribute will be passed of all of the members defined in the context of that `Enum`) however it will require the same level of hacking if we want to use `=` for that matter.

> For example in OpenFisca-France, we recently added a list of recognised diploma levels. This list is defined in legislation and is thus sourced, but that source is currently only visible as a comment in the source code, and not exposed through the API and thus not visible in the legislation explorer.

Thanks. I see the need for it, and also that an `Enum` _may_ no longer be what is needed for the task, for the reasons exposed above.

I don't have an actual suggestion of implementation just yet.

**Comment by MattiSG** [comment]
Thank you so much @maukoquiroga for explaining the limitations in depth and for having identified these leads for solutions! 🙇 

I see that you self-assigned this issue, please let me know if there any way I can help 🙂

**Comment by maukoquiroga** [comment]
Thanks @MattiSG ! You know I'm working hard to clarify process 😃 

By assigning myself I meant just to signify that I commit to follow up on this and at some point either produce a formal feature request someone can work on, including ourselves, or proposing to reject it by some ground that can create jurisprudence.

I see two concrete ways we can move this forward, and where your help could be great:

- Elaborate this in a way that ressembles more to a feature request than to a bug report / support request. That'll help to anticipate the needed documentation, and we could even reuse that to create a proper template for future feature requests.
- Similarly, in terms of "[how make the decision?](https://numpy.org/doc/stable/dev/governance/governance.html#consensus-based-decision-making-by-the-community)" if you have in mind a process we can test, RFC or other, the simpler the better, please do not hesitate to propose it.

That would be it I guess, in technical terms I think we've almost nailed it already.

Please let me know if that makes sense to you.

**Comment by MattiSG** [comment]
> Elaborate this in a way that ressembles more to a feature request

Thank you for this suggestion: it made me look more in depth at the legislation explorer UI in order to draft something, and made me realise that Enum values are already exposed in the associated variable (example: [`scolarite`](https://fr.openfisca.org/legislation/scolarite?q=scolarite) in OpenFisca-France has values and descriptions [listed](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/education.py#L300-L302) from [`TypesScolarite`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/education.py#L291-L297).
This means that a workaround for explaining the origins and details of the classification for reusers might just be **using the `reference` field of the associated variable** rather than trying to add one to the Enum itself. This is not obvious, but could be documented as a best practice (or make a case for reconsidering how enums are defined, as I seem to remember there has already been some discussions around that).
We could then still rely on code comments for additional documentation on individual members of the enum.

One potential improvement I could see would be to have a reference for each enum member that could be hyperlinked in the legislation explorer, with each “Definition” entry pointing to the reference (or adding a “Reference” column to the table), but this builds upon the initial request rather than explaining it.

My conclusion for this issue:

1. Workaround: use the `reference` field of the Variable that exposes the Enum + use comments in the Enum itself.
2. Improve the overall usability of Enums by defining them in a Variable and exposing the possible values to the rest of the package through the Variable. This would be a separate RFC.

Given this conclusion, I close this issue. If anyone believes it is still worth investigating on its own, or that I missed some point, please feel free to reopen 🙂
