### ISSUE TITLE
Test Python 3.8

### ISSUE THREAD

**Issue by MaxGhenis** [openfisca/openfisca-core#1035]
Python 3.10 will also be launched in about 6 weeks.

**Comment by MattiSG** [comment]
Thanks @MaxGhenis!

Once #1030 is approved, we should have enough test runners to apply a matrix strategy that should let us test on several Python versions at once :smiley:

In order to help prioritise and avoid resource wastage, could you please share any deployment constraints you have / know of? With which version of Python do you currently use OpenFisca? 🙂

**Comment by maukoquiroga** [comment]
I've been tinkering with a working prototype here #1031 😃 (it works in local if you want to try it out).

**Comment by MaxGhenis** [comment]
>In order to help prioritise and avoid resource wastage, could you please share any deployment constraints you have / know of?

No constraints, though there could be general performance improvements. @nikhilwoodruff also mentioned code structuring improvements in 3.9.

>With which version of Python do you currently use OpenFisca?

3.7

**Comment by MattiSG** [comment]
#1030 has been approved, a preliminary implementation in https://github.com/openfisca/openfisca-france/pull/1663 seems to show that 3.7 and 3.8 pass tests, while 3.9 fails at least for the Web API.

**Comment by MattiSG** [comment]
#1030 has been approved, a preliminary implementation in https://github.com/openfisca/openfisca-france/pull/1663 seems to show that 3.7 and 3.8 pass tests, while 3.9 fails at least for the Web API.

**Comment by maukoquiroga** [comment]
@MattiSG great! In #1031 I've got all the tests passing for 3.9 but `test_shell_script_with_reform`, we can take a look together @HAEKADI if you think it could help.

**Comment by HAEKADI** [comment]
@maukoquiroga The `api-test` keeps running without exiting for Python 3.9. You can take a look at the [logs](https://github.com/openfisca/openfisca-france/runs/3459760268?check_suite_focus=true) on GitHub Actions. I had to stop the workflow manually 🤔

**Comment by MaxGhenis** [comment]
Since Python 3.9 has issues (https://github.com/openfisca/openfisca-core/issues/1035#issuecomment-913693451), I shrunk this issue down to Python 3.8. Python 3.8 support would be especially useful since it's the default conda Python version, and that's how many developers install Python.

**Comment by bonjourmauko** [comment]
This has been fixed in #1181
