### ISSUE TITLE
DeprecationWarning for imp module in tax_benefit_system.py

### ISSUE THREAD

**Issue by MaxGhenis** [openfisca/openfisca-core#1053]
>  /home/mghenis/anaconda3/lib/python3.8/site-packages/openfisca_core/taxbenefitsystems/tax_benefit_system.py:10: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module

https://github.com/openfisca/openfisca-core/blob/195fa723f1418e215a0c9eb351a96bd181cba10a/openfisca_core/taxbenefitsystems/tax_benefit_system.py#L10

**Comment by maukoquiroga** [comment]
Thanks @MaxGhenis ! 

It seems the offending code to be https://github.com/openfisca/openfisca-core/blob/195fa723f1418e215a0c9eb351a96bd181cba10a/openfisca_core/taxbenefitsystems/tax_benefit_system.py#L191-L195.

One possible solution to this would be to use the backwards-compatible functions provided by `importlib`:

```diff
-module_name = '{}_{}_{}'.format(id(self), hash(os.path.abspath(file_path)), file_name)
-
-module_directory = os.path.dirname(file_path)
-try:
-    module = load_module(module_name, *find_module(file_name, [module_directory]))
-
+module_name = f"{id(self)}_{hash(os.path.abspath(file_path))}_{file_name}"
+
+try:
+    spec = importlib.util.spec_from_file_location(module_name, file_path)
+    module = importlib.util.module_from_spec(spec)
+    sys.modules[module_name] = module
+    spec.loader.exec_module(module)
+
```

Do not hesitate to propose a fix for this 😃
