### ISSUE TITLE
Enlist OpenFisca as a UN Digital Public Good

### ISSUE THREAD

**Issue by ericherman** [openfisca/openfisca-core#1056]
Digital Public Goods is defined by [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods-candidates/blob/main/README.md) as *open source software, open data, open AI models, open standards and open content that adhere to privacy and other applicable best practices, do no harm and are of high relevance for attainment of [the UN’s 2030 Sustainable Development Goals (SDGs)](https://sdgs.un.org/goals)*. 

Does that definition apply to OpenFisca as well?

Could OpenFisca qualify to become a Digital Public Good?

If so, the page "[Contributing to Digital Public Goods](https://github.com/unicef/publicgoods-candidates/blob/main/CONTRIBUTING.md)" describes how to nominate a codebase for inclusion in Digital Public Goods.

**Comment by ericherman** [comment]
It seems to me there are some gaps which would need to bridged, for instance by expanding the contributing file or adding a code of conduct file.

**Comment by MattiSG** [comment]
Thanks @ericherman! This is interesting indeed. I don't identify a clear outcome from being listed as a “Digital Public Good” beyond reputation, so I wouldn't prioritise the associated work yet 🙂

For future reference, I believe that the [X-road](https://digitalpublicgoods.net/registry/x-road.html) entry would be a good example, as it is also infrastructure (compared to more topical entries).

**Comment by ericherman** [comment]
The process has begun:

* https://github.com/unicef/publicgoods-candidates/pull/760
* https://github.com/unicef/publicgoods-candidates/pull/761

**Comment by MattiSG** [comment]
# 🍾 
After quite a bit of work and an overly long time, I sent last month our [complete application](https://app.digitalpublicgoods.net/a/10318)… and we are now [officially recognised](https://twitter.com/OpenFisca/status/1636348008072617984) as DPG!
