### ISSUE TITLE
Remove unused Coveralls

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#1073]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

- Submit a PR from a third-party organisation.

### Here is what I expected to happen:

- CI passes.

### Here is what actually happened:

- CI fails on sending data to coveralls.io.

### Here is data (or links to it) that can help you reproduce this issue:

https://github.com/openfisca/openfisca-core/pull/1070#issuecomment-945785704

## Context

I identify more as a:

- Maintainer.

- - - - 

Coverage data storage was introduced by @maukoquiroga in b785382722eeb72b8cc72f18cb0942e0b6424c1e. It does not seem to be used by anyone in the build / release process, and a quick question on Slack did not yield any other reply. I am in favour of removing coveralls.io altogether, which I suggest to do unless someone chimes in within 4 days to say they use it, with a fast removal if @maukoquiroga confirms it can be removed.

The alternative would be to not execute the Coveralls CI job on third-party PRs.

**Comment by bonjourmauko** [comment]
This issue has again come to my attention now that we have matrix builds. Under that new scenario, I see no usefulness of collecting coverage information with Coveralls.

**Comment by benjello** [comment]
Please go on and remove the service no one use.

**Comment by bonjourmauko** [comment]
It is a low hanging fruit, @benjello don't you want to propose a PR?
