### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by JasonMorrisSC** [openfisca/openfisca-core#1078]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

Followed instructions at https://openfisca.org/doc/installation/windows-no-admin.html

### Here is what I expected to happen:

Successful install.

### Here is what actually happened:

On step 3, `pip install *` gives the following errors:

```
ERROR: Biryani-0.10.4-py2-none-any.whl is not a supported wheel on this platform.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) - skipping
(openfisca)
```

## Context

I identify more as a:

- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by maukoquiroga** [comment]
Thanks @JasonMorrisSC .

> What I wanted to do was get a Python environment where I could bootstrap a country package, encode some new legislation, and deploy it (just locally, for now) as a web API, in order to explore OpenFisca's capabilities

That's great input, we'll eventually redo that section of the doc from scratch.

> I eventually followed the instructions for bootstrapping a country package, and was able to sort of manually do what bootstrap.sh was supposed to do

🥳 

> But I still don't have openfisca-core installed on the machine

I've asked for help in the OpenFisca's community Slack if someone has  been confronted to that use case, so to provide you with a solution and at the same time update the doc.

In the meantime, you're more than welcome to join the Slack 😃 —if you prefer, for privacy concerns, to not share your email publicly, you can always contact me via Twitter or by email (contact@openfisca.org).

**Comment by benjello** [comment]
At IPP, we have to use openfisca on a windows system without admin rights.
We use Anaconda and install in a virtualenv all the deps of openfisca-core that are provided b Anaconda using conda and all the other deps using pip. It is cumbersome and not very efficient. That why I am in favor of #1039.

**Comment by maukoquiroga** [comment]
Thanks @benjello ! Do you think you could describe the step-by-step process? Perhaps you've already wrote it in an internal README at IPP, given you're continuously on-boarding people with that kind of system.

**Comment by JasonMorrisSC** [comment]
Happy to add the OpenFisca slack to my collection, but what is the domain name?

**Comment by maukoquiroga** [comment]
> Happy to add the OpenFisca slack to my collection, but what is the domain name?

🤣  https://github.com/openfisca/openfisca-core/blob/47f01b3a861874270ff193c7a155e61d716e0be6/README.md?plain=1#L5 (openfisca.slack.com)

**Comment by MattiSG** [comment]
I understand that this issue has been fixed by https://github.com/openfisca/openfisca-core/issues/1039: you can now use `conda` to install OpenFisca on all architectures, including Window without admin rights 🙂 (thanks @benoit-cty!)

Feel free to reopen if I got something wrong 😊
