### ISSUE TITLE
Publish to Conda is failing

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#1172]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I checked Github Actions.

### Here is what I expected to happen:

See only ✅ 

### Here is what actually happened:

I saw a ❌ 

### Here is data (or links to it) that can help you reproduce this issue:

https://github.com/openfisca/openfisca-core/actions/runs/3641267730/jobs/6147093427

## Context

Evolution of dependencies seem to have broken deploy to Conda.

**Comment by MattiSG** [comment]
@benoit-cty could you maybe have a look into this? 🙂

**Comment by benoit-cty** [comment]
Fixed on May 27, 2022 by https://github.com/openfisca/openfisca-core/pull/1127
