### ISSUE TITLE
Fixing docstrings

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#122]
_Issue by **[benjello](https://github.com/benjello)** from Friday Mar 15, 2013 at 11:27 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/119_

---

Use the following script after customization:
 https://github.com/pydata/pandas/issues/2916

**Comment by MattiSG** [comment]
This issue is never ending (and never started  ;)  ).

In order to increase the readability of the current active work in progress, I close this 3-years old issue.
