### ISSUE TITLE
Find a better name than qui*

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#132]
_Issue by **[benjello](https://github.com/benjello)** from Monday Mar 25, 2013 at 10:42 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/129_

---

quifm, quifoy and quimen (for the french case) are not very explicit.

**Comment by MattiSG** [comment]
1. Are these still in use in `core`?
2. If yes, is there any reason for those elements that seem to be linked to entities not to be moved towards each country's tax and benefit system?

_You may just say yes to both. I'm just trying to decide whether this issue should be closed, not get into its details._

cc @fpagnoux

**Comment by cbenz** [comment]
This issue should be in OpenFisca-France.

Following https://github.com/openfisca/openfisca-core/pull/415/files this issue has no reason to exist.

@fpagnoux tell me if I'm wrong

**Comment by fpagnoux** [comment]
These variables do not exist anymore.
