### ISSUE TITLE
Create a validation object that can be stored

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#170]
_Issue by **[benjello](https://github.com/benjello)** from Thursday Apr 18, 2013 at 09:55 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/167_

---

Should contain the id of the commit, the data and all the material to obtain the same results

**Comment by MattiSG** [comment]
This issue doesn't seem to be important since users could live for 4 years without it :wink:

In order to increase the readability of the current active work in progress, I close it.
