### ISSUE TITLE
method parameter adjustment

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#236]
_Issue by **[AlexisEidelman](https://github.com/AlexisEidelman)** from Tuesday Jun 11, 2013 at 08:21 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/237_

---

To run a legislation over a survey of a different year, we must define how to deal with change in price, income and so long. 
A method should change parameters as asked by user.

Possibly, a argument should be added to all parameter (for each country) expliciting how they must change (rate shouldn't), benefit amount and threshold could be changed in a different way (price and income)

**Comment by MattiSG** [comment]
This issue doesn't seem to be very important since users could live for 4 years without it :wink:

In order to increase the readability of the current active work in progress, I close it.
