### ISSUE TITLE
Save method for simulation 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#268]
_Issue by **[benjello](https://github.com/benjello)** from Tuesday Jul 09, 2013 at 15:12 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/269_

---

Find a way to save the relevant data for a simulation (including input tables and output tables optionally)

**Comment by MattiSG** [comment]
This issue doesn't seem to be very important since users could live for 4 years without it :wink:

In order to increase the readability of the current active work in progress, I close it.
