### ISSUE TITLE
create entities (family)

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#310]
_Issue by **[AlexisEidelman](https://github.com/AlexisEidelman)** from Sunday Dec 22, 2013 at 15:29 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/311_

---

Families should be generated using men information and links (father, mother, etc). 
It's already a legislation point since maximal age for children in families is set by law. 

Note that there is different union, Families for household benefit are not exactly the same as for family benefits. For Aspa it also different...

**Comment by MattiSG** [comment]
This issue doesn't seem to be very important since users could live for 3 years without it :wink:

In order to increase the readability of the current active work in progress, I close it.
