### ISSUE TITLE
[crash] 'CompactNode' object has no attribute 'assiette'

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#325]
With the latest `v0.5dev` on openfisca-web-api (659dac8e75bb409afede114f59c5fb3a8d86a5e6), openfisca-france (78ec32edbd0e7897960de714c95da345ffe765e5) and openfisca-core (555e99685f16b85d6f89c21ba1ff7689ba664524), I get a crash when I request the calculation of `allegement_fillon` (was `alleg_fillon` < 0.5).

The seemingly important parts of the trace are:

```log
14:57:59,557 ERROR [openfisca_core.formulas] An error occurred while calling formula individus@reintegration_titre_restaurant_employeur<2015-02> in openfisca_france.model.cotisations_sociales.remuneration_prive.reintegration_titre_restaurant_employeur
14:57:59,558 ERROR [openfisca_core.formulas] An error occurred while calling formula individus@salbrut<2015-02> in openfisca_france.model.cotisations_sociales.remuneration_prive.salbrut
14:57:59,558 ERROR [openfisca_core.formulas] An error occurred while calling formula individus@ratio_smic_salaire<2015> in openfisca_france.model.cotisations_sociales.allegements.function_2012
14:57:59,558 ERROR [openfisca_core.formulas] An error occurred while calling formula individus@allegement_fillon_annuel<2015> in openfisca_france.model.cotisations_sociales.allegements.allegement_fillon_annuel
14:57:59,558 ERROR [openfisca_core.formulas] An error occurred while calling formula individus@allegement_fillon<2015-01> in openfisca_france.model.cotisations_sociales.allegements.allegement_fillon

[…]

File "/Users/sgmap/Dev/openfisca-france/openfisca_france/model/cotisations_sociales/remuneration_prive.py", line 145, in function
simulation.legislation_at(period.start).cotsoc.assiette.cantines_titres_restaurants.taux_minimum_exoneration
AttributeError: 'CompactNode' object has no attribute 'assiette'
```

**This kills the server and all possible proxies, as the output is an HTML Internal Server Error and not a JSON output**, even though the requested content-type is JSON.

The full trace is available [here](https://gist.github.com/MattiSG/91cc73e0f8cf76ddf094) and not shown here for brevity (99 lines).

This regression happened in the past 10 days.

**Comment by benjello** [comment]
@MattiSG  please try with a date in 2014
@eraviart  it works for me on my computer for both date but the legislative parameters are not set for 2015

**Comment by eraviart** [comment]
Please give the JSON posted to /api/1/calculate that raises an exception and/or the name of the test. I have no clue of what you are testing.

**Comment by MattiSG** [comment]
@eraviart Sorry. Here is the JSON request:

```json
{  
    "scenarios":[  
        {  
            "test_case":{  
                "familles":[  
                    {  
                        "parents":[  
                            "ind0"
                        ]
                    }
                ],
                "foyers_fiscaux":[  
                    {  
                        "declarants":[  
                            "ind0"
                        ]
                    }
                ],
                "individus":[  
                    {  
                        "salbrut":{  
                            "2015-01":1445.38
                        },
                        "effectif_entreprise":2,
                        "activite":"Actif occupé",
                        "id":"ind0"
                    }
                ],
                "menages":[  
                    {  
                        "personne_de_reference":"ind0"
                    }
                ]
            },
            "period":"month:2015-01",
            "legislation_url":"http://api.openfisca.fr/api/1/default-legislation"
        }
    ],
    "variables":[  
        "allegement_fillon"
    ]
}
```

**Comment by MattiSG** [comment]
@benjello If I replace `2015-01` by `2014-06`, the result is still the same.

**Comment by eraviart** [comment]
@MattiSG The bug comes from line "legislation_url":"http://api.openfisca.fr/api/1/default-legislation"
Remove it from JSON and everything should/will work.

The problem comes from the fact that api.openfisca.fr & api-test-01.openfisca.fr dont share the same version of the legislation. And you were asking to use an obsolete legislation with up to date formulas.

**Comment by MattiSG** [comment]
@eraviart Confirmed & [fixed](https://github.com/sgmap/paie-api/commit/454bb3ad4d31638d04c032f3b4651485a392c0e1)! Thank you very much  :)

Was there any way I could have known other than trial and error?

**Comment by MattiSG** [comment]
And, more importantly: should I infer the `legislation_url` from the target host or just remove the line altogether and let the server figure it out?

**Comment by eraviart** [comment]
Always remove the line.
