### ISSUE TITLE
Deprecated function find_item_at_date

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#330]
The find_item_at_date function
https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/reforms.py#L119
seems to be used only by its own unit test
https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/tests/test_reforms.py#L33

This function is very specific and I think should be removed from core.reforms.

@benjello Can you confirm it is not used by any reform?

**Comment by benjello** [comment]
No objection from my part. @adrienpacifico do you it for modulation AF ?
