### ISSUE TITLE
Replace Makefile by Python invoke

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#335]
http://docs.pyinvoke.org/en/0.10.1/

**Comment by MattiSG** [comment]
The [makefile](https://github.com/openfisca/openfisca-core/blob/9b7f08ea90ff207f99aef95f9a4cc4ef204b34b7/Makefile) is small enough to be readable, and there is no user request to change it.

In order to increase the readability of the current active work in progress, I close this issue.
