### ISSUE TITLE
docstring test are not executed in travis

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#337]
Some docstring test are disseminated in directories that are not located inside tests are not executed.

**Comment by cbenz** [comment]
Fixed by commit a2e1ce4ab4ac7b105342fd7eb913390b6f56b584

Mistake introduced by commit 2692e32df93646442400ba4f5e35f95ddba1b753

**Comment by benjello** [comment]
Sorry. Was just cleaning my inbox ...

**Comment by cbenz** [comment]
no pb :)
