### ISSUE TITLE
Ease the legislation JSON manipulation

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#340]
When creating a `Reform` which changes the legislation JSON, the manipulation is not easy.

[This line](https://github.com/openfisca/openfisca-france/blob/0133e9343e4fa4c4e9335f841e5760721bacc86e/openfisca_france/reforms/aides_ville_paris.py#L346) tends to show the problem.

Another use case is to modify parameters programatically.

**Comment by cbenz** [comment]
After discussing with @fpagnoux and Mael (BTW what's his github username?):

- like the idea to switch back to XML for reforms (reforms are bundled with an XML subtree in a dedicated file)
- XML subtree is appended to the XML tree giving a "path" (get rid of the `["children"]` JSON navigation)
- helper functions manipulate hidden JSON representation or XML (useful when modifying existing parameters, without appending a whole subtree)

I'm still unsure, I'd like to be challenged. When I have time I'll prototype this and see.

Someday when switching to [YAML parameters](https://git.framasoft.org/french-tax-and-benefit-tables/ipp-tax-and-benefit-tables-yaml-clean) we'll port XML subtrees to YAML files.

**Comment by MattiSG** [comment]
> BTW what's his github username?

@laem

> I'd like to be challenged

The more declarative we go the better, IMO. Switching from XML to YAML would also be welcome, but that's a matter of simplifying a format rather than improving the representation itself. I consider this format change as less important than splitting the file in several ones.

**Comment by cbenz** [comment]
@MattiSG thanks

**Comment by cbenz** [comment]
We ended up expressing legislation changes in a syntax close to `simulation.legislation_at`:

```python
value = legislation_at(instant).x.y
# value == 999

update_legislation_between(start = instant1, stop = instant2).x.y = 888
```

The `legislation_json` is not modified, but the updates are stored in a list so when `legislation_at(instant)` is called, the `CompactNode` is built as usual. When the `CompactNode` is used with `.x.y` paths we just have to check if `instant` is between `start` and `stop` before returning the value, and return the modified value if relevant.

To be implemented...

**Comment by benjello** [comment]
Sounds good to me. Should be usable in a reform though.

**Comment by cbenz** [comment]
The main target is reforms.

**Comment by MattiSG** [comment]
This issue is never ending (and never started  ;)  ).

In order to increase the readability of the current active work in progress, I close this 2-years old issue.
