### ISSUE TITLE
Remove deprecated update_legislation()

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#344]
Remove deprecated [`update_legislation`](https://github.com/openfisca/openfisca-core/blob/18f72180529470664c79e228ed0ad544a42de6f5/openfisca_core/reforms.py#L188) function.

Blocked by openfisca/openfisca-france#317

See #340

**Comment by MattiSG** [comment]
`update_legislation` is [not deprecated anymore](https://github.com/openfisca/openfisca-france/issues/317#issuecomment-249515726).
