### ISSUE TITLE
Brainstorm about updating the legislation in reforms

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#345]
In order to replace [`update_legislation`](https://github.com/openfisca/openfisca-core/blob/18f72180529470664c79e228ed0ad544a42de6f5/openfisca_core/reforms.py#L188) which is deprecated (see #344), we have to find a simple way to update the legislation in reforms.

@benjello Here we list the needs, what are the use cases?

Perhaps this is a non-issue, and we can instead brainstorm about #340

**Comment by benjello** [comment]
The are different situation than #340. Imagine you just want to do a parametric reform by only modifying parameters of the legislation. We should be able to do that easily.
