### ISSUE TITLE
Support for dated formulas in reforms

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#346]
Questions around reforms and dated formulas:
- Does a dated formula in a reform updates or replaces the reference? So does a reform author have to duplicate the whole class in order to change only one method?
- Is it possible to overload a simple formula with a dated formula in a reform?
- Is it possible to overload a dated formula with a simple formula in a reform?

Furthermore, this issue is an invitation to brainstorm about it.

CC @eraviart

**Comment by MattiSG** [comment]
This 2.5-years old invitation to brainstorm seems to not have met many conclusions :wink:
Closing.
