### ISSUE TITLE
Don't accept circular references

### ISSUE THREAD

**Issue by eraviart** [openfisca/openfisca-core#347]
When AL requires AL (month - 1) and AL (mont - 1) requires RSA (month-4 to month - 2) break cycle immediately and return default value.

Try to do this for every formula, not only RSA & AL.

**Comment by cbenz** [comment]
Now OpenFisca handles some cyclic dependencies cases, see unit tests https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/tests/test_cycles.py
