### ISSUE TITLE
Problem with erratic rates.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-core#349]
When the observations are close enough (e.g 10 euros of gap between each salaire de base), the marginal rates are not correct.

See [this notebook](https://github.com/adrienpacifico/bug-openfisca/blob/master/decote_en_dur_3%20bug%20report.ipynb) as an exemple.

**Comment by benjello** [comment]
Please try with a single and then we will look at the coupe. I suspect that you mix a foyer value with indvidual value and thus inducing a mismatch in vector sizes.

**Comment by benjello** [comment]
You can take a look at https://github.com/openfisca/openfisca-matplotlib/tree/master/openfisca_matplotlib
for drawing rates. Notebook examples would be nice ;-)

**Comment by adrienpacifico** [comment]
> Please try with a single and then we will look at the coupe. I suspect that you mix a foyer value with indvidual value and thus inducing a mismatch in vector sizes.

Here it is : [Notebook rates single](https://github.com/adrienpacifico/bug-openfisca/blob/master/decote_en_dur_3%20bug%20report%20single.ipynb)
The problem is still here. I am suspecting wrong rounding (or something else) with the core.

> You can take a look at https://github.com/openfisca/openfisca-matplotlib/tree/master/openfisca_matplotlib
for drawing rates.

Yes thanx, test_graph.rates() doesn't work for me @home (If I wish I could make it work, I think).

The problem with rates doesn't occur if I'm doing only 100 simulations, but at 200 I'm stating to get some artefacts (that I can smooth), and around a 1000 I'm getting what you've seen on my notebook.

But at 1000 simulations the spread between two net wages (or revenu brut global) is around 30 euros... I don't think we should observe that with such large spread.

**Comment by benjello** [comment]
@adrienpacifico: some of the IR bases and the IR is rounded so it may explain that.
Can you produce two simple test-case with a high jump so we can try to understand things here before calling in @eraviart and @cbenz ;-)

**Comment by adrienpacifico** [comment]
Yep, I will.

**Comment by benjello** [comment]
@adrienpacifico Should we close this ?

**Comment by adrienpacifico** [comment]
Maybe, I'm still not satisfied with the provided solution and I'm kind of working on one. This still could be a space where we can talk about it. 

But I you prefers to close it, to keep only "real" issues opened, you can without hesitating.

**Comment by adrienpacifico** [comment]
Thanx by the way for your help, that helped me to understand the issue I was facing.
