### ISSUE TITLE
Ease the numpy arrays related code

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#354]
This is a proposal to enhance the clarity of the code related to numpy arrays.

The point is only to treat each code construct which is a trick without providing a global abstraction over numpy.

**Comment by cbenz** [comment]
As seen with @fpagnoux

**Comment by fpagnoux** [comment]
I started working on [this branch](https://github.com/openfisca/openfisca-france/tree/do-not-use-zeros-or-other-tricks)

**Comment by fpagnoux** [comment]
@cbenz 
I don't get [this one] (https://github.com/openfisca/openfisca-france/blob/do-not-use-zeros-or-other-tricks/openfisca_france/model/prestations/minima_sociaux/rsa.py#L668) I'll let you handle it ;]

**Comment by fpagnoux** [comment]
There is a few `zeros` remaining in commented code [here](https://github.com/openfisca/openfisca-france/blob/do-not-use-zeros-or-other-tricks/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py#L21), [there](https://github.com/openfisca/openfisca-france/blob/do-not-use-zeros-or-other-tricks/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py#L211), and [there](https://github.com/openfisca/openfisca-france/blob/do-not-use-zeros-or-other-tricks/openfisca_france/model/prestations/prestations_familiales/paje.py#L648) : 

I don't know what to do with it.

**Comment by benjello** [comment]
You can remove the first and last ones

**Comment by fpagnoux** [comment]
From what I've seen  we are only using these zeroed numpy arrays in three cases: 
- For loops. In this case they can be replaced by a generator.
- For formulas that are only partly implemented.
- The case I mentioned in rsa.py that seems specific.

I replaced the dirty stuff by the cleaner by not clearer `zeros(self.holder.entity.count)`. I guess it would make sense to have something like `self.zeros()` instead. 

I haven't found any `numpy.ones()` in the code.

**Comment by cbenz** [comment]
Good, and thanks for the atomic commits.

**Comment by cbenz** [comment]
About 235c358a557576173348f8ff2cd3d2e3b900492f don't you think that we lost the boundaries of the formula you remove?

**Comment by fpagnoux** [comment]
I'm pretty sure these start boundaries are fantasist. The ACS has been introduced in 2005, not in 2000. For the af coefficient, I coded it and I know this 2002  just aimed at having a default value, so behavior is the same.

**Comment by cbenz** [comment]
Implemented in `next`.
