### ISSUE TITLE
Simplify variables vocabulary and syntax

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#355]
Following #348 discussion, here are some ideas.

Merge `@reference_formula` decorator with `SimpleFormulaColumn` metaclass.

Before:

```python
# Input variable
reference_input_variable(
    name = "age",
    column = IntCol,
    entity_class = Individus,
    )

# Variable with formula
@reference_formula
class irpp(SimpleFormulaColumn):
    column = FloatCol
    entity_class = FoyersFiscaux

    def function(self, simulation, period):
        return period, x
```

After:

```python
# Input variable
class age(Variable):
    column = IntCol
    entity_class = Individus

# Variable with formula
class irpp(Variable):
    column = FloatCol
    entity_class = FoyersFiscaux

    def function(self, simulation, period):
        return period, x
```

**Comment by benjello** [comment]
It is clean and i follow you on that side. But didn't you loose the information by removing the  reference_formula decorator ?

**Comment by cbenz** [comment]
No problem, sorry I didn't explain.

The Variable inherited class would be different in openfisca-france and extensions:

- In OpenFisca-France:

  ```python
  from .formulas import Variable

  class irpp(Variable):
      column = FloatCol
      entity_class = FoyersFiscaux

      def function(self, simulation, period):
          return period, x
  ```

- In an extension:

  ```python
  Reform = reforms.make_reform(...)

  class irpp(Reform.Variable):
      column = FloatCol
      entity_class = FoyersFiscaux

      def function(self, simulation, period):
          return period, x
  ```

**Comment by benjello** [comment]
Ok then.

**Comment by fpagnoux** [comment]
Any news on this topic ? I can help this week if needed.

**Comment by cbenz** [comment]
We forget to handle a case when a reform updates a variable giving the `reference = ` attribute: 150325583ee13ec2900a7b5b76b22777f73b2d65 and test b84c00e33d315422c6e9d21936f1843250fdd106

**Comment by cbenz** [comment]
Tests still don't pass with https://github.com/openfisca/openfisca-france-indirect-taxation

**Comment by cbenz** [comment]
Merged in `master` of all projects, pushed, Travis tests ongoing (but all were OK on my machine).

In case of emergency please just do `git reset --hard <ref>` where `<ref>` is the last commit before merge.

**Comment by cbenz** [comment]
Good work everyone!

**Comment by cbenz** [comment]
Not closing issue because of https://github.com/openfisca/openfisca-france/issues/350, https://github.com/openfisca/openfisca-france/pull/369 and https://github.com/openfisca/openfisca-core/pull/365

**Comment by benjello** [comment]
@fpagnoux @cbenz : should we close this issue ?

**Comment by fpagnoux** [comment]
I would say yes.

**Comment by fpagnoux** [comment]
And [this one](https://github.com/openfisca/openfisca-france/issues/350) as well.
