### ISSUE TITLE
Replace dated variables by simple variables

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#356]
Since dated variables formulas have the same parameters than simple formulas `(self, simulation, period)`, we can replace dated formulas by simple.

The formula uses a `if` to determine the right formula.

Otherwise the author can decide to create many distinct variables.

(like in the Julia version)

**Comment by benjello** [comment]
Need an example. Might adding more trouble than simplification for a lot of contributors.

**Comment by cbenz** [comment]
A dated variable could be:

```python
class rmi(Variable):
    column = FloatCol
    entity_class = Familles

    def function(self, simulation, period):
        return period, x

class rsa(Variable):
    column = FloatCol
    entity_class = Familles

    def function(self, simulation, period):
        if period.start >= date(2009, 06, 1):
            return period, x
        else:
            return period, x
```

**Comment by benjello** [comment]
I really do prefer the present implementation: it has more structure and when you focus on one formula you focus on the formula of a particular time interval. I do not think that there is too much structure for this precise purpose. I think formula and variable needs more homogenisation than than structure simplification.

**Comment by cbenz** [comment]
OK I understand.

The point was mainly to simplify the API and web tools, which currently have to treat dated formulas in a specific manner. I think of Trace tool and Legislation explorer.

But that's not a so big work.

**Comment by cbenz** [comment]
I close this issue, thanks for the quick replies!

**Comment by MattiSG** [comment]
Done in https://github.com/openfisca/openfisca-core/issues/371.
