### ISSUE TITLE
Upgrade to NumPy 1.10

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#357]
Casting errors: 
- Date comparison fails
- Mixing integers and float fails

**Comment by cbenz** [comment]
I confirm the bug, I tried on my machine.

**Comment by cbenz** [comment]
I restricted the dependencies versions: openfisca/openfisca-france@6f00fd605d9da74b9fbc7e68f55e13899f8fb7e5 and a437a1d2cc27f6fab7def550f0efbbc1720607cf

**Comment by benjello** [comment]
It is becoming difficult to work on debian without numpy 1.10 so I added the prio-high label

**Comment by cbenz** [comment]
https://github.com/openfisca/openfisca-france/commit/a9c3713691829f9a6213230d394b554e9074eb00 and https://travis-ci.org/openfisca/openfisca-france

**Comment by benjello** [comment]
@cbenz: do you intend to merge this PR quickly or should I include it manually locally ?

**Comment by benjello** [comment]
Sorry it is done ...

**Comment by cbenz** [comment]
:cupid:
