### ISSUE TITLE
Improve assert_near

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#360]
`openfisca_core.tools.assert_near` could be greatly improved if it could deal with series of couples of `(value, target_values)`. The assertion should give you a complete view of how the test failed for all the variables. When you debug you need a complete view.
 
@cbenz what do you think?

**Comment by benjello** [comment]
BTW the dafault argument absolute_error_margin = 0 is misleading

**Comment by cbenz** [comment]
I don't fully understand, could you give an example? Do you have

**Comment by cbenz** [comment]
What should the default argument be?

**Comment by cbenz** [comment]
I enhanced the default arguments: 5424818d255d4e061487abdbae0b4e93217614ff

Please confirm if it's better!

**Comment by benjello** [comment]
ok for this part. Forget the other or assign it to me and i will come back to you later

**Comment by cbenz** [comment]
OK, please come back with a use case.
