### ISSUE TITLE
Replace all period expressions by shortcuts

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#361]
Commits cca60265b5796b31f662b3949b22eaf1b22ea0b7 and 1ffeb36c8a79d8d906e9d2e6c3848868f44ad09e introduced period shortcuts.

We must replace all expressions that may be written with a shortcut, by its shortcut.

**Comment by MattiSG** [comment]
I would recommend using [opportunistic refactoring](http://martinfowler.com/bliki/OpportunisticRefactoring.html) rather than full-on refactor phases (that have the side-effect of preventing proper history searches for bug causes).
