### ISSUE TITLE
Introduce OpenFisca command-line client

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#362]
This is a proposal which may be discussed.

I'd like to introduce an OpenFisca command-line client.

Use cases:

```
$ openfisca test:yaml embauche.sgmap.fr/test_embauche_55c1dbb46149d1903b3d1e27.yaml
$ openfisca json-test-case-to-vectors <file_path>
```

This would be done using a `console` `entry_point` of the `setup.py` of openfisca-core.

**Comment by MattiSG** [comment]
Good idea to ease usage!  :)

But what about focusing on simplifying the architecture rather than adding tools to face the complexity?  ;)
