### ISSUE TITLE
Short-circuit boolean multiplication with NumPy (to mimic an "if")

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#363]
> This issue follows a discussion with @laem

In some formulas (@laem do you remember which one?) an array is multiplied by a array of booleans.

I'm pretty sure that numpy does some optimisations, in particular when all the values are `False`:

```python
np.array([1,2,4]) * np.array([False, False, False]) => array([0, 0, 0])
```

But when the code of the formula is like:

```python
def function(self, simulation, period):
   numbers = simulation.calculate('numbers', period)
   booleans = simulation.calculate('booleans', period)
   return period, numbers * booleans
```

Even if `booleans` is an array of booleans all `False`, `numbers` will have been calculated.
Of course there are some real formulas in which `numbers` is an expensive computation.

Maybe the formula should have been written like this:

```python
def function(self, simulation, period):
   booleans = simulation.calculate('booleans', period)
   numbers = self.zeros() \
        if all(booleans == False) \
        else simulation.calculate('numbers', period)
   return period, numbers * booleans
```

For those who know NumPy idioms what do you think?
@benjello @eraviart

**Comment by benjello** [comment]
Cannot help you but if your solution increases performance it is a go for me.

**Comment by cbenz** [comment]
Or we could add a helper...

**Comment by benjello** [comment]
Go for a helper that could work with all eligibility dummies.

**Comment by laem** [comment]
:+1: 
A good example is `class allegement_fillon` : 
```python
period = period.this_month
        stagiaire = simulation.calculate('stagiaire', period)
        apprenti = simulation.calculate('apprenti', period)
        allegement_fillon_mode_recouvrement = simulation.calculate('allegement_fillon_mode_recouvrement', period)
        allegement = (
            # en fin d'année
            allegement_fillon_mode_recouvrement == 0) * (
                compute_allegement_fillon_annuel(simulation, period)
                ) + (
            # anticipé
            allegement_fillon_mode_recouvrement == 1) * (
                compute_allegement_fillon_anticipe(simulation, period)
                ) + (
            # cumul progressif
            allegement_fillon_mode_recouvrement == 2) * (
                compute_allegement_fillon_progressif(simulation, period)
            )
        return period, allegement * not_(stagiaire) * not_(apprenti)
```
You can find references to this issue as `short circuit multiplication`...

**Comment by cbenz** [comment]
Or else:

```python
def function(self, simulation, period):
    booleans = simulation.calculate('booleans', period)
    if all(booleans == False):
        numbers = simulation.calculate('numbers', period)
        return period, numbers * booleans
    return self.zeros()
```

**Comment by cbenz** [comment]
For the record:

- it's possible to replace `booleans * numbers` by [`np.where`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html): `np.where(booleans, numbers, 0)` (like a ternary operator)
- there is [`lazyarray`](http://lazyarray.readthedocs.org/en/latest/tutorial.html) which [says](http://lazyarray.readthedocs.org/en/latest/performance.html):

  > The main aim of `lazyarray` is to improve performance when [...] arrays are used conditionally

Good explanation on [Python for Data Analysis](https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/ch04.html#I_programlisting4_d1e6710)

**Comment by benjello** [comment]
I am not sur that where is more performant than multiplication with boolean.

**Comment by cbenz** [comment]
I agree, I only mention that because NumPy 1.10 enforced type checks. To be continued on #357

**Comment by laem** [comment]
Concerning the formula `allegement_fillon` cited above, see this alternative syntax 611ffa87e9d954fa2db0a31dbe2fa0638ece767f

**Comment by cbenz** [comment]
So here is the test: https://github.com/openfisca/openfisca-core/blob/fa2174cd5ec4514f0b76b47ccab190480e40b17a/openfisca_core/tests/test_formulas.py#L74-L83

And the timed results:

```
~/D/o/openfisca-core (switch-helper|✚2…) $ nosetests openfisca_core/tests/test_formulas.py:test_switch
.
----------------------------------------------------------------------
Ran 1 test in 4.969s

OK
~/D/o/openfisca-core (switch-helper|✚2…) $ nosetests openfisca_core/tests/test_formulas.py:test_multiplication
.
----------------------------------------------------------------------
Ran 1 test in 4.655s

OK
```

But the `case_one` and `case_two` functions are very cheap.
I should test it with a real computation...

**Comment by cbenz** [comment]
After some tests I conclude that the most expensive between iterating in Python over a big array and computing for nothing some values, is the iteration.

Thanks @benjello for insisting on that :)

So what I did is keeping the convinient syntax of [`self.switch`](https://github.com/openfisca/openfisca-core/blob/d49aaee973cd61a2dd1069b0b67c9975982e9bc7/openfisca_core/tests/test_formulas.py#L41-L47) but [implemented it](https://github.com/openfisca/openfisca-core/blob/d49aaee973cd61a2dd1069b0b67c9975982e9bc7/openfisca_core/formulas.py#L76-L95) with [`np.select`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.select.html) which applies the conditions the same way than the form `(conditions == choice1) * value1 + (conditions == choice2) * value2 + [etc]`.

With big arrays the average timings are equal.

I think we can stop there the investigation for optimisations since iterating over arrays is expensive and the Core's cache does a good job.

We can now use the `self.switch` helper to simplify the expressions. I'll add it to the documentation (openfisca/openfisca-gitbook#4).

Perhaps there is one last tradeoff which would consist of (not iterating over arrays) testing if `np.any(conditions == specific_value)` and generate dynamically the dict given to `self.switch`, but I don't know the cost of `np.any`:

```python
    def function(self, simulation, period):
        choice = simulation.calculate('choice', period)
        value_by_choice = {1: calculate_cheap_value()}
        if np.any(choice == 2):
            value_by_choice[2] = calculate_expensive_value()
        result = self.switch(choice, value_by_choice)
        return period, result
```

@laem It would be cool to test it on an expensive "fillon" formula.

**Comment by fpagnoux** [comment]
> After some tests I conclude that the most expensive between iterating in Python over a big array and computing for nothing some values, is the iteration.

Can you give an order of magnitude of the difference observed ? It's really interesting to quantify on concrete experiments the benefits of vectorial computing :)
Have you also carried out experiments on smaller sets of individuals ? Does avoiding computing useless value improve performances in these cases? mes-aides and embauche, and I guess douanes will involve `O(1)` entities, so testing it would be nice too.

**Comment by benjello** [comment]
I think than np.any performance should go down with vector size so we may have option to switch behavior for this kind of variables since performance would be highly use case dependent.

**Comment by cbenz** [comment]
> Can you give an order of magnitude of the difference observed ? It's really interesting to quantify on concrete experiments the benefits of vectorial computing :)

I'd say that it depends on the context: the cost of the computations we'd like to avoid (ie `allegement_fillon`) versus the time iteration is done in Python. I didn't want to test it explicitely because it would have depended on the cost of the formula computation.

What I did test is the time of iteration in Python over a 1e5 array, and it's > 10 seconds. I don't mention about 1e6 ... never really finished the test, I had to interrupt it.

So that's why I advocate for a `switch` helper which outputs an expression equivalent to the multiplication syntax, and rely on the cache of the Core.

For more explanation we can see IRL :)

**Comment by laem** [comment]
Would it be possible to have this "versus" test somewhere ? It could be interesting for trying other possible optimization in the future :smiley:

**Comment by cbenz** [comment]
I'm cleaning it in order to publish it

**Comment by cbenz** [comment]
https://github.com/openfisca/openfisca-core/blob/8d01a649258a2be9e6fc2f997c0d3132bc9e1e4b/openfisca_core/scripts/measure_numpy_condition_notations.py

**Comment by cbenz** [comment]
```
~/D/o/openfisca-core (switch-helper|✔) $ ./openfisca_core/scripts/measure_numpy_condition_notations.py --array-length 1000 --calculate-time 0.5
Namespace(array_length=1000, calculate_time=0.5)
multiplication	: 1.50179911 seconds elapsed
switch_select	: 1.50178385 seconds elapsed
switch_fromiter	: 1.00239992 seconds elapsed
~/D/o/openfisca-core (switch-helper|✔) $ ./openfisca_core/scripts/measure_numpy_condition_notations.py --array-length 1000000 --calculate-time 0.5
Namespace(array_length=1000000, calculate_time=0.5)
multiplication	: 1.54225183 seconds elapsed
switch_select	: 1.51782680 seconds elapsed
switch_fromiter	: 1.29510999 seconds elapsed
~/D/o/openfisca-core (switch-helper|✔) $ ./openfisca_core/scripts/measure_numpy_condition_notations.py --array-length 100000000 --calculate-time 0.5
Namespace(array_length=100000000, calculate_time=0.5)
multiplication	: 6.82061815 seconds elapsed
switch_select	: 3.25079989 seconds elapsed
^CTraceback (most recent call last):
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 138, in <module>
    sys.exit(main())
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 134, in main
    test_all_notations()
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 122, in test_all_notations
    test_switch_fromiter(choice)
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 91, in test_switch_fromiter
    dtype = np.int,
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 48, in switch_fromiter
    dtype,
  File "./openfisca_core/scripts/measure_numpy_condition_notations.py", line 46, in <genexpr>
    for condition in conditions
KeyboardInterrupt
~/D/o/openfisca-core (switch-helper|✔) $ ./openfisca_core/scripts/measure_numpy_condition_notations.py --array-length 10000000 --calculate-time 0.5
Namespace(array_length=10000000, calculate_time=0.5)
multiplication	: 1.71356606 seconds elapsed
switch_select	: 1.71171999 seconds elapsed
switch_fromiter	: 3.96232009 seconds elapsed
```

**Comment by cbenz** [comment]
What I find interesting is that np.select is more efficient than multiplication notation, perhaps due to the intermediary array of booleans creation for multiplication notation.

**Comment by cbenz** [comment]
@fpagnoux introduced [`apply_threshold`](https://github.com/openfisca/openfisca-core/blob/fb89914be2c511a2d34551f97424a687b67bae9f/openfisca_core/formula_helpers.py)

@fpagnoux What do you think of my last additions in https://github.com/openfisca/openfisca-france/tree/use-helpers ?

**Comment by cbenz** [comment]
@fpagnoux And since my last addition of [`switch`](https://github.com/openfisca/openfisca-core/commit/6d2dc2439f0871356a3955e4e2f50a0efc488e72#diff-04cf99044a88ae295a0e6071d6380cfcR34) do you prefer using it or using [`np.select` directly](https://github.com/openfisca/openfisca-france/commit/915b3748f14bc1bfefaf106618d80e3b6b12f12f#diff-6cfe75440d7ad5c949e1b1e8f5b7c2b0R345)?

**Comment by fpagnoux** [comment]
I'm happy to use switch for appropriate situations, but I haven't met so much `switch` cases recently. `np.select` has the advantage of being very flexible, and quite often the conditions are more complex than an equality.
I'm also using `np.where` more and more

**Comment by benjello** [comment]
You might be interested by creating an isin helper as in [pandas] (http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.isin.html) using [numpy.in1d] (http://docs.scipy.org/doc/numpy/reference/generated/numpy.in1d.html)
Migh be useful in a lot of places like this [one] (https://github.com/sgmap/openfisca-france/pull/40/files) (test on statut_occupation in paris_logement_plfm Variable)

**Comment by cbenz** [comment]
Helpers are in master now, closing issue.
