### ISSUE TITLE
Store columns directly in TaxBenefitSystem

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#366]
As discussed with @eraviart and @fpagnoux the idea is to store the columns directly in `TaxBenefitSystem` instead of entities.

Columns are generated by parsing Variable classes via metaclasses.

Currently the entities store the columns in [column_by_name](https://github.com/openfisca/openfisca-core/blob/d62ff6b0eb3e81f4ceebdbee2d64e0c90848c20a/openfisca_core/entities.py#L8) and `TaxBenefitSystem` merges the dicts [here](https://github.com/openfisca/openfisca-core/blob/d62ff6b0eb3e81f4ceebdbee2d64e0c90848c20a/openfisca_core/taxbenefitsystems.py#L45-L50)

**Comment by fpagnoux** [comment]
:+1:

**Comment by benjello** [comment]
@fpagnoux @cbenz : shouldn't we close this issue ?

**Comment by fpagnoux** [comment]
Yes, let's close it.
