### ISSUE TITLE
Rename PersonToEntityColumn

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#373]
Should use `PersonToEntityVariable` to be in line with `Variable`, `DatedVariable` etc
But wait for my go before merging ;-)

**Comment by cbenz** [comment]
Merging what? :)

But yes, this rename should be done too.

**Comment by benjello** [comment]
merging any PR with the renaming. I am catching up several modifications and I cannot handle huge change for a couple of days ...

**Comment by benjello** [comment]
@cbenz : you can proceed with this renaming, but propagate the changes to baremes-ipp too.

**Comment by fpagnoux** [comment]
PersonToEntityColumn have been deprecated and removed a while ago.
