### ISSUE TITLE
Provide helpers for reform

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-core#376]
It could be good to have features in order to easily run a reform.
- [ ] **Easily disable a Variable** : Give a list of Variables (formulas) that would be taken away from the reformed tax benefit system
  - Disable the Variable
  - Return a null or None value when called by an other Variable 
- [ ] **Easily change period** : Change a period for one Variable, and smoothly adapt to other called formulas in the uptream and downstream variables and transversal variables. 
  1. One way could be to change transversal variables `period = period.this_month` to `period = period` (as it was before in the code) ; possible errors due to period would be at the "user" own risk.
  2. An other way could be a more fancy automatic way that would transform calculate to calculate_add or divide, etc. Full specification might be a bit complicated.
- [ ] **Easily change parameters** : Change a parameter already existing in the params
  - `Reform.change_param.ir.plafond_qf.celib(value = 2000, start = "01-01-2001", stop = None)` 
  - or 
    `Reform.change_bareme_param.ir.plafond_qf.celib(value = {tranche1 : 699, tranche2 : 825}, start = "01-01-2001", stop = None)`

What do you think ?

**Comment by benjello** [comment]
- Reform with neutralize_column  already exists, look at in [this test] (https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/tests/test_reforms.py#L20)
 - It will be very difficult to implement a safe mechanism.
 - Should be the never ending forthcoming task to @cbenz ;-)

**Comment by cbenz** [comment]
Thanks @adrienpacifico for formalizing your needs and thoughts!

**Comment by Morendil** [comment]
Closing this as very, very stale.
