### ISSUE TITLE
baremes-ipp

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#380]
Merging #377 #378 and #379 into openfisca-core baremes-ipp branch breaks openfisca-france's baremes-ipp branch tests.
@cbenz @fpagnoux @laem

**Comment by fpagnoux** [comment]
#378 has been closed and won't be merged. Do you still have a bug with only #377 and 379 ?
What is the error you get ?

**Comment by benjello** [comment]
My fault, everything seem [ok] (https://travis-ci.org/benjello/openfisca-france/builds/112918767)
