### ISSUE TITLE
web_tools.get_trace_tool_link not working

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#381]
The trace tool return nothing when using web_tools.get_trace_tool_link not working
See this [example] (http://notebook.openfisca.fr:8888/notebooks/2015-10-31-hackathon-reformes/exemple%20graphs.ipynb)

**Comment by cbenz** [comment]
The new way is:
```
from openfisca_core import tools
print tools.get_trace_tool_link(scenario, ['allegement_fillon'], api_url='http://api.openfisca.fr/', trace_tool_url='http://www.openfisca.fr/tools/trace')
```

**Comment by cbenz** [comment]
cf http://doc.openfisca.fr/en/web-tools/trace_tool.html
