### ISSUE TITLE
flake8

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#389]
I got [this new error](https://travis-ci.org/openfisca/openfisca-core/builds/138029856) when pushing to baremes-ipp branch.

@fpagnoux, @laem, @cbenz: should we ban star imports ?

Am-i missing something else ?

**Comment by laem** [comment]
I try to conform to pep8 but I don't know much about it... I could'nt make PyCharm, my editor work with it so it's a bit painful.

**Comment by benjello** [comment]
See https://github.com/openfisca/openfisca-core/blob/master/setup.cfg
