### ISSUE TITLE
Add all module variables to a reform

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#392]
Is there a way to easily load all variables form a module to a reform ?
I am trying to migrate openfisca-france-data. See [here](https://github.com/openfisca/openfisca-france-data/blob/master/openfisca_france_data/model/base.py) and [here](https://github.com/openfisca/openfisca-france-data/blob/master/openfisca_france_data/__init__.py).

@fpagnoux @cbenz : i need your help ;-)

**Comment by benjello** [comment]
I found a way. I will submit it to your judgement tomorrow.

**Comment by fpagnoux** [comment]
You can use one of these methods in `self.apply`:

`self.add_variables_from_file(file)` will import all Variable subclasses contained in python file `file`.

`self.add_variables_from_directory(directory)` will browse a directory recursively looking for variables, and load them.

Is this what you were looking for ?

**Comment by benjello** [comment]
Cannot use those method for aliss reform in indirect taxation. But might be valuable for other use.
Thanks @fpagnoux.
