### ISSUE TITLE
What's the use of having both entity_by_key_singular and entity_by_key_plural ?

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-core#407]
Hi all,

I am wondering is there any use, except of the naming convenience, between plural and singular keys of entities ?

If not, wouldn't it be better to have only an entity_by_key with a singular key instead of keeping both ?

Many thanx in advance for your answers !

**Comment by benjello** [comment]
Mainly history, I think.
@cbenz @eraviart : do you agree ?

**Comment by eraviart** [comment]
yes

On Mon, 2016-08-29 at 03:11 -0700, Mahdi Ben Jelloul wrote:
> Mainly history, I think.
> 
> @cbenz @eraviart : do you agree ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/openfisca
/openfisca-core","title":"openfisca/openfisca-
core","subtitle":"GitHub repository","main_image_url":"https://cloud.
githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/openfisca/openfisca-
core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@benjello
in #407: Mainly history, I think.\r\n@cbenz @eraviart : do you agree
?"}],"action":{"name":"View
Issue","url":"https://github.com/openfisca/openfisca-
core/issues/407#issuecomment-243086091"}}}

**Comment by fpagnoux** [comment]
I've worked recently on a refactoring of `entities`. This may disappear soon :)
