### ISSUE TITLE
bareme.calc returns NaN sometimes

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-core#410]
Hi @benjello, following https://github.com/openfisca/openfisca-france/pull/573 I've found that `apply_bareme_for_relevant_type_sal` in `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/base.py` calls `iter_cotisations` which calls `openfisca_core.taxscales.MarginalRateTaxScale.calc`.

This last function returns sometimes the `NaN`, in particular [this line](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/taxscales.py#L198)

Should we add a check here? or is the problem upstream?

Here is the context:

``` python
     18     def iter_cotisations():
     19         for type_sal_name, type_sal_index in CAT:
     20             if type_sal_name not in bareme_by_type_sal_name:  # to deal with public_titulaire_militaire
     21                 continue
     22             bareme = bareme_by_type_sal_name[type_sal_name].get(bareme_name)  # TODO; should have better warnings
     23             if bareme is not None:
     24                 yield bareme.calc(
     25                     base * (categorie_salarie == type_sal_index),
     26                     factor = plafond_securite_sociale,
---> 27                     round_base_decimals = round_base_decimals,
     28                     )
     29     return - sum(iter_cotisations())

ipdb> plafond_securite_sociale
array([ 0.], dtype=float32)
```

``` python
    194     def calc(self, base, factor = 1, round_base_decimals = None):
    195         base1 = np.tile(base, (len(self.thresholds), 1)).T
    196         if isinstance(factor, (float, int)):
    197             factor = np.ones(len(base)) * factor
    198         thresholds1 = np.outer(factor, np.array(self.thresholds + [np.inf]))
    199         if round_base_decimals is not None:
    200             thresholds1 = np.round(thresholds1, round_base_decimals)
    201         a = max_(min_(base1, thresholds1[:, 1:]) - thresholds1[:, :-1], 0)
--> 202         if round_base_decimals is None:
    203             return np.dot(self.rates, a.T)
    204         else:
    205             r = np.tile(self.rates, (len(base), 1))
    206             b = np.round(a, round_base_decimals)
    207             return np.round(r * b, round_base_decimals).sum(axis = 1)
    208 

ipdb> base
array([ 0.], dtype=float32)
ipdb> factor
array([ 0.], dtype=float32)
ipdb> round_base_decimals
2
```

**Comment by benjello** [comment]
Could you show me the value of round_base_decimals, a and self.rates ?
I did not understand wich operation through a NaN ?

**Comment by cbenz** [comment]
@benjello Sorry it was cut by my copy-paste. I added it above (the value is `2`)

**Comment by benjello** [comment]
@cbenz : still I can't see the lige where NaNs appear.

**Comment by cbenz** [comment]
@benjello Sorry, it's:
```python
thresholds1 = np.outer(factor, np.array(self.thresholds + [np.inf]))
```

**Comment by cbenz** [comment]
I launch it like this:

- install ipdb `pip install ipdb`
- add `import ipdb; ipdb.set_trace()` in `class ags(Variable)` just before `apply_bareme`
- `openfisca-run-test -v **/ags.yaml`

Then `s` to step into a function or `n` to execute the line

**Comment by benjello** [comment]
OK got it. The nans comes from: 
`
0 * np.inf
`
Should transform it to:
`
 np.inf * (0 + np.finfo(np.float).eps)
`
May be by changing 
`
thresholds1 = np.outer(factor + np.finfo(np.float).eps, np.array(self.thresholds + [np.inf]))
`

**Comment by cbenz** [comment]
@benjello Thanks, I'll test it just after. :-)
