### ISSUE TITLE
__version__ not in package attribute

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-core#416]
```python
import openfisca_core
openfisca_core.__version__
```
returns an attribute error. 

- Can you give me an other way to get the package version inside a python shell ?
- Could we make the __version__ work ?

**Comment by fpagnoux** [comment]
You can use:
```py
import pkg_resources

pkg_resources.get_distribution("openfisca_core").version
```

**Comment by adrienpacifico** [comment]
Thank you!

I jiggered with `pip show` to solve my problem, but your solution is far better !

[PEP 396](https://www.python.org/dev/peps/pep-0396/) seems to recommend to have .__version__ attribute to the package.

From my standpoint, my problem is solved.
Thus issue can be either closed or kept opened  (in low priority?) if someone think that it should be implemented one day.
