### ISSUE TITLE
Ensure helpers are agnostic to the manipulated data type

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#434]
Switch and similar helpers should work with scalars (or warns) or otherwise you [may end up in trouble](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py#L658) when you work with more than individual !

@fpagnoux @laem @cbenz 

_— EDIT: I moved the title of this issue in the message body. — @MattiSG_

**Comment by fpagnoux** [comment]
You mean vectors ?

**Comment by benjello** [comment]
Sorry it is [this line](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py#L660). IU think I had a problem here. But I will do more checks.

**Comment by MattiSG** [comment]
Removing the bug label: this is not a bug but bad (or undocumented) API design.

@benjello is this issue still legit, or was it linked to some specific problem you had when writing the code, as you mentioned in the comment above?

**Comment by benjello** [comment]
Do notre remember :-(. Closing for now.
