### ISSUE TITLE
Do not crash when asked for a parameter after end date

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#437]
As someone who use openfisca as a backend of a simulation application,
My application doesn't crash overnight without me having done anything,
Because we just passed the end date of one legislative parameter

----------------

The changes introduced with the fuzzy parameters are a catastrophe for anyone using openfisca in prod. It introduces a major production risk : if we pass the end date of a parameter we use, then the application cannot do any calculation anymore.

The PNDS (institutional re-user) application was down for some time because of this, as well as some of our testing instances.

Openfisca should offer a "production" mode where it is flexible and extrapolates parameters values, and a "strict" mode where it crashed when a value is missing if it is necessary.

**Comment by cbenz** [comment]
Anything to reproduce the bug or do post-mortem?

**Comment by fpagnoux** [comment]
You can try to compute `ppa` or `2017-01` with `openfisca-france#9.0.0`

**Comment by fpagnoux** [comment]
I don't think a post-mortem would bring much, the dynamics inside the team are different now that when this behaviour was introduced. Let's just mention it at the next planification and see how we can fix that.

**Comment by fpagnoux** [comment]
See old discussions in https://github.com/openfisca/openfisca-core/issues/368

**Comment by MattiSG** [comment]
> should offer a "production" mode where it is flexible and extrapolates parameters values, and a "strict" mode

Or just print warnings all the time. Indeed, let's discuss that in the next planning session  :)

**Comment by fpagnoux** [comment]
>Or just print warnings all the time. Indeed, let's discuss that in the next planning session :)

That what I meant by:
>if it is necessary
;)

**Comment by MattiSG** [comment]
The current implementation:
- raises questions from contributors: https://github.com/openfisca/openfisca-france/issues/539
- implies last-minute maintenance: https://github.com/openfisca/openfisca-france/pull/645

**Comment by MattiSG** [comment]
Implement and document the following:

- [ ] Remove the `fuzzy` attribute.
- [ ] Remove the `fin` date attribute.
- [ ] Always extend values towards the future.
- [ ] Add the possibility to state a null value at some start date, to show that a parameter has been removed from law.
- [ ] Introduce the `<PLACEHOLDER>` node type. That type allows signalling an expected value change before the value is actually known. It has no impact on the computation. It has a mandatory attribute `deb="{iso8601-date}"`. It has an optional attribute `href="url"`, which must contain a link to the reference that proves the value of the parameter should change at that date. Its contents are free text, which may contain any textual information useful for retrieval of the value once it is published.
- [ ] Diagnosis that prints all the `<PLACEHOLDER>` at the current date.

**Comment by MattiSG** [comment]
@michelbl can you please confirm that the current `DatedVariable` behaviour is consistent with the one that we're aiming for, i.e. that `DatedVariable` have a start date but no end date? See openfisca/openfisca-france#539 for the raised question.

**Comment by michelbl** [comment]
@MattiSG No, there are plenty of examples : https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prelevements_obligatoires/isf.py#L327
