### ISSUE TITLE
Build reference doc in CI

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#441]
So that it is always up to date with the master of `openfisca-core`

**Comment by fpagnoux** [comment]
I've added `ReadTheDocs` to _Integrations & services_.

- [ ] Check that a build is triggered next time a branch is merge to master.

**Comment by MattiSG** [comment]
@fpagnoux It seems #440 was merged after the integration was set — how can we check if the build was run properly?  :)

**Comment by fpagnoux** [comment]
It's 5:47pm.

There was two merges on master at 3:31pm and 4:07pm, respectively 2:16 and 1:40 ago. 

Recent compilations : 

![image](https://cloud.githubusercontent.com/assets/11834997/22432149/3cae9ca8-e714-11e6-949b-7104f737af5c.png)

I think we are good 😎
