### ISSUE TITLE
Neutralizing a column outside a reform produces an error

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#443]
In other words is it necessary to use `self.refrence` instead of `self` in https://github.com/openfisca/openfisca-core/blob/4ddc0648cfef10c888cc434b284a8e493488d90a/openfisca_core/taxbenefitsystems.py#L201-L202 ?

Some context, I want to hot neutralize a column when filling my simulation with data. It is convenient for memory purposes to neutralize all the column for which I do not have data.

@fpagnoux @cbenz any hint ?

**Comment by MattiSG** [comment]
Please prefer communication means such as Gitter or Slack for general discussions / usage questions if you have access to them  :)

Issues should be used as a way to store actionable items, not ongoing discussions.

As often as possible, the answers should be written straight to the doc / wiki, and the requester used as a reviewer, iterating until the answer is clear to her (cc @fpagnoux @cbenz).

**Comment by benjello** [comment]
OK, let me reword this issue so it is actionnable.

As I user which fills its simulation with survey data I want to be able to neutralize some unused input columns. This is not possible right now. Error happens [here](https://github.com/openfisca/openfisca-core/blob/4ddc0648cfef10c888cc434b284a8e493488d90a/openfisca_core/taxbenefitsystems.py#L201-L202).

@cbenz, @fpagnoux do you thing that using `self` instead of `self.refrence`  in these [two lines](https://github.com/openfisca/openfisca-core/blob/4ddc0648cfef10c888cc434b284a8e493488d90a/openfisca_core/taxbenefitsystems.py#L201-L202
)
using self instead of self.reference in the following lines is OK ?

**Comment by MattiSG** [comment]
👏  :wink:

**Comment by fpagnoux** [comment]
Yep, it is a mistake that a `TaxBenefitSystem` method refers to a reference that is only available for reforms. 
The change you suggest seems right.
