### ISSUE TITLE
Offer a boilerplate tax and benefit system

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#457]
As a new tax and benefit system developer,
I can start from a boilerplate tax and benefit system,
So that I build mine faster

- - - -

**EDIT**: the following is removed.

> To avoid deprecation, this tax and benefit system should be used for tests in CI, must be properly documented, and should be written as cleanly as possible to set an example.
> 
> It should replace `DummyCountry`.

**Comment by fpagnoux** [comment]
I didn't spend a lot of time on it, but here is a quick overview of the difficulities:

- `DummyCountry` is used by many tests in `core`, so violently replacing it would imply to adapt all these tests.
- It is a lot more complex than a boilerplate should be, so we need to split the boilerplate part from the complex part.
- It is written in French

**Comment by MattiSG** [comment]
Redefinition: this issue should **not** include using the boilerplate tax and benefit system as `DummyCountry`. Those two, as well as documentation examples, should all converge to the boilerplate tax and benefit system, but we won't pay all the changes towards that.

However, all future changes to the documentation should be towards externalisation of the code examples to the boilerplate, for example with https://plugins.gitbook.com/plugin/github-embed.

**Comment by MattiSG** [comment]
Regarding maintenance, breaking changes to Core will mean needing to update the boilerplate. This seems doable. In all cases, the boilerplate will make its version dependency to Core explicit.
