### ISSUE TITLE
Document value inference mechanisms

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#458]
There are currently a few places where inferences take place:
- In parameters values, through the `fuzzy` attribute, which artificially extends the validity period of a value — #437.
- In period management, through `calculate_output`, which can automatically sum or divide values over periods to match the requested period.
- In period management, through `set_input`, which can automatically sum or divide input values over periods to match the computable period.
- In some formulas, through `base_function`, which can yield values that the original requested formula could not compute on its own — #460.
- In some formulas, through `max_nb_cycles`, which can block the computation toward the past and thus doesn't allow some values to be computed.

We need to agree on a common, systematic way of doing inferences, to avoid conflicting views such as in #437 or in branch [`extrapolate-intensive-variables-to-past`](https://github.com/openfisca/openfisca-core/commits/extrapolate-intensive-variables-to-past).

The minimal output is a complete list of inferences and expected usage in the documentation, which could be based upon the above list.

The expected output is a set of helper functions, architectural changes and documentation that support a consistent way of inferring values in OpenFisca.

**Comment by MattiSG** [comment]
I'm being told there's also something about “suggestions” — can @cbenz detail the current behaviour, in the same format as above?

Any other known inference behaviours should be listed here. **Please refrain from debating about them for the moment.**

**Comment by benjello** [comment]
There is also the  `nb_cycles` that also implictly  do some time inference.

**Comment by MattiSG** [comment]
From https://github.com/openfisca/openfisca-core/issues/460#issuecomment-283343141:

> `max_nb_cycles` is an implicit inference, since it may block the computation toward the past and thus doesn't allow some values to be computed.

@benjello is this the same as the `nb_cycles` you mentioned above?

**Comment by benjello** [comment]
Yes it is, sorry for not using the right term `max_nb_cycles`

**Comment by MattiSG** [comment]
Ok, it's been about 2 weeks that this reference issue was open. The time for collecting known inferences seems to be over. I updated the original post to include `max_nb_cycles`, and will open a PR in GitBook to document these inferences.
