### ISSUE TITLE
Make explicit input variables temporal inferences

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#460]
## This issue handles a part of #458.

For `base_function`, the issue rose with the formula `rsa`, where macrosimulation (where missing values should be the default ones (or raise warnings, @benjello?) and production (where missing values should be inferred) expected behaviours differ.

Default values in input variables are the source of the issue: if a formula needs values that are undefined (e.g. because they are in previous months from the calculation), it won't crash nor log anything because the input variables return their default values. This inference behaviour seems to be fine for macrosimulation, but production would expect a time-based inference, where the value is copied from its closest defined value rather than a global default one. Changing the inference mode means changing the `base_function`, but that raises conflicts between uses.

There is a consensus between @cbenz @michelbl @fpagnoux that `base_function` is incomprehensible and counterintuitive. It is at least misnamed and it should be more explicit that it is currently used purely as an extrapolation mechanism.

There is also a consensus that defaulting to the simulation period when requesting to compute a formula is not a proper behaviour: this piece of information should be mandatory to avoid incomprehensible behaviour on omission.

### Candidates

- Remove the default period of the input variables: it is currently the period of the simulation, while it could be totally explicit. _**This solution seems to be the preferred one.** For example, it is “well-known” that the revenue tax is defined on the year 2 years ago, not the current one. Documenting the requested definition periods in each formula and forcing the inputs to explicitly state their period could solve the problem._
- Change the default period of the input variables: it is currently the period of the simulation, while it could be “at all times”. _This needs defining “at all times” in Core._

### Eliminated

- Configuration switch to alternate between the two behaviours in the input variables. _This solution does not scale and increases complexity._
- Implement two different formulas, each one implementing one specific behaviour. _Considering that callers would need to define which version to call, that would cascade upwards with each caller formula also having an alternate version, which would end up being the same as having a configuration switch._
- Improve debugging tools to report used inputs. _The produced data would be irrelevant because of the size of the dependency graph, which would make it too hard to identify the pertinent parts._
- Stop providing default values for inputs, which would make computations report errors if they don't define necessary values. _This solution is probably not viable since the dependency graph is quickly huge, and that would mean defining very large amounts of disconnected values in order to achieve the simplest computations. Since there is no point in providing different “default values” sets, there is no point either in a solution where default values would be an opt-in provided by a file, for example._

Suggested action plan
----------------------

- [ ] Remove `base_function`, check how many tests fail and evaluate the amount of work to refactor the inputs.
- [ ] Make it mandatory to specify input variable periods in test cases.
- [ ] Recommend to document input periods in the formula documentation whenever those periods do not match the formula computation period.

**Comment by benjello** [comment]
Some comments:
 - When computing an individual variable, it might be doable to specify sufficient input variables. But when you look at the whole system (decompositions, fiche de paie, even mes-aides as a whole etc) to identify the different pass-through it is very painful to provide sufficient initialized variables. Defaulting to the least harmful default value seems a reasonable choice. But I can understand that one may want to have a mode where errors pop up when a variable is missing, but the user should have the option to choose the first behavior (I just saw that you rejected that option and I do not need it). 
 - I agree on the consensus on `base_function` and defaulting to the simulation period.
 - I greatly suggest that the time-based inference should be provided as an option per variable.
 - A backstop date or period of time might also be implemented. We have some variable whose calculation undergoing infinite loops in the pas (X(t) needs Y(t-1) which in turn needs X(t-2)) that could be halted by requiring that passing a certain date/period the default (or custom default) or the last known value is used (We should get rid of the confusing `max_nb_cycles`).
 - Choosing the input setter should be possible. For example I know that salaire_imposable is a monthly variable but I will provide yearly variable (eventually for some past years), I should be able to config the fact that the value should be divided by 12 (and avoiding multiple periods storing).

I hope this helps and keep on the good work !

**Comment by MattiSG** [comment]
> Choosing the input setter should be possible.

This could be interesting, but is out of the scope of this specific issue on `base_function` and default simulation period.
This is `set_input`, which will be treated in another issue, and enriches #458.

> A backstop date or period of time might also be implemented.

This could be interesting, but is out of the scope of this specific issue on `base_function` and default simulation period.
This is an alternative to `max_nb_cycles`, which is not an inference and thus won't be treated in #458.

> I greatly suggest that the time-based inference should be provided as an option per variable.

Do you have an example of a computing that would be **impossible** to do without such an inference? If not, a case where it would be very cumbersome?
The conclusion of previous discussions seemed to be more that the engine itself should be dumb and leave it to case-specific preprocessing to add the necessary inferred values from the context-specific provided inputs.

**Comment by benjello** [comment]
I disagree on one point: 
  `max_nb_cycles` is an implicit inference, since it may block the computation toward the past and thus doesn't allow some values to be computed.

For your last remark, I think of the obvious `is_permanent` for  `date_naissance` but it seems to be treated by [the proposal](https://github.com/openfisca/openfisca-core/issues/442).

My suggestion was to recognize that the need of extrapolating a value to the past or future without having it permanent may be a good option to replace  
````
base_function = requested_period_last_or_next_value
````

**Comment by MattiSG** [comment]
Very clear, thank you! I updated #458 accordingly  🙂
