### ISSUE TITLE
Distribute OpenFisca through self-contained packages

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#461]
As an ops deploying to a server with no internet connection,
I can deploy self-contained OpenFisca packages,
So that I can offer the OpenFisca API on an internal network

**Comment by MattiSG** [comment]
@pndsagora Can you please confirm this is indeed the reason that led you to create https://github.com/openfisca/openfisca-core/pull/446, https://github.com/openfisca/openfisca-parsers/pull/24, https://github.com/openfisca/openfisca-france/pull/680 and https://github.com/openfisca/openfisca-web-api/pull/89?

Would it be of any use that pre-built packages are directly distributed by OpenFisca? Would it be of use that they are uploaded to some package directory?

**Comment by MattiSG** [comment]
Possible implementations:

1. Debian packages with `rpm`.
2. [Pip install through wheel](https://github.com/openfisca/openfisca-web-api/pull/89#discussion_r100753171).
3. Document the need to [update `setuptools`](https://github.com/openfisca/openfisca-web-api/pull/89#discussion_r100602058).

**Comment by cbenz** [comment]
@MattiSG Debian-like distributions uses `.deb` packages, and RedHat-like distributions use `.rpm` packages. I update the title of the issue.

**Comment by MattiSG** [comment]
@cbenz Thanks! I updated the above.

**Comment by MattiSG** [comment]
Solution 3 [worked](https://github.com/openfisca/openfisca-web-api/pull/89#discussion_r103909945) 🙂

The aim of this issue is thus to at least document the version condition and the process to follow (at most, to distribute those packages ourselves).

**Comment by MattiSG** [comment]
@cbenz do you intend to work on this?

**Comment by cbenz** [comment]
@MattiSG Now that we know that it's [possible](https://github.com/openfisca/openfisca-web-api/pull/89#discussion_r103909945) to use Python Wheels being offline, I don't plan to work on distribution-specific packaging.

**Comment by MattiSG** [comment]
@cbenz 

> The aim of this issue is thus to at least document the version condition and the process to follow (at most, to distribute those packages ourselves).

**Comment by MattiSG** [comment]
@cbenz Isn't this fixed by https://github.com/openfisca/openfisca-gitbook/pull/38? 🤔
