### ISSUE TITLE
Do not hide import errors in `openfisca-run-test`

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#464]
When I try to run `openfisca-run-test` using a country-package I am working on I cannot sort out the ImportError origin between an install/packaging problem from a coding error specific to the country-package.
The [following lines](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/scripts/__init__.py#L30-L33):
````python
    try:
        country_package = importlib.import_module(country_package_name)
    except ImportError:
        handle_error(u'Could not import module `{}`. Make sure it is installed in your environment.'.format(country_package_name))
```` 
catches all the ImportError without showing me the actual error.

@fpagnoux @cbenz what about printing the catched error ?

**Comment by MattiSG** [comment]
Expected result:

```
{{ stack trace }}

Could not import module {}.
Are you sure it is installed in your environment? If so, look at the stack trace above to determine the origin of this error.
See more at <https://github.com/openfisca/country-template#installing>.
```
