### ISSUE TITLE
Cryptic message when attempting to install on Python 3.6

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-core#466]
TLDR: use Python 2 for now; it may be worthwhile upgrading the distributed package to be compatible with 3.

```
docker run -it -v (pwd):/app -w /app -p 8080:8080 python:3.6 /bin/bash
root@d15561ba6f1e:/app# pip install --editable .
Obtaining file:///app
Collecting Babel>=0.9.4 (from OpenFisca-France==13.2.0)
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 108kB/s
Collecting Biryani[datetimeconv]>=0.10.4 (from OpenFisca-France==13.2.0)
  Downloading Biryani-0.10.4.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 5.7MB/s
Collecting numpy>=1.11 (from OpenFisca-France==13.2.0)
  Downloading numpy-1.12.0-cp36-cp36m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 44kB/s
Collecting OpenFisca-Core<6.0,>=5.0.0 (from OpenFisca-France==13.2.0)
  Could not find a version that satisfies the requirement OpenFisca-Core<6.0,>=5.0.0 (from OpenFisca-France==13.2.0) (from versions: 0.5.0, 0.5.1)
No matching distribution found for OpenFisca-Core<6.0,>=5.0.0 (from OpenFisca-France==13.2.0)
```

This is because OpenFisca-Core is listed on PyPI as compatible only with Python 2, and the only version compatible with Python 3 is an old source tarball:

```
root@d15561ba6f1e:/app# pip install OpenFisca-Core
Collecting OpenFisca-Core
  Downloading OpenFisca-Core-0.5.1.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 813kB/s
```

**Comment by fpagnoux** [comment]
Thanks for reporting the issue !

@cbenz : what is the best way to warn the user about the incompatibility with python 3 ? Also, out of curiosity, what does prevent us from upgrading to python 3 ?

**Comment by MattiSG** [comment]
Also, quick fix: unpublish `OpenFisca-Core-0.5.1` from Pypi.

**Comment by cbenz** [comment]
@fpagnoux I don't know how to warn the user. There may be a `python_version` kwarg in `setup.py`, something like that.

@MattiSG Yes, I unpublished the `.tar.gz` of `OpenFisca-Core-0.5.1` but kept the `.whl` which was not the problem. https://pypi.python.org/pypi/OpenFisca-Core/0.5.1

Keep in mind that nothing technical is blocking the switch to Python 3!

**Comment by cbenz** [comment]
I also removed the source `.tar.gz` of `OpenFisca-Core-0.5.0`.

Now:

```sh
pip install --no-cache-dir openfisca-core
Collecting openfisca-core
  Could not find a version that satisfies the requirement openfisca-core (from versions: )
No matching distribution found for openfisca-core
```

**Comment by MattiSG** [comment]
Thanks for the report @Morendil!

Unfortunately, we won't be able to go beyond the message that @cbenz added above. Upon manual testing, it still seems it is more readable for users that the install fails at the beginning of the process rather than in the middle of the process. We will improve the documentation and make sure this is documented in all repos.
