### ISSUE TITLE
Make explicit output variables requested periods

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#468]
To avoid mistakes where the period is not specified and the “simulation period” is used, make it mandatory to specify periods in `calculate` / `compute` calls.

**Comment by MattiSG** [comment]
@benjello do you see any risk / difficulty in doing this?

**Comment by benjello** [comment]
I agree that it is the right thing to do. But it will definitively impact many packages downstream.
But the fix should be easy by using if needed a period at a Scenario (or SurveyScenario) level instead of a simulation level.
