### ISSUE TITLE
Wrong size of vector returned when chaining entities

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#470]
An exemple using openfisca-france will make the problem clearer.
I want to know if the `demandeur` of  `famille` is `DECLARANT_PRINCIPAL`. 
Using:
````
famille.demandeur.has_role(FoyerFiscal.DECLARANT_PRINCIPAL)
````
I get a vector of the size of the individuals (`individu`)present in the simulation instead of the size of the `famille`.

cc @fpagnoux @cbenz

**Comment by fpagnoux** [comment]
Fixed by https://github.com/openfisca/openfisca-core/pull/602
