### ISSUE TITLE
Broken link for contributing guidelines

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#471]
When I open a issue in openfisca-core, I can click on a contributing guideline link which takes me to [another link](https://github.com/openfisca/openfisca-core/blob/master/CONTRIBUTING.md) which ends [nowhere](https://doc.openfisca.fr/en/contribute/guidelines.html)

**Comment by MattiSG** [comment]
Remove `/en` in the URL.

**Comment by MattiSG** [comment]
Check those links in all other repos.

**Comment by fpagnoux** [comment]
All the PRs are merged. Should we close ?

**Comment by MattiSG** [comment]
Checked links in France, Core and Web-API. All good, closing.
