### ISSUE TITLE
Raise nicer errors when legislation is invalid

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#474]
As a formula writer,
I get nice error when my parameter tree is not valid,
So that I can understand the problem quickly and fix it

-------

I may have done an error when writing my XML parameters, but I certainly don't deserve 113 000 characters of this:

```ValueError: OrderedDict([('NODE', {1: OrderedDict([('NODE', {1: OrderedDict([('NODE', {1: OrderedDict([('NODE', {5: OrderedDict([('CODE', {1: OrderedDict([('VALUE', {0: OrderedDict([('valeur', u'Value must be a float')])})])})])})])})])})])})]) for: OrderedDict([('origin', 'ipp'), ('code', 'root'), ('NODE', [OrderedDict([('origin', 'openfisca'), ('code', 'bouclier_fiscal'), ('description', 'Bouclier fiscal'), ('CODE', [OrderedDict([('origin', 'openfisca'), ('code', 'taux'), ('description', "Taux d'imposition maximal"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2007-01-01'), ('fin', u'2010-12-31'), ('valeur', '0.5'), ('tail', u'Suppression du bouclier fiscal \xe0 compter des revenus r\xe9alis\xe9s en 2011.')]), OrderedDict([('deb', u'2006-01-01'), ('fin', u'2006-12-31'), ('valeur', '0.6')])])])])]), OrderedDict([('origin', 'openfisca'), ('code', 'bourses_education'), ('description', u"Bourses de l'\xc9ducation nationale"), ('NODE', [OrderedDict([('origin', 'openfisca'), ('code', 'bourse_college'), ('description', u'Bourse des coll\xe8ges'), ('CODE', [OrderedDict([('origin', 'openfisca'), ('code', 'montant_taux_1'), ('type', u'monetary'), ('description', u'Montant \xe9chelon 1, en multiple de la BMAF'), ('format', u'float'), ('VALUE', [OrderedDict([('deb', u'2009-05-15'), ('valeur', '0.2048')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'montant_taux_2'), ('type', u'monetary'), ('description', u'Montant \xe9chelon 2, en multiple de la BMAF'), ('format', u'float'), ('VALUE', [OrderedDict([('deb', u'2009-05-15'), ('valeur', '0.5673')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'montant_taux_3'), ('type', u'monetary'), ('description', u'Montant \xe9chelon 3, en multiple de la BMAF'), ('format', u'float'), ('VALUE', [OrderedDict([('deb', u'2009-05-15'), ('valeur', '0.8860')])])])]), ('NODE', [OrderedDict([('code', 'avant_2016'), ('CODE', [OrderedDict([('origin', 'openfisca'), ('code', 'coeff_enfant_supplementaire'), ('description', u'Coefficient \xe0 rajouter aux plafonds pour chaque enfant \xe0 charge'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '0.3')]), OrderedDict([('deb', u'2014-01-01'), ('fin', u'2016-06-30'), ('valeur', '0.3')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_taux_1'), ('type', u'monetary'), ('description', u'Plafond de r\xe9f\xe9rence pour le taux 1'), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2015-07-01'), ('fin', u'2016-06-30'), ('valeur', '11288')]), OrderedDict([('deb', u'2014-01-01'), ('fin', u'2015-06-30'), ('valeur', '11252')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_taux_2'), ('type', u'monetary'), ('description', u'Plafond de r\xe9f\xe9rence pour le taux 2'), ('format', u'float'), ('VALUE', [OrderedDict([('deb', u'2015-07-01'), ('fin', u'2016-06-30'), ('valeur', '6102')]), OrderedDict([('deb', u'2014-01-01'), ('fin', u'2015-06-30'), ('valeur', '6083')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_taux_3'), ('type', u'monetary'), ('description', u'Plafond de r\xe9f\xe9rence pour le taux 3'), ('format', u'float'), ('VALUE', [OrderedDict([('deb', u'2015-07-01'), ('fin', u'2016-06-30'), ('valeur', '2153')]), OrderedDict([('deb', u'2014-01-01'), ('fin', u'2015-06-30'), ('valeur', '2146')])])])])]), OrderedDict([('code', 'apres_2016'), ('NODE', [OrderedDict([('code', 'echelon_1'), ('CODE', [OrderedDict([('origin', 'openfisca'), ('code', 'plafond_1e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec un enfant, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '1556.2')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_2e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 2 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '1915.3')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_3e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 3 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '2274.4')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_4e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 4 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '2633.5')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_5e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 5 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '2992.7')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_6e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 6 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '3351.8')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_7e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 7 enfants, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '3710.9')])])]), OrderedDict([('origin', 'openfisca'), ('code', 'plafond_8e'), ('description', u"Plafond de r\xe9f\xe9rence pour l'\xe9chelon 1, pour une famille avec 8 enfants ou plus, en multiple du SMIC horaire brut"), ('format', u'percent'), ('VALUE', [OrderedDict([('deb', u'2016-07-01'), ('valeur', '4070.0')])])])])]), OrderedDict([('code', 'echelon_2'), ('CODE', [OrderedDict([('origin', 'openf```

**Comment by MattiSG** [comment]
@michelbl interested? 😁

**Comment by MattiSG** [comment]
- [ ] Add a DTD.
- [ ] Validate the XML files according to the DTD in the loading pipeline.
- [ ] Validate node types.
- [ ] Validate attributes.
- [ ] Remove all the equivalent byriani.
