### ISSUE TITLE
Deprecate parsers

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#500]
- [x] Remove parsers optional dependency.
- [x] Remove any documentation on the topic.
- [x] Document that the parsers are deprecated and explain why (in the README).
- [x] Update and close obsolete issues in `openfisca-parsers`.

**Comment by cbenz** [comment]
The script [`show_merged_parameters.py`](https://github.com/openfisca/openfisca-france/blob/baremes-ipp/openfisca_france/scripts/parameters/baremes_ipp/show_merged_parameters.py) uses the parsers.

In a discussion with @fpagnoux we proposed to downgrade the feature of the script which relies on the parsers, if it's not a core feature.
