### ISSUE TITLE
Document the preview API using OpenAPI

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#514]
As a developper using the web API, 
I can easily know what output format I should expect

**Comment by MattiSG** [comment]
- [ ] Serve the API documentation from the Legislation Explorer.

**Comment by MattiSG** [comment]
Use http://swagger.io.
Look in http://swagger.io/open-source-integrations/ for possible Flask integrations.
Once the description has been written, use http://swagger.io/swagger-ui/ to consume and visualise the description.

**Comment by Anna-Livia** [comment]
To serve the specification from the flask app, you can try :
Changing :
`app = Flask(__name__)`
into 
`app = Flask(__name__, static_url_path='')`
Adding :
`@app.route('/openFiscaAPI.yml')
def root():
    return app.send_static_file('openFiscaAPI.yml')`
in `app.py`
Adding the `openFiscaAPI.yml`file in a directory called `static`

Display OpenAPI spec with Swagger UI :
I put the swaggerUI files (html, css, js) in a `openAPI_interface`branch  on the `legislation-explorer`repo. To use it, fill in the URL field in the`index.html`file.
