### ISSUE TITLE
Rename “url” to “reference”

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#521]
The `url` attribute is mostly, and should actually be, used for legislative references. Make this usage clearer, as pioneered in the parameter API.

**Comment by michelbl** [comment]
I found that `reference` is already used as an attribute of a Variable in openfisca-france, for only 3 cases:
* https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/plfr2014.py#L22
* https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/plfr2014.py#L39
* https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/inversion_revenus.py#L51

This is not useful as the reference column is already inferred.

I suggest to remove the attribute `reference`, as used to refer to a column.

**Comment by fpagnoux** [comment]
@guillett If I tell you like a variable in OpenFisca, such as `rsa`, has a `reference`, what do spontaneously think this attribute refers to ? Is it ambiguous ? 

If I tell you it refers to a legislative reference, are you surprised or does it make sense ?

**Comment by MattiSG** [comment]
> I suggest to remove the attribute reference, as used to refer to a column.

Agreed. Calling the original version of a variable in a reform “reference” doesn't sound very obvious to me. And I can't find a better alternative to “legislative reference”.

**Comment by MattiSG** [comment]
We have found a consensus on names as discussed in #525 and can proceed with final renames & merging. We should have discussed the naming scheme before implementation.

- `reference` for variable external documentation references.
- `baseline` for tax and benefit system references.
- `baseline_variable` for baseline variable.
- `use_baseline` for the boolean option, that was before this PR reference, triggering the load of the reference tax and benefit system.

Thanks @benjello @fpagnoux @bfabre01 & Twitter followers! 🎊
