### ISSUE TITLE
Log computation errors

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#531]
Log all errors to `stderr`, with the following information:

- Date and time.
- Stack trace.
- Input data and requested computation variables.

A dedicated logging package should be used.

**Comment by davidbgk** [comment]
Two options:

* a [good logger configuration](https://www.python-boilerplate.com/py3+logging/)
* using [Logbook](http://logbook.readthedocs.io/en/stable/)

**Comment by MattiSG** [comment]
- [ ] Replace all `print` by proper logs.
- [ ] Ensure runtime errors in formulas (unknown variable, unknown parameter…) are [great](https://github.com/openfisca/openfisca-core/blob/master/CONTRIBUTING.md#error-messages).
- [ ] Ensure assertion failure message of formula return type is [great](https://github.com/openfisca/openfisca-core/blob/master/CONTRIBUTING.md#error-messages).
- [ ] Ensure entity mismatch error message is [great](https://github.com/openfisca/openfisca-core/blob/master/CONTRIBUTING.md#error-messages).
