### ISSUE TITLE
Faster load/startup in debug/dev/test mode

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#535]
Relates to openfisca/openfisca-france#926

### Here is what I did:

Start the web API with gunicorn and the `reload` flag.

### Here is what I expected to happen:

To reload quickly.

### Here is what actually happened:

It is pretty slow.

#### Details

This week-end I spent some time profiling the web-api startup.

My experience revealed that a lot of time is spent in `get_introspection_data`.

Would it be possible toggle this data retrieval ?

I hacked this and startup time is definitely shorter (set to `False` in `FrenchTaxBenefitSystem` `__init__`) :
https://github.com/guillett/openfisca-core/commit/5e3a11eb762978a7f14e85de970460bf36ae9771

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
Hi @guillett,

Thanks a lot for your work on improving the performance of OpenFisca!

Just to be sure, are-we talking about the "legacy" `openfisca-web-api` or the "preview" API included in `openfisca-core` ? I'm assuming you encountered the issue with the preview one.

Indeed, the reloading is pretty slow. What is surprising is that the reloading is, at least on my computer, much slower that the startup itself 🤔 . Did you observe the same phenomenon ? How long does an API startup for you ? How long does it take to reload it ?

However, I don't think we will consider, at least for now, to add the attribute you're suggesting. The introspection data are used for instance in the [legislation explorer](https://legislation.openfisca.fr/), and we are really careful about not adding too many attributes to tax and benefit systems.

**Comment by guillett** [comment]
Thanks a lot for your reply @fpagnoux.

The slow part is not in the API but in OpenFisca-Core (thought FWIW I am using the legacy API). `get_introspection_data` fetches data from multiples files that's the slow process.

I understand that adding an attribute is annoying and I don't know what is the best way to mitigate that situation but I thought this slow reload/startup should be discussed.

Here is some details:

On my computer, I ran the following script with and without loading introspection data.
```python
# -*- coding: utf-8 -*-

from openfisca_france import CountryTaxBenefitSystem

CountryTaxBenefitSystem()

```



```
(venv-openfisca-france) ➜  openfisca-france git:(hack_fast) ✗ for i in $(seq 10); do time python startup.py; done;
python startup.py  0,76s user 0,17s system 94% cpu 0,993 total
python startup.py  0,76s user 0,17s system 95% cpu 0,976 total
python startup.py  0,78s user 0,16s system 96% cpu 0,970 total
python startup.py  0,75s user 0,17s system 96% cpu 0,943 total
python startup.py  0,76s user 0,16s system 97% cpu 0,945 total
python startup.py  0,77s user 0,17s system 91% cpu 1,028 total
python startup.py  0,76s user 0,16s system 97% cpu 0,956 total
python startup.py  0,75s user 0,16s system 95% cpu 0,951 total
python startup.py  0,75s user 0,16s system 97% cpu 0,940 total
python startup.py  0,76s user 0,17s system 94% cpu 0,975 total
(venv-openfisca-france) ➜  openfisca-france git:(hack_fast) ✗ for i in $(seq 10); do time python startup.py; done;
python startup.py  6,96s user 0,33s system 93% cpu 7,796 total
python startup.py  6,96s user 0,33s system 92% cpu 7,855 total
python startup.py  7,01s user 0,34s system 92% cpu 7,923 total
python startup.py  7,05s user 0,34s system 90% cpu 8,139 total
python startup.py  7,00s user 0,35s system 93% cpu 7,888 total
python startup.py  6,99s user 0,34s system 87% cpu 8,361 total
python startup.py  6,97s user 0,34s system 89% cpu 8,158 total
python startup.py  7,02s user 0,35s system 88% cpu 8,331 total
python startup.py  6,91s user 0,33s system 91% cpu 7,954 total
python startup.py  7,08s user 0,35s system 90% cpu 8,238 total
(venv-openfisca-france) ➜  openfisca-france git:(hack_fast) ✗
```

**Comment by fpagnoux** [comment]
The same takes about 3s on my machine, which is better, but still pretty slow.

In which cases does this startup time becomes a real handicap for your usage ?

**Comment by guillett** [comment]
Hi,

Here are additional data points to highlight the issue.

@fpagnoux, this long startup time prevents Test Driven Development.
IMHO, this is a realy problem for onboarding new contributors, slow feedback loop increase developer frustration.

I ran tests on my machine and on [CircleCI](https://circleci.com/gh/sgmap/openfisca-paris/22).

Reading my previous suggestion, I really think it should be possible to prevent introspection data loading.

Running one failing test in openfisca_paris takes 10s for the user.

```bash
(venv-openfisca-paris) ➜  openfisca-paris git:(taux_effort) for i in $(seq 10); do time openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris; done;
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,36s user 0,37s system 95% cpu 11,225 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,10s user 0,33s system 99% cpu 10,461 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,15s user 0,33s system 99% cpu 10,533 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,09s user 0,33s system 99% cpu 10,482 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,47s user 0,37s system 95% cpu 11,321 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,43s user 0,38s system 97% cpu 11,093 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,56s user 0,37s system 96% cpu 11,273 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,89s user 0,41s system 97% cpu 11,608 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,32s user 0,35s system 97% cpu 10,896 total
openfisca-run-test tests/test_taux_effort.yaml --extensions openfisca_paris  10,31s user 0,36s system 97% cpu 10,995 total
```

On CircleCI it takes 6s

```
user    0m6.059s
user    0m6.100s
user    0m6.110s
user    0m5.790s
user    0m5.963s
user    0m5.942s
user    0m5.892s
user    0m6.095s
user    0m6.087s
user    0m6.207s
```

Running the whole test set (96 tests) in openfisca_paris takes 120s for the user.

```bash
(venv-openfisca-paris) ➜  openfisca-paris git:(taux_effort) for i in $(seq 10); do time openfisca-run-test . --extensions openfisca_paris; done;
openfisca-run-test . --extensions openfisca_paris  128,60s user 0,84s system 96% cpu 2:14,10 total
openfisca-run-test . --extensions openfisca_paris  128,21s user 0,85s system 98% cpu 2:11,24 total
openfisca-run-test . --extensions openfisca_paris  127,43s user 0,84s system 95% cpu 2:14,18 total
```

On CircleCI it takes 150s

```
user    2m32.775s
user    2m31.563s
user    2m32.559s
user    2m32.962s
user    2m38.058s
user    2m36.147s
user    2m38.706s
user    2m35.175s
user    2m36.696s
user    2m37.586s
```

**Comment by guillett** [comment]
Results on [CircleCI](https://circleci.com/gh/sgmap/openfisca-paris/24) with hacked Core (ie. without loading introspection data)


Notable improvement running a single test.

```
user  0m2.622s
user  0m2.591s
user  0m2.680s
user  0m2.506s
user  0m2.596s
user  0m2.617s
user  0m2.554s
user  0m2.610s
user  0m2.517s
user  0m2.572s
```

Benefits on the whole test set is less noticeable because the introspection data loading is done once.

```
user    2m30.220s
user    2m29.348s
user    2m36.319s
user    2m28.659s
user    2m37.500s
user    2m30.885s
user    2m33.556s
user    2m29.040s
user    2m35.349s
user    2m36.281s
```

**Comment by Morendil** [comment]
Closing this as stale and not an effective solution to the stated problem.

It seems to me that `get_introspection_data` is part of the core job of the Web API; we could of course find ways to defer it, or load the data on-demand when a variable is requested, and that is only shuffling the work around; it still needs to be done eventually. At the same time, starting the entire Web API for a TDD cycle working on formulas strikes me as very roundabout.

The code that runs fastest is that which is not executed or even written at all; no matter how much we optimize, when tests have to traverse many layers of implementation before reaching what's being tested, they're always going to be slower than tests which focus on a smaller part of the system and traverse fewer levels of the call stack.

I will gladly consult with any contributor looking to establish an effective TDD loop, and my advice tends to start with "test closer to the code you're modifying". I usually find ways to do that.
