### ISSUE TITLE
Remove scenarios

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#540]
They are poorly named, as they do three things:

1. Input validation through entities consistency checks.
2. Relationships completion between entities.
3. Parse the situation Python instance from an input.

## Consensus

- Refactor by renaming & splitting roles.

## Open questions

1. Should we keep input validation? This is in the law, but is not consistently handled by OpenFisca.
2. Should we replace relationships completion by situation templates?
3. How to support transition for users who rely on scenarios?

**Comment by Morendil** [comment]
One additional things that scenarios did (still do, pending PRs currently in review):
- manage "axes" - these are a feature undocumented (except in [notebooks](https://github.com/openfisca/tutorial/blob/ee8d873889eec7e7d887f9610e6225443e0c4ca0/notebooks/how_to_handle_axes.ipynb)) whereby an input variable can give rise to a set of values increasing by a fixed step

**Comment by sandcha** [comment]
Linked to #691
