### ISSUE TITLE
Add a `/entities` endpoint to the API

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#561]
Returns a JSON object listing all modelled entities where the property names is the `key` property of the entity and where the value is an Object with the following properties:

- String `plural`. Mandatory.
- String `documentation`, coming from the entity docstring. Defaults to `""`.
- Object `roles` if the entity is not a person (in case the entity is a person, `roles` must be falsy), where the name is the `key` property and where the value is an object with the following properties:
  - String `plural`. Mandatory.
  - Boolean `mandatory`. Defaults to `false`.
  - Number `max` (if one is defined).

`subroles` are not to be exposed yet.

Related to https://github.com/openfisca/legislation-explorer/issues/80.

**Comment by fpagnoux** [comment]
For more discussion about subroles: https://github.com/openfisca/openfisca-core/issues/560#issuecomment-390085728
