### ISSUE TITLE
Deprecate support for naming collisions

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#562]
Variables, parameters and entities should always have different names.
OpenFisca Core should now validate there are no naming collisions.
As a first step, such collisions will be detected and a warning will be output, stating that this behaviour is deprecated and that support for it will be removed.

**Comment by benjello** [comment]
At l'East for variables a collision détection exists sincères toi can't add a variable that already exists.

**Comment by benjello** [comment]
I think you already can't add an existing variable, you have to explicitly update it.

**Comment by fpagnoux** [comment]
I think this issue was more saying that a *variable* and an *entity* should not be allowed to have the same name.

Right now, it is already impossible to have two variables with the same name. An error would be raised at the tax and benefit system loading.

**Comment by MattiSG** [comment]
Oh right, thanks for correcting!

**Comment by Morendil** [comment]
Closing as stale (and unclear what the value would be, the status quo on https://github.com/openfisca/openfisca-france/issues/808 showing IMO that this doesn't create much pain).

**Comment by fpagnoux** [comment]
The status quo seems to come from a [lack of consensus](https://github.com/openfisca/openfisca-france/issues/808) than a lack of pain...
