### ISSUE TITLE
Make it easier to use OpenFisca in an hostile environnement

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#574]
By hostile we mean:

- Windows (possibly old versions)
- Limited access to the internet 
- No administrator privilege on the computer

OpenFisca is a software targeted at administrations. We cannot expect our customers to have a proper development environment. 

Efforts have already been made in the past to address this issue:
  - Publish of Windows-compatible wheels on pypi
  - Offer a notebook server _(discontinued, as it costed too much time to maintain it)_
  - Explore the [binder](http://mybinder.org/) solution  (@edarin)

However, the training at the French Senate showed that we still had progress to do.

**Comment by fpagnoux** [comment]
Possibles solutions :

## 1. Offer an OpenFisca virtual machine with an already set development environment.

Main advantage  
  - The environment can be finely set to be fully ready to work in OpenFisca

Main drawbacks:
  - Forces user to work with Linux, what they are usually not used to
  - The users need VirtualBox to be installed on their machine. Without admin rights, this is impossible (maybe we could investigate booting from a USB key ? )
  - Working on a VM is heavy
    - It's slow
    - Needs configuration to be able copy/paste or share folders between host and virtual machines.

**Comment by maukoquiroga** [comment]
**Definiton of done:**

Define the best way to deliver OpenFisca to the crowd in trouble.

Either we give them an OpenFisca Python or an OpenFisca where they could connect and save their work.

**TODO:**

- [ ] Explore docker
- [ ] Explore jupytuhub/lab
- [ ] Explore binder

**Comment by benjello** [comment]
Pour info: @cbenz avait fait tourner un jupyterhub.
Binder déconne parfois.

**Comment by Anna-Livia** [comment]
Merci @benjello :)

**Comment by MattiSG** [comment]
Is this still relevant?

We currently document how to:

- Install OF offline: https://openfisca.org/doc/offline-environment.html
- Install OF with Windows and no admin privileges: https://openfisca.org/doc/windows-no-admin.html
- Use OF without installing: https://openfisca.org/doc/howto-web-no-local-install.html

Seems like we covered all the cases described in this issue 😃 👏 

Voting to close.

**Comment by maukoquiroga** [comment]
@MattiSG We were waiting for openfisca/openfisca-doc#120 to close 😃
