### ISSUE TITLE
Document the new API

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#577]
The doc still references `api-test.openfisca.fr` as the "Preview API", and doesn't reference the swagger. 

- Never mention `api-test.openfisca.fr` in **any** repo.
- Mention `fr.openfisca.org/api/v18/` instead.
- Reference the swagger documentation for the `france`.
- Reference `api.openfisca.fr` as deprecated
- Reference the openfisca-core readme to serve the api
- Mark the openfisca-web-api package as deprecated

**Comment by fpagnoux** [comment]
On the "OpenFisca Web API" page:

-------------------

# Openfisca Web API

## Public France API

The latest version of the France web API is fr.openfisca.org/api/v18/.
Its routes are documented in legislation.openfisca.fr/swagger

##

**Comment by fpagnoux** [comment]
On the 3.1 subsection : 

-------

# Deprecated API

Banner about deprecation : please use the new one !

## Public instance for France

Move the warning and conditions that were on the main page

## Endpoints

 ...

**Comment by fpagnoux** [comment]
On the 3.x subsection :

--------

Describing a situation in OpenFisca

This page should explain how to build a JSON to describe a situation.

The idea is not to repeat what swagger says, but explain the philosophy and insist on the tricky points.

**Comment by Anna-Livia** [comment]
[ ] Never mention api-test.openfisca.fr in any repo.
[ ] Mention fr.openfisca.org/api/v18/ instead.
[ ] Reference the swagger documentation for the france.
[ ] Reference api.openfisca.fr as deprecated
[ ] Reference the openfisca-core readme to serve the api
[ ] Mark the openfisca-web-api package as deprecated
