### ISSUE TITLE
Managing apostrophe symbol in Enum values

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#580]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
I sent `"Locataire ou sous-locataire d‘un logement loué vide non-HLM"` for `statut_occupation_logement` to the previous API and it is working.
I sent it the the new API and it is failing with an Internal Error.

### Here is data (or links to it) that can help you reproduce this issue:

```js
{

    "individus": {
        "demandeur": {}
    },
    "familles": {
        "_": {
            "parents": [
                "demandeur"
            ],
            "enfants": [ ]
        }
    },
    "foyers_fiscaux": {
        "_": {
            "declarants": [
                "demandeur"
            ],
            "personnes_a_charge": [ ]
        }
    },
    "menages": {
        "_": {
            "statut_occupation_logement": {
                "2017-07": "Locataire ou sous-locataire d‘un logement loué vide non-HLM"

            },
            "personne_de_reference": [
                "demandeur"
            ],
            "enfants": [ ]
        }
    }

}
```

`curl -X POST http://localhost:2000/calculate  -H 'Content-Type: application/json' -d @openfisca_request_error.json`

## Context

I identify more as a:

- Magician _(I try to use the new API 🙂)_.

**Comment by guillett** [comment]
Previous API payload and response are available via:

https://mes-aides.gouv.fr/api/situations/545bbc9d71135d04138c34f8/openfisca-request

https://mes-aides.gouv.fr/api/situations/545bbc9d71135d04138c34f8/openfisca-response

**Comment by fpagnoux** [comment]
I @guillett.

Thanks for reporting this issue. It seems that we have an encoding issue on some error messages. We'll publish a fix really soon.

This is the error message you were supposed to get : 

```
{
    "menages": {
        "_": {
            "statut_occupation_logement": {
                "2017-07": "'Locataire ou sous-locataire d‘un logement loué vide non-HLM' is not a valid value for 'statut_occupation_logement'. Possible values are ['Non renseigné', 'Accédant à la propriété', 'Propriétaire (non accédant) du logement', 'Locataire d'un logement HLM', 'Locataire ou sous-locataire d'un logement loué vide non-HLM', 'Locataire ou sous-locataire d'un logement loué meublé ou d'une chambre d'hôtel', 'Logé gratuitement par des parents, des amis ou l'employeur', 'Locataire d'un foyer (résidence universitaire, maison de retraite, foyer de jeune travailleur, résidence sociale...)', 'Sans domicile stable']."
            }
        }
    }
}
```

It seems like you used the wrong kind of apostrophe, so the value you sent doesn't match any the allowed values.

**Comment by fpagnoux** [comment]
For information, we are thinking about redesigning the way we handle enums in OpenFisca to make them more robust (currently it's not, as we've seen here)

**Comment by guillett** [comment]
Thanks a lot @fpagnoux.

You are right, there are two distinct matters here:
1. The encoding issue in the error message
2. The ability to match different kinds of apostrophe.

My 4cts:
1. The error message you posted here is great.
2. As indicated in my original comment, the previous API was able to convert `‘` into `'`. That's why I mentioned https://mes-aides.gouv.fr/api/situations/545bbc9d71135d04138c34f8/openfisca-response. IMHO, it would be a regression (compared to the previous API) to display an error message in that situation.

**Comment by maukoquiroga** [comment]
Hi @guillett ! Do you have the version numbers of both `openfisca-core` and `openfisca-france` where the apostrophes are properly managed ?

I've tried the payload against `openfisca-france` versions `18.11.1`, `19.0.4` and `20.0.0` and it fails for the three of them.

If it is a regression, version numbers would greatly help in bisecting to find the culprit.

**Comment by fpagnoux** [comment]
I think we'll stick to supporting identifiers, as they are more robust :).
