### ISSUE TITLE
Use a safe default port for the API

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#592]
Hi there!

I really enjoy OpenFisca, but here is a remark.

### Here is what I did:
I am trying to upgrade to the new API

### Here is what I expected to happen:

To be able to access the API via the browser on `http://localhost:2000/parameter/cotsoc.gen.smic_h_b`.

### Here is what actually happened:

Firefox (https://developer.mozilla.org/en-US/docs/Mozilla/Mozilla_Port_Blocking) and Chrome (https://superuser.com/questions/188058/which-ports-are-considered-unsafe-on-chrome#188070) block that port.

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by sandcha** [comment]
@maukoquiroga Old api port expected (`2000`), `6000` found but blocked by ports. We suggest `8000` as default new port in order to serve old and new api on same server with default configuration.

**Comment by sandcha** [comment]
Linked to #593

**Comment by maukoquiroga** [comment]
Thanks @sandcha. @guillett does the improved documentation, on what concerns to defining a port, solve the issue you're having? 😃

**Comment by fpagnoux** [comment]
I don't think the initial issue with an unsafe default port has been fixed, re-opening and adding to the next major milestone.
