### ISSUE TITLE
Track Web API version in Piwik stats

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#594]
Relates to openfisca/openfisca-core#685
Requires openfisca/tracker/issues/4

**For** maintainers.

**Story:**

When deploying new API versions,
I want to know the usage metrics for each of the currently supported versions,
so I can provide a better overall experience to our users.

**Motivations:**

- Know which version we're going to keep running
- Know when to notify of sunsetting to our users
- Optimise our server usage, i.e. to avoid memory issues that could block all of our services

**Definition of done:**

- [x] Track API version for each tracked API request, for the versions that support it.
- [x] Group API calls by version

**Details:**

In order to check web API versions usage, we can track the API version in the request url sent to Piwik.

To do so, see `request.url` in the core web api module (`app.py`).

<img width="1048" alt="capture d ecran 2018-07-09 a 22 14 57" src="https://user-images.githubusercontent.com/329236/42474075-bcc0d5f0-83c6-11e8-8822-ce94008b6e65.png">

**Comment by Anna-Livia** [comment]
![Capture d’écran 2018-07-09 à 14.11.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922aa9a25cd102270617380/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b37ff21222410ea3febc405c4145fde78c2db4aa2e30c80351b882294d7ed43819a4bf8b16eb03b827d84a83e4bf8b4cc1ef6f77e283dd5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163562e175327d4e911d7229792a.png)

The use of event allows us to know how many calls per package version are made.
Also to know how many times urls are called in general and per version.
