### ISSUE TITLE
Improve syntax error messages in test files

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#599]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I created an incorrectly formatted test file in YAML.
https://circleci.com/gh/ludwig-test/openfisca-france/2

### Here is what I expected to happen:
I expected to have a nice message 🙂 that highlight the location of my syntax error.

### Here is what actually happened:

```
ValueError: Invalid description of menage: OrderedDict([('loyer', OrderedDict([(Period((u'month', Instant((2017, 12, 1)), 1)), 0.0), (Period((u'month', Instant((2017, 11, 1)), 1)), 0.0), (Period((u'month', Instant((2017, 10, 1)), 1)), 0.0), (Period((u'month', Instant((2017, 9, 1)), 1)), 0.0)])), ('depcom', OrderedDict([(Period((u'month', Instant((2017, 12, 1)), 1)), '55545'), (Period((u'month', Instant((2017, 11, 1)), 1)), '55545'), (Period((u'month', Instant((2017, 10, 1)), 1)), '55545'), (Period((u'month', Instant((2017, 9, 1)), 1)), '55545')])), ('statut_occupation_logement', OrderedDict([(Period((u'month', Instant((2017, 12, 1)), 1)), 8), (Period((u'month', Instant((2017, 11, 1)), 1)), 8), (Period((u'month', Instant((2017, 10, 1)), 1)), 8), (Period((u'month', Instant((2017, 9, 1)), 1)), 8)])), ('personne_de_reference', ['demandeur']), ('enfants', []), ('id', 0)]). Error: Value is not an instance of (<type 'basestring'>, <type 'int'>)
```

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.
(remove this line as well as all items in the list that don't fit your situation)

**Comment by guillett** [comment]
I managed to understand and fix the problem (in the new API `personne_de_reference` and `conjoint` are single item arrays but in a test file they are **not**, they are just an id string.

**Comment by fpagnoux** [comment]
This has been solved by https://github.com/openfisca/openfisca-core/pull/781.
