### ISSUE TITLE
Running Openfisca behind Apache/mod_wsgi

### ISSUE THREAD

**Issue by pndsagora** [openfisca/openfisca-core#607]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I try to run Openfisca behind an Apache/mod_wsgi setup. We recently moved from an old Openfisca version (before openfisca-web-api deprecation) to openfisca-core v21.0.0 and openfisca-france v19.0.1.

### Here is what I expected to happen:

With previous version, we used the following wsgi file and it worked fine with our Apache/mod_wsgi setup

```python
import openfisca_web_api.application
application = openfisca_web_api.application.make_app({"country_package": "openfisca_france", "debug": "false"})
```

### Here is what actually happened:

Due to the openfisca-web-api deprecation, the _openfisca.wsgi_ does not work anymore. Could you please provide us the new entrypoint of the API in the openfisca-core module ?

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by jmdallais** [comment]
Hi ! 
@fpagnoux , @guillett , @benjello , did you see that issue and are you able to provide an answer please ?
Many thanks in advance.
Regards,
JMD

**Comment by schampagnac** [comment]
Hi @Anna-Livia and @sandcha 

I wish you a happy new year.
I want to know if someone of you have an answer to resolve the problem of PNDS ?

Thanks a lot

**Comment by sandcha** [comment]
Hi @schampagnac,

Happy new year 🙂 
We never used it with Apache/mod_wsgi. 
Nevertheless, I would be happy to help. What error message did you get? 

And, did you try to instantiate an `OpenFiscaWebAPIApplication` (aka gunicorn application) as it is done in the [serve script](https://github.com/openfisca/openfisca-core/blob/master/openfisca_web_api_preview/scripts/serve.py#L97)?

**Comment by marchand-laetitia-msa** [comment]
Hi @Anna-Livia,

First of all, thank you for your help.
We tried : 
`from openfisca_web_api_preview.app import create_app
application = openfisca_web_api_preview.app.create_app({"country_package": "openfisca_france", "debug": "true"})
`
then the error is : `ImportError: No module named openfisca_web_api_preview.app`

Do you know if openfisca_web_api_preview is reachable like this : `import openfisca_web_api_preview` instead of 'from openfisca_web_api_preview.app import create_app' ?
 Or if we have to access it from an other entry point?

Best regards

**Comment by guillett** [comment]
Thanks @marchand-laetitia-msa for those additional details.

Could you try the wsgi:
```python
from openfisca_core.scripts import build_tax_benefit_system
from openfisca_web_api_preview.app import create_app

country_package_name = 'openfisca_france'
tax_benefit_system = build_tax_benefit_system(
    country_package_name = country_package_name,
    extensions = None,
    reforms = None
)

application = create_app(tax_benefit_system)
```

It seems to work on my workstation.

**Comment by pndsagora** [comment]
Hello @guillett,

We try with the provided wsgi, but now we have the following error :

```
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72] mod_wsgi (pid=8081): Exception occurred processing WSGI script '/data/soft/ersof82e/agora/deploy/openfisca.wsgi'.
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72] Traceback (most recent call last):
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/ersof82e/agora/deploy/openfisca.wsgi", line 18, in <module>
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     reforms = None
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/openfisca_core/scripts/__init__.py", line 25, in build_tax_benefit_system
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     country_package = importlib.import_module(country_package_name)
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/soft/python2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     __import__(name)
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/openfisca_france/__init__.py", line 3, in <module>
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     from france_taxbenefitsystem import FranceTaxBenefitSystem
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/openfisca_france/france_taxbenefitsystem.py", line 11, in <module>
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     from .model.prelevements_obligatoires.prelevements_sociaux.cotisations_sociales import preprocessing
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py", line 9, in <module>
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     from openfisca_france.model.base import *  # noqa
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/openfisca_france/model/base.py", line 14, in <module>
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     'non_pertinent',
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/enum/__init__.py", line 347, in __call__
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     return cls.__new__(cls, value)
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]   File "/data/soft/packages/lib/python2.7/site-packages/enum/__init__.py", line 662, in __new__
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72]     raise ValueError("%s is not a valid %s" % (value, cls.__name__))
[Mon Jan 08 12:18:20 2018] [error] [client 170.205.250.72] ValueError: ['prive_non_cadre', 'prive_cadre', 'public_titulaire_etat', 'public_titulaire_militaire', 'public_titulaire_territoriale', 'public_titulaire_hospitaliere', 'public_non_titulaire', 'non_pertinent'] is not a valid Enum
```

What could cause this error ?

Best regards

**Comment by guillett** [comment]
OK, thanks.

Can you run `pip list` (make sure you are in the correct environment).

**Comment by pndsagora** [comment]
Here's the _pip list_ output :

```
Babel (2.3.4)
Biryani (0.10.4)
click (2.0)
dpath (1.4.0)
enum34 (1.1.6)
Flask (0.12.2)
Flask-Cors (3.0.2)
functools32 (3.2.3.post2)
gunicorn (19.7.1)
isodate (0.5.4)
itsdangerous (0.24)
Jinja2 (2.10)
jsonschema (2.6.0)
lxml (3.7.1)
MarkupSafe (1.0)
numpy (1.11.1)
OpenFisca-Core (21.0.0)
OpenFisca-France (19.0.1)
Paste (2.0.3)
PasteDeploy (1.5.2)
pip (8.1.2)
Pygments (2.1.3)
pytz (2016.6.1)
PyYAML (3.12)
requests (2.11.1)
setuptools (26.1.1)
six (1.10.0)
Tempita (0.5.2)
WebError (0.13.1)
WebOb (1.6.1)
Werkzeug (0.13)
wheel (0.29.0)
```

**Comment by guillett** [comment]
Great.

You should **not** be using OpenFisca-Core 21.0.0. You probably can downgrade it via `pip install Openfisca-Core==20.0.0`.

You should be using a `requirement.txt` to set up your python environment to easily replicate your production environment.

Let us know how it goes.

**Comment by pndsagora** [comment]
It works better with Openfisca-Core in version 20.

Now we have another problem. Requests take a lot of time, finish in timeout, and we have the following warning in Apache log files : 

```
[error] WARNING:openfisca_core.parameters:libyaml is not installed in your environement. This can make OpenFisca slower to start. Once you have installed libyaml, run 'pip uninstall pyyaml && pip install pyyaml' so that it is used in your Python environement.
```

I tried to uninstall / reinstall pyyaml as suggested, without success.

libyaml is installed : 

```sh
$ rpm -ql libyaml
/usr/lib64/libyaml-0.so.2
/usr/lib64/libyaml-0.so.2.0.4
/usr/share/doc/libyaml-0.1.3
/usr/share/doc/libyaml-0.1.3/LICENSE
/usr/share/doc/libyaml-0.1.3/README
```

**Comment by benjello** [comment]
It is pyyaml that is needed. You can  install with pip as indicated in the warning message.

**Comment by pndsagora** [comment]
I thought pyyaml was already installed, as shown in the _pip list_ output (see this [comment](https://github.com/openfisca/openfisca-core/issues/607#issuecomment-355953389))

Does the case matter ? There's another package pyyaml (lowercase) ?

**Comment by benjello** [comment]
Did you try:
```shell
pip uninstall pyyaml && pip install pyyaml
```

**Comment by guillett** [comment]
That's great if the API is up now.

You should know that the API takes 15/20 seconds on my workstation to be ready.

Can you wait a bit before sending a request (so that you're sure it is ready to handle requests)?
Plus, could you paste a payload here?

**Comment by pndsagora** [comment]
Hello,

@benjello : Yes, I tried to uninstall and reinstall pyyaml, without success.

@guillett : I've waited about 30s before sending the first request.

I use the the following command to test :

```sh
curl -vvv -i "http://[HOST]:[PORT]/openfisca/calculate" -H "Content-Type: application/json" --data-binary "@calculate.json"
```

With this payload :

```json
{
  "familles": {
    "famille_1": {
      "enfants": [
        "Janet"
      ],
      "parents": [
        "Bill",
        "Bob"
      ]
    }
  },
  "foyers_fiscaux": {
    "foyer_fiscal_1": {
      "declarants": [
        "Bill",
        "Bob"
      ],
      "personnes_a_charge": [
        "Janet"
      ]
    }
  },
  "individus": {
    "Bill": {
      "salaire_de_base": {
        "2017": 20000
      }
    },
    "Bob": {
      "salaire_de_base": {
        "2017": 30000
      }
    },
    "Janet": {}
  },
  "menages": {
    "menage_1": {
      "conjoint": [
        "Bob"
      ],
      "enfants": [
        "Janet"
      ],
      "impots_directs": {
        "2017": null
      },
      "personne_de_reference": [
        "Bill"
      ],
      "revenu_disponible": {
        "2017": null
      }
    }
  }
}
```

**Comment by pndsagora** [comment]
@guillett : after several test, it works, I had a timeout problem with the proxy we're using. If I bypass the proxy, it stills a bit slow but it works. I will perform additional tests, I'll let you know.

Could the warning about missing libyaml explains the slow reponse time ?
 
Best regards.

**Comment by pndsagora** [comment]
Our additional tests are successful.

Thanks a lot for your feedback, and thanks everyone for you help.

**Comment by guillett** [comment]
🎉
