### ISSUE TITLE
Remove numpy < 1.13 dependancy

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#613]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

## Context

I identify more as an Economist, Developer and Evangelist and I have encountered many frictions when 
installing openfisca on diverse system.

I think we should target to use the latest stable versions of the main openfisca dependencies (numpy) for mainly two reasons: 
 - the openfisca derivatives dependencies (openfisca-survey-manager relies on pandas, numexpr and tables) relies on numpy and using lod versiosn of numpy can prevent using newer versions with more features. If openfisca doesn't depend on a specific version of numpy the other way around would not be binding
 - We should aim at migrating to Python 3 (Jupyter is switching to Python only and is very convenient to use with openfisca)  and not depending on a specific version of numpy is a good way to start  
 
## Issue

I would like to remove the dependency. If I do that should I care only at tests errors or are they other errors pass undetected. 

see also https://github.com/openfisca/openfisca-core/pull/526
cc @michelbl @fpagnoux

**Comment by benjello** [comment]
@maukoquiroga (I assigned you to get a response ;-))  @Anna-Livia @fpagnoux : this is somehow related to https://github.com/openfisca/openfisca-core/issues/630 since it is about having openfisca usable with the latest version of the important libraries like numpy.

Adding on the reason mentionned in the openning, it is quite annoying to depend on numpy < 1.13 since many standard users who have a python install would not want/have to downgrade their numpy package.

I am willing to help but I don't know how ? Hints are welcomed.

**Comment by michelbl** [comment]
This fix is a bit more complicated, because `assert_near` handles lots of cases (for example, when `value` is a ndarray and `target_value` is a number.

In #613 I propose a quick fix that seems to make things work as expected. However the code of `assert_near` could be refactored to separate the different use cases.

**Comment by fpagnoux** [comment]
Fixed by #635 and https://github.com/openfisca/openfisca-france/pull/956
