### ISSUE TITLE
Allow to run a specific test with nosetests

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#622]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

`nosetests tests/core/test_parameters.py:test_parameter_for_period`
`nosetests tests/core/test_parameters.py`

### Here is what I expected to happen:

To run test(s).

### Here is what actually happened:

```
(venv-openfisca-core) ➜  openfisca-core git:(fix_repr) nosetests tests/core/test_parameters.py:test_parameter_for_period
E
======================================================================
ERROR: Failure: ImportError (No module named test_parameters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/repos/venv-openfisca-core/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/repos/venv-openfisca-core/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/repos/venv-openfisca-core/lib/python2.7/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named test_parameters

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by benjello** [comment]
Je pense qu'il s'agit d'un problème de configuration du paquet.
Les tests qui sont à la racine ne sont pas repérés ... (pas de __init__.py, etc)

**Comment by maukoquiroga** [comment]
@guillett The thing is the `tests` directory is already in your your [`nosetests` working path](https://github.com/openfisca/openfisca-core/blob/5681baf304dd2fcc7aace56b6783d75f7c23f614/setup.cfg#L11).

Try:

      nosetests core/test_parameters.py
      nosetests core/test_parameters.py:test_parameter_for_period
