### ISSUE TITLE
Question: how is input_to_period_tuple supposed to be used ?

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#626]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
```
print periods.Period(periods.input_to_period_tuple("2014-04-01:4")) 
```
### Here is what I expected to happen:
Obtain a period object
```
month:2014-04:4
```
### Here is what actually happened:
```
/home/benjello/openfisca/openfisca-core/openfisca_core/periods.pyc in __str__(self)
    318         """
    319 
--> 320         unit, start_instant, size = self
    321         if unit == ETERNITY:
    322             return 'ETERNITY'

ValueError: need more than 2 values to unpack
```
The error may come from the fact that a period cannot be initialized with 
```periods.input_to_period_tuple("2014-04-01:4")``` 
since it returns 
```
((u'month', (2014, 4), 4), None)
```
Notice the absence of Instant

## Context

I was updating the following [notebook](https://github.com/openfisca/tutorial/blob/master/notebooks/how_to_handle_periods.ipynb) 

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by benjello** [comment]
@Anna-Livia @sandcha @fpagnoux : I am ready fix this myself if you confirm the incorrect behavior

**Comment by Anna-Livia** [comment]
@benjello In the documentation of [input_to_period_tuple](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/periods.py#L870), I see : 
```
>>> input_to_period_tuple(u'2014-3:12')
    ((u'month', (2014, 3), 12), None)
```
Which seems to fit what you get.

Is there something I'm not getting ?

**Comment by benjello** [comment]
it should return:
````
((u'month', Instant(2014, 4), 4), None)
````
to be able to initialize a period.
So I am wondering if this function is unused or used in a way I do not understand.

**Comment by fpagnoux** [comment]
I don't think this function is used anymore.

If you want to build a period from a string, the best way is
`periods.period(u'2014-3:12')`


2018-03-14 6:05 GMT-04:00 Mahdi Ben Jelloul <notifications@github.com>:

**Comment by benjello** [comment]
@fpagnoux : I thought that was the old way of doing since I got an error
````ipython
----> 1 periods.period(u'2014-3:12')
/home/benjello/openfisca/openfisca-core/openfisca_core/periods.pyc in period(value)
    815     unit = components[0]
    816     if unit not in (MONTH, YEAR):
--> 817         raise_error(value)
    818 
    819     # middle component must be a valid iso period

/home/benjello/openfisca/openfisca-core/openfisca_core/periods.pyc in raise_error(value)
    790             u"<http://openfisca.org/doc/periodsinstants.html#api>."
    791             ])
--> 792         raise ValueError(message)
    793 
    794     if value == 'ETERNITY' or value == ETERNITY:

ValueError: Expected a period (eg. '2017', '2017-01', ...); got: '2014-3:12'.
Learn more about legal period formats in OpenFisca:
<http://openfisca.org/doc/periodsinstants.html#api>.
````

**Comment by fpagnoux** [comment]
I don't think '2014-3:12' is a valid period according to the
documentation page <http://openfisca.org/doc/periodsinstants.html#api>
mentioned in the error message. I'd try 'month:2014-03:12' or
'year:2014-03'



2018-03-14 12:15 GMT-04:00 Mahdi Ben Jelloul <notifications@github.com>:

**Comment by benjello** [comment]
Merci je teste asap

**Comment by benjello** [comment]
Merci je teste asap

**Comment by benjello** [comment]
Bien vu @fpagnoux. J'utilisais l'ancienne syntaxe.
Par contre j'ai un truc bizarre:
````
period = periods.Period((u'month', "2014-04-01", 4))
period2 = periods.Period((u'month', periods.Instant((2014, 4, 1)), 4))
print period.unit, period2.unit, period.unit == period2.unit
print period.start, period2.start, period.start == period2.start 
print period.size, period2.size, period.size == period2.size
````
me donne:
````
month month True
2014-04-01 2014-04-01 False
4 4 True
````
Je pense qu'il faudrait que l'on s'assure que le deuxième argument de Period() est un instant ou que l'on convertisse ce dernier en instant.

**Comment by fpagnoux** [comment]
Dans quel cas est-ce que tu es amené à utiliser directement le constructeur `Period` ?

**Comment by benjello** [comment]
C'était juste pour tester

**Comment by benjello** [comment]
C'est bon merci @fpagnoux !
