### ISSUE TITLE
Python 3 Foray 1

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#631]
Related to #630

**Definition of done**

- [x] Make 1 test pass in Python 2.7 and 3.x
- [x] Document learning
- [ ] Merge changes upstream (1 test passing)

**Comment by Anna-Livia** [comment]
### Unicode et Bastring disparaissent et deviennent str
Pour rétro comptabilité, utiliser : 
- `from __future__ import unicode_literals`en haut des fichiers de variablesdes country package
- dans les typecheck :
```py
try  : 
    isinstance(text, unicode) # ou Basetring
except NameError:
    is instrance(text, str)
```

**Comment by fpagnoux** [comment]
If you made some progress on Python 3 compatibility, I'd suggest to merge this evolutions into master.

Otherwise the code will just rot, conflict will appears, and we won't be able to use your work.
