### ISSUE TITLE
Can't load system if two files have the same name

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#642]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Last week, I was in France countryside and I pair-programmed to code a local benefit.

I did not manage to show our product with all the extensions activated because I had an exception when loading the French tax benefit system.

To demo the issue, I created [guillett/test_openfisca_extensions](https://github.com/guillett/test_openfisca_extensions).

I managed to investigate the issue today and I think I found the culprit line.
#### [openfisca_core/taxbenefitsystems.py:152](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/taxbenefitsystems.py#L152)
```python
    def add_variables_from_file(self, file_path):
        """
        Adds all OpenFisca variables contained in a given file to the tax and benefit system.
        """
        try:
            file_name = path.splitext(path.basename(file_path))[0]
            module_name = '{}_{}'.format(id(self), file_name)  # If two tax and benefit systems load the same module, the second one should not replace the first one. Hence this unique module name.
            module_directory = path.dirname(file_path)
            try:
                module = load_module(module_name, *find_module(file_name, [module_directory]))
            except NameError as e:
                logging.error(str(e) + ": if this code used to work, this error might be due to a major change in OpenFisca-Core. Checkout the changelog to learn more: <https://github.com/openfisca/openfisca-core/blob/master/CHANGELOG.md>")
                raise
            potential_variables = [getattr(module, item) for item in dir(module) if not item.startswith('__')]
            for pot_variable in potential_variables:
                # We only want to get the module classes defined in this module (not imported)
                if isclass(pot_variable) and \
                        issubclass(pot_variable, Variable) and \
                        pot_variable.__module__.endswith(module_name): #   <----------- THIS LINE HERE
                    self.add_variable(pot_variable)
        except:
            log.error(u'Unable to load OpenFisca variables from file "{}"'.format(file_path))
raise
```

## `pot_variable.__module__.endswith(module_name)`

If two modules have the same names (ie. two files) that will fail.

I managed to [replicate this issue](https://circleci.com/gh/openfisca/country-template/239) with less complexity (ie. only with the country-template package).

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
Thanks for reporting the issue @guillett !

Will try to have a look at it this week.

**Comment by fpagnoux** [comment]
More likely next week actually, sorry about that.

**Comment by maukoquiroga** [comment]
@fpagnoux you did have a similar issue loading different tax-benefit systems, didn't you? Can't find the commit, though.

**Comment by guillett** [comment]
Thanks everyone!

_Note: I just dumped some of my issues here so that I do not forget them._

**Comment by fpagnoux** [comment]
> @fpagnoux you did have a similar issue loading different tax-benefit systems, didn't you? Can't find the commit, though.

You're probably thinking of `f7475d031f7bd669c16a0acf30bf1e232c2876a4 `. I add a weird issue with loading twice the same tax and benefit system, but it was not exactly the same issue.

**Comment by maukoquiroga** [comment]
> Thanks everyone!
> 
> Note: I just dumped some of my issues here so that I do not forget them.

Please do! There's a high chance your issues aren't only yours. 😄
