### ISSUE TITLE
Fix EnumArray dtype type (should be np.dtype)

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#652]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
````
    month = '2005-01'
    simulation = new_simulation(tax_benefit_system, month)
    var = simulation.calculate('housing_occupancy_status', month)
    print(var.dtype.kind)
````

### Here is what I expected to happen:

No error

### Here is what actually happened:

AttributeError: type object 'numpy.int16' has no attribute 'kind'

## Context

Bug appeared when using [`create_data_frame_by_entity`](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/scenarios.py#L302) with Enum variables.

It is linked to a wrong use of dtype in [EnumArray](https://github.com/openfisca/openfisca-core/blob/e97a3ed33bc3980a8bc27fbe81d17bdeeff9f999/openfisca_core/indexed_enums.py#L59)
wich is numpy type and not of class numpy.dtype, as you can see in the following example:
 ````
print(type(np.dtype(np.int16)))
print(np.dtype(np.int16).kind)
print(type(np.int16))
print(np.int16.kind)
````

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
Thanks for reporting the issue !

Submitted a fix in #654. Can you confirm that this solves your problem ?
