### ISSUE TITLE
Enrich `/variables` to contains related entity name

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#653]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Try to generate an generic UI for OpenFisca.

### Here is what I expected to happen:
To easily know which entity is related to each variable via the web API.

### Here is what actually happened:
One needs to to ping every variable endpoint to know the related variable.
`https://fr.openfisca.org/api/v18/variable/rsa`

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by MattiSG** [comment]
Hi @guillett and thanks for this issue! Could you please elaborate a bit on what you'd like to see here? Which endpoint would you like to be enriched, and with which data? An example of an expected JSON response would be brilliant!  😃

**Comment by MattiSG** [comment]
Have you noticed the `definitions.SituationOutput` node in the `/spec` endpoint? I'm wondering if it might not be exactly what you're looking for 😃

For France, for example:

![screen shot 2018-05-18 at 16 28 00](https://user-images.githubusercontent.com/222463/40216081-760e630c-5ab8-11e8-9276-5df1881d4978.png)

**Comment by guillett** [comment]
Very good point @MattiSG, I actually played, a few hours, with https://mozilla-services.github.io/react-jsonschema-form/ to test an basic version of a generic ui.

However, to me, the entity name is part of the variable definition.

**Comment by fpagnoux** [comment]
> However, to me, the entity name is part of the variable definition.

Not sure I fully understand what you mean by that.

The API spec indeed seems to expose, for each entity, the list of variables that exist for the entity. Is it what you are looking for? If not, what information are missing?

**Comment by fpagnoux** [comment]
Up @guillett

**Comment by fpagnoux** [comment]
Closing the issue as it's inactive. @guillett feel free to reopen if you come up with a clearer idea of what's missing from the web API 🙂 .
