### ISSUE TITLE
Provide a way to dump to/restore fom disk the state of a simulation  

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#661]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I want to do:

I would like to save the state of a simulation  to be able to restart from that exact point several times.
I should thus be able to dump it and reload it.
I think that a good starting point could be the work done by @fpagnoux to allow out-of-memory computations with variables saved on disk.

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

I want to build simulation on huge data and save time at initialisation by always loading the same initial state.
I want to be able to save individual states to run multiple reforms on them.

**Comment by fpagnoux** [comment]
Thanks for opening the issue!

Yep, I can see how that could help for big simulations. I'm adding that to the backlog, and I'll see I find some time to look into it. Can't promise anything though.
