### ISSUE TITLE
Consider Core-provided Web API as stable

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#663]
Since https://github.com/openfisca/openfisca-web-api is considered deprecated (see https://github.com/openfisca/openfisca-doc/pull/140), there is no point in keeping the version number of the current web API at `0.1.0`, nor in naming it “preview” anymore.

**Comment by fpagnoux** [comment]
Where did you see the `0.1.0` version number?

The whole point of the `preview` suffix was to avoid a conflict with the legacy API. Since it's now entirely deprecated, 👍 to rename the package.

**Comment by MattiSG** [comment]
> Where did you see the 0.1.0 version number?

See related commit in work branch: https://github.com/openfisca/openfisca-core/commit/2876bd53289eeea6b6f7f20057e9175b057f7716#diff-23fa28715f5fb76e7d3e6d61bee8a92bL5

**Comment by maukoquiroga** [comment]
So I finally understand why it is called preview!
