### ISSUE TITLE
Obtain web API examples from the provided country package

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#664]
The OpenAPI specification exposed on `/spec` is currently pulling parts of the data it exposes from the loaded country package (such as name, variables list, parameters list…).

However, all usage examples are [hardcoded](https://github.com/openfisca/openfisca-core/blob/3d5084a34cebb9274daa9d45717e0424f39f068e/openfisca_web_api_preview/openAPI.yml#L202-L224), which prevents the examples to work with other country packages than `france` (and will also prevent them from working when the `france` package is updated).

The examples should be dynamically created from the loaded country package.

**Comment by fpagnoux** [comment]
Good point, thanks for reporting the issue. 

Adding that to the backlog, but any PR would be welcome :)

**Comment by fpagnoux** [comment]
Concrete impact of this issues:

In http://nz.openfisca.org/swagger, the "Try it out" on the `/calculate` doesn't work with the provided example:

![image](https://user-images.githubusercontent.com/11834997/45742833-282ca500-bbfb-11e8-9085-82ffc69f5082.png)

**Comment by fpagnoux** [comment]
Result of some investigation and discussion with @sandcha:
- Creating a valid simulation input for an arbitrary country package automatically is not trivial
- Without any additional input from the country package maintainer, such an example is likely to be irrelevant (e.g. calculating the `age` with the `salary` as an input)
- It seems more relevant to let each country package define the relevant simulation inputs to be exposed as examples in the OpenAPi spec. The country template actually [already does it](https://github.com/openfisca/country-template/tree/master/openfisca_country_template/situation_examples).

**Comment by fpagnoux** [comment]
## Proposition

Country package maintainers can define which examples they want to use in their OpenAPI spec the following way: https://github.com/openfisca/country-template/compare/define-openapi-ex

If no example has been defined:
    - An arbitrary parameter is used for the `/parameter` route example
    - An arbitrary variable is used for the `/variable` route example
    - No example is shown for the `/calculate` and `/trace` routes. Instead, a text message such as the following is displayed:

![image](https://user-images.githubusercontent.com/11834997/47042257-cfe4b680-d158-11e8-888b-769524c68a2b.png)

What do you think 🙂 ? @openfisca/aotearoa @openfisca/core-contrib ?
