### ISSUE TITLE
Improve reliability of OpenAPI specification host definition

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#665]
The OpenAPI specification exposed by the Web API currently gets its `host` name from an undocumented `SERVER_NAME` environment variable:

https://github.com/openfisca/openfisca-core/blob/3d5084a34cebb9274daa9d45717e0424f39f068e/openfisca_web_api_preview/loader/spec.py#L19

This variable is for example not provided by hosts such as Heroku, and cannot be guessed by the teams as it is not documented.

This variable should at least be documented.
Preferably, the `host` property should be automatically generated, possibly by mirroring the request's origin.

**Comment by fpagnoux** [comment]
Thanks for reporting the issue!

Moving this issue to the backlog, but any PR would be welcome :).

**Comment by fpagnoux** [comment]
> Preferably, the host property should be automatically generated, possibly by mirroring the request's origin.

One little implementation question @MattiSG: by "mirroring the request's origin", do you mean that:

- _Each time_ a client send a request to the API, we figure out the host URL from the request and include it in the response.
- _When the first request comes in_, we figure out the host URL, store it somewhere, and include it in all later responses.

I was about to go for the 2nd one, but now I'm wondering if there is not some cases where that could backfire
