### ISSUE TITLE
Enable setting variables even if they are not cached

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#676]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I used `holder.set_input`to set a variable (which do have formaulas) to a specific vector of values.
But since this variable was in the `memory_config.variables_to_drop` list, it was never set.
When called by calculate it used the formula or when the formula do not exists it used the default value. 

### Here is what I expected to happen:
I wanted to find back the value I explicitly set.

### Here is what actually happened:

The value was never set.
When called by calculate it used the formula or when the formula do not exists it used the default value. 

## Context

Using openfisca-france with survey data

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
Thanks for reporting the issue!

Indeed, right now, declaring a variable as "to drop" prevent it from being stored, including as an input...

I tried to fix that in branch `allow-set-input-variable-not-cached`, can you have a look and tell me if that fixes the issue? Thanks!
