### ISSUE TITLE
Make parameters node accessible through the Web API

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#678]
In OpenFisca, the structure of parameters is a tree. For instance:
- `prestations.minima_sociaux.rsa.montant_de_base_du_rsa` is a leaf that represents a concrete parameter of the legislation
- `prestations.minima_sociaux.rsa` is a node that represents a structured group of parameters of the legislation

Today, in the Web API, I can access two things: 
- A [leaf](https://fr.openfisca.org/api/v21/parameter/prestations.minima_sociaux.rsa.montant_de_base_du_rsa).
- The [flattened list of all leafs](https://fr.openfisca.org/api/v21/parameters).

I'm trying to represent, in a web view, a node of the legislation parameters.
But there is no way for me to directly access a node of the parameters.
The best I can do is parse the list of leafs to reconstruct the graph, but this seems silly and tedious, and it doesn't allow me to access the metadata associated with a node (description).

-------

As a client of the API building a front displaying the parameters,
I'd like to be able to access a node through the Web API,
So that I can build a view of this node that include its metadata

**Comment by fpagnoux** [comment]
Implementation suggestion:

Route: `/parameter/prestations.minima_sociaux.rsa.majoration_parent_isole`:

## Suggestion 1 (flat)

```JSON
{
	"id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
	"description": "Majoration du RSA pour parent isolé",
	"femmes_enceintes": {
		"description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
		"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
		"values": {
			"1997-01-01": 0.0,
			"2009-06-01": 1.284,
			"2009-06-20": 1.28412
		}
	},
	"par_enfant_a_charge": {
		"description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
		"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
		"values": {
			"1997-01-01": 0.0,
			"2009-06-01": 0.428,
			"2009-06-20": 0.42804
		}
	},
	"duree_du_droit": {
		"description": null,
		"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
		"values": {
			"2009-06-01": 12.0
		}
	}
}
```

## Suggestion 2 (`children` key)

```JSON
{
	"id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
	"description": "Majoration du RSA pour parent isolé",
	"children": {
		"femmes_enceintes": {
			"description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
			"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
			"values": {
				"1997-01-01": 0.0,
				"2009-06-01": 1.284,
				"2009-06-20": 1.28412
			}
		},
		"par_enfant_a_charge": {
			"description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
			"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
			"values": {
				"1997-01-01": 0.0,
				"2009-06-01": 0.428,
				"2009-06-20": 0.42804
			}
		},
		"duree_du_droit": {
			"description": null,
			"id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
			"values": {
				"2009-06-01": 12.0
			}
		}
	}
}
```

**Comment by MattiSG** [comment]
This is just screaming for proper namespacing support. Replace the `.` in the parameters names by a `/` and it all makes sense.

While slightly less elegant, `children` is definitely the way to go, otherwise preventing metadata and sub-nodes names conflicts will mean having many forbidden names and will bring backward compatibility headaches for situations where we expand metadata support, such as in #677.

I am not sure about exposing the values themselves, though. Metadata is linear in growth. Including data itself means all parents of a large leaf will be a huge resource drain, and this is not even stable in time.

**Comment by fpagnoux** [comment]
> Replace the `.` in the parameters names by a `/` and it all makes sense.

I agree on principle, but if we do it for the nodes, we should also do it for the leafs, and that would be a breaking change for the web API. Not sure I want to treat that  in this issue.

> While slightly less elegant, children is definitely the way to go, otherwise preventing metadata and sub-nodes names conflicts will mean having many forbidden names and will bring backward compatibility headaches for situations where we expand metadata support, such as in #677.

👌. However, we'll have conflicts anyway in parameters definition: when I define a parameter node in a YAML file, both children and metadata are mixed 😈...

> I am not sure about exposing the values themselves, though. Metadata is linear in growth. Including data itself means all parents of a large leaf will be a huge resource drain, and this is not even stable in time.

Good point.

New proposition:

### Suggestion 2

```JSON
{
  "id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
  "description": "Majoration du RSA pour parent isolé",
  "children": {
    "femmes_enceintes": {
      "description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
    },
    "par_enfant_a_charge": {
      "description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
    },
    "duree_du_droit": {
      "description": null,
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
      }
    }
  }
}
```

**Comment by MattiSG** [comment]
> if we do it for the nodes, we should also do it for the leafs, and that would be a breaking change for the web API

Not necessarily 🙂
We can introduce support for `/` syntax as `v1.1.0`, deprecate support for `.`, but not remove it yet.
I believe namespacing for variables and parameters (or something that looks like it) is the next big thing for naming anyway (see #668).

> we'll have conflicts anyway in parameters definition

Is this still the case with #681?

> Suggestion 3

Reads quite well.
However, when I try to think of a way to navigate this object, I feel it will be strange in the client to use `majoration_parent_isole.children['femmes_enceintes']`. While `children` describes things well technically, it is not very clear and can easily conflict (conceptually) with domain names.

Here are a couple (none brilliant) ideas for the property name:

1. `children`
2. `_`
3. `_children`
4. `subparams`
5. `subparameters`

Also, what happens for a leaf node? Does it have an empty `children` property? I feel like it shouldn't have any.

**Comment by fpagnoux** [comment]
> Is this still the case with #681?

Yep, #681 parses more metadata but doesn't change the expected structure of the YAML files. But once we agree on the `children` key we could transpose the change in parameter declaration.

 I like the shortness of `_`, even though the meaning may not be transparent.
`subparams` would also acceptable to be, though abbreviations are not great. 

`_children` doesn't seem much better than `children`, and `subparameters ` is heavy.

Anyone else has an opinion? @benjello @Anna-Livia @sandcha?

**Comment by fpagnoux** [comment]
> Also, what happens for a leaf node? Does it have an empty children property? I feel like it shouldn't have any.

Leaf node would not have a `children` property, the same way a node that's not a leaf would not have a `values` property.

**Comment by benjello** [comment]
Not enough competent to provide a useful input here

**Comment by Anna-Livia** [comment]
I  like suggestion 3.
- For the name of the attribute that list the available nodes, how about `links`
- Would it be helpful to incorporate a `node_type` attribute to each child to know it it is a `node`or a `leaf`?

**Comment by fpagnoux** [comment]
> For the name of the attribute that list the available nodes, how about links

`links` really makes me think of an hypertext link, not sure it's semantically carrying the idea of "sub-parameters".

> Would it be helpful to incorporate a node_type attribute to each child to know it it is a node or a leaf?

I think we had the discussion when designing the first routes of the Web API (to distinguish scales from simple params), and concluded that it was a little redundant with the presence of the `values`/`brackets` property.

**Comment by maukoquiroga** [comment]
> `links` really makes me think of an hypertext link, not sure it's semantically carrying the idea of "sub-parameters".

I was actually thinking on #512 for this 😄: if sub-parameters are consumable independently, based on suggestion 3, using `relationship` instead of `children`, that could look like :

```json
{
  "data": [{
    "type": "parameter",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
    "attributes": {
      "title": "majoration_parent_isole",
      "description": "Majoration du RSA pour parent isolé"
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole"
    },
    "relationships": {
      "parameters": {
        "links": {
          "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole/parameters",
          "related": "https://api-test.openfisca.fr/parameters"
        },
        "data": [
          { "type": "parameters", "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes" },
          { "type": "parameters", "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge" },
          { "type": "parameters", "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit" }
        ]
      }
    }
  }],
  "included": [{
    "type": "parameters",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
    "attributes": {
      "title": "femmes_enceintes",
      "description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
      "values": {
        "1997-01-01": 0.0,
        "2009-06-01": 1.284,
        "2009-06-20": 1.28412
      }
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole/parameters/femmes_enceintes",
      "related": "https://api-test.openfisca.fr/parameters/femmes_enceintes"
    }
  }, {
    "type": "parameters",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
    "attributes": {
      "title": "par_enfant_a_charge",
      "description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
      "values": {
        "1997-01-01": 0.0,
        "2009-06-01": 0.428,
        "2009-06-20": 0.42804
      }
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole/parameters/par_enfant_a_charge",
      "related": "https://api-test.openfisca.fr/parameters/par_enfant_a_charge"
    }
  }, {
    "type": "parameters",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
    "attributes": {
      "title": "duree_du_droit",
      "description": null,
      "values": {
        "2009-06-01": 12.0
      }
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole/parameters/duree_du_droit",
      "related": "https://api-test.openfisca.fr/parameters/duree_du_droit"
    }
  }]
}
```

Although that's too verbose ! Without all the `links`, but keeping `relationships` :

```json
{
  "data": {
    "type": "parameter",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
    "attributes": {
      "title": "majoration_parent_isole",
      "description": "Majoration du RSA pour parent isolé"
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole",
      "related": "https://api-test.openfisca.fr/parameters"
    },
    "relationships": {
      "parameters": [{
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
        "attributes": {
          "title": "femmes_enceintes",
          "description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
          "values": {
            "1997-01-01": 0.0,
            "2009-06-01": 1.284,
            "2009-06-20": 1.28412
          }
        }
      }, {
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
        "attributes": {
          "title": "par_enfant_a_charge",
          "description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
          "values": {
            "1997-01-01": 0.0,
            "2009-06-01": 0.428,
            "2009-06-20": 0.42804
          }
        }
      }, {
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
        "attributes": {
          "title": "duree_du_droit",
          "description": null,
          "values": {
            "2009-06-01": 12.0
          }
        }
      }]
    }
  }
}
```

**Comment by fpagnoux** [comment]
If I remove the values, that gives us:

```JSON
{
  "data": {
    "type": "parameter",
    "id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
    "attributes": {
      "title": "majoration_parent_isole",
      "description": "Majoration du RSA pour parent isolé"
    },
    "links": {
      "self": "https://api-test.openfisca.fr/parameters/prestations/minima_sociaux/rsa/majoration_parent_isole",
      "related": "https://api-test.openfisca.fr/parameters"
    },
    "relationships": {
      "parameters": [{
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
        "attributes": {
          "title": "femmes_enceintes",
          "description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
        }
      }, {
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
        "attributes": {
          "title": "par_enfant_a_charge",
          "description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
        }
      }, {
        "type": "parameters",
        "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
        "attributes": {
          "title": "duree_du_droit",
          "description": null,
        }
      }]
    }
  }
}
```

which I find significantly heavier than "Suggestion 3"

**Comment by fpagnoux** [comment]
I'd like to move forward towards opening the PR. I'm planning to go with suggestion 3, which seems popular. But we still need to make up our mind about this keyword.

The 3 solutions I'd find acceptable are:

1. `_`
2. `children`
3. `subparams`

Among these 3, which one do you prefer?

@MattiSG @maukoquiroga @Anna-Livia ?

**Comment by maukoquiroga** [comment]
@fpagnoux Yeah adding all the links adds a lot of overhead indeed. Suggestion 3 is actually cool. Regarding the keywords, I'd say in order of préférence :

1. `subparams`
2. `children`
3. `_`

---

Last proposition: sticking to suggestion 3, just adding the `rel` object:

```json
{
  "id": "prestations.minima_sociaux.rsa.majoration_parent_isole",
  "description": "Majoration du RSA pour parent isolé",
  "rel": {
    "femmes_enceintes": {
      "description": "Taux de la majoration du RSA socle pour une femme enceinte sans enfant (en pourcentage du rsa de base pour un célibataire sans personne à charge)",
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.femmes_enceintes",
    },
    "par_enfant_a_charge": {
      "description": "Majoration du RSA socle par enfant supplémentaire (en pourcentage du rsa de base)",
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.par_enfant_a_charge",
    },
    "duree_du_droit": {
      "description": null,
      "id": "prestations.minima_sociaux.rsa.majoration_parent_isole.duree_du_droit",
      }
    }
  }
}
```

**Comment by MattiSG** [comment]
My order of preference is:

1. `subparams`
2. `children`
3. `rel`
4. `_`
