### ISSUE TITLE
Track metadata in Piwik

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#683]
Relates to openfisca/openfisca-core#685
Requires openfisca/tracker/issues/4

**For** maintainers.

**Story:**

When deploying new API versions,
I want to know the detailed usage metrics for each of the currently supported versions,
so I can provide a better overall experience to our users.

**Definition of done:**

In order to have a better view of the API's usage, track :

- [ ] ~Core version~
- [x] Country package name
- [x] Country package version

**Comment by MattiSG** [comment]
Looks like a duplicate of https://github.com/openfisca/openfisca-core/issues/683.

Closing this for now, feel free to reopen if I misqualified 🙂

**Comment by fpagnoux** [comment]
I think we already have the name and country package version:

![image](https://user-images.githubusercontent.com/11834997/44536684-01964f80-a6cb-11e8-9026-38d0b03effb7.png)

I'm however not sure what the core version would bring. @maukoquiroga in which case would this piece of information help you?

**Comment by maukoquiroga** [comment]
Hi @fpagnoux, effectively the current information available is enough. I've updated description.
