### ISSUE TITLE
API visits not properly tracked in Piwik

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#684]
Relates to openfisca/openfisca-core#685

Currently, API visits are not properly tracked in Piwik.

We should ensure that we track/group:

- by domain name => `https://fr.openfisca.org`, and
- by path => `/api/v21`

<img width="1039" alt="capture d ecran 2018-07-09 a 22 18 34" src="https://user-images.githubusercontent.com/329236/42473904-2ef9bc78-83c6-11e8-956e-3d26110eb2e8.png">

**Comment by MattiSG** [comment]
I don't understand what you would like your stats to look like. Are you sure your instance is properly set up and that the problem does lie with the Tracker itself? 🙂

In any case, this issue should be moved to [`openfisca/tracker`](https://github.com/openfisca/tracker), not in Core. I'm closing this here, feel free to reopen in https://github.com/openfisca/tracker, possibly describing what you would like your stats to look like! 🙂
