### ISSUE TITLE
Redirect /parameter/path.to.param to parameter/path/to/param

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#695]
Depends on #694 

The `/parameter/path.to.param` route is  deprecated. Use a `301` to redirect it to the proper new route `parameter/path/to/param`

This is a breaking change, as clients which do not follow redirects may break if using the old path.

**Comment by Morendil** [comment]
At the moment both forms are working, and it seems to me like this is just fine. We need only three lines of code to try both routes, and redirecting would likely not save any implementation complexity. In sum, I don't see much value in this issue, recommend closing. Any objections?
