### ISSUE TITLE
Automatically check that new files import `unicode_literals`

### ISSUE THREAD

**Issue by magopian** [openfisca/openfisca-core#707]
Following #702, it became apparent that the `from __future__ import unicode_literals` was needed in all the python modules, until the backward compatibility with python 2 is dropped.

One proposition is to just be very cautious during reviews whenever a new module is created, for an additional 5 months until the backward compatibility is dropped.

The other one is to implement (or find and use?) a script that would be run on each CI build, and maybe in a git pre-commit hook.

I haven't found any existing script that would do that, but the [modulefinder](https://docs.python.org/3/library/modulefinder.html) could be used to come up with something quick and probably dirty.
Another option would be to investigate [findimports](https://pypi.org/project/findimports/).

**Comment by Morendil** [comment]
With 6 weeks to go until we drop Python 2 support, this doesn't seem worth investing in. Closing.
