### ISSUE TITLE
Create a method `asof` that returns the state of the tax benefit system at that date 

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#720]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

I would like to extract a tax benefit system _as of_ some specific date potentially to use in the future _as is_  time never changed anything for that specific date.

The steps that should do the job are:
 - [ ] erase all parameters after some date
 - [ ] erase all the formulas after some date for all the variables

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.
- Historian _(I accumulate data based on past legislation values)_.
- Lobbyist _(I model reforms to make them exist)_.

@fpagnoux do you see other things that may cause problems ?

cc @claireleroy @bfabre01

**Comment by benjello** [comment]
I implemented it as a standalone function in [another package](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/utils.py#L156).

@openfisca/core-contributors : 
 - do you think that this tool and the inflator mentionned in this [france issue](https://github.com/openfisca/openfisca-france/issues/1095) should make it to core ?
 - if so could you have a quick look at the code and tell me what I should take care of when moving it to core as a new tax_benefit_system method

**Comment by benjello** [comment]
@openfisca/core-contrib  @Morendil @sandcha @fpagnoux @maukoquiroga : I almost finished a couple of tax-benefit system and parameters methods that are implemented as independent functions in survey-manager:
 - [`asof`](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/utils.py#L127) which freeze the tax-benefit-system as of some date
 -  [`inflate_parameters`](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/utils.py#L18) that modify all the parameters starting from some date by in inflator value provided by the user.

[Tests](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/tests/test_legislation_inflator.py) are here so you can grasp what these functions actually do.
  
I think the best place for this are methods for Parameters and TaxBenefitSystem objects and thus belong to. What is your opinion ?

**Comment by benjello** [comment]
@Morendil @sandcha @fpagnoux: any advice ?I really want to do that but not in vain (PR not accepted as out of scope) ;-)

**Comment by benjello** [comment]
@maukoquiroga @Morendil @sandcha : time to iterate on this subject. Are you opposed to have it in core ?

**Comment by Morendil** [comment]
@benjello Sorry we didn't give you a reply earlier. Can we hold off a bit longer on a decision? We're not sure what our budget till the end of the year looks like and as a result our policy on new contributions tends to be strongly conservative at the moment. There should be news this week.

**Comment by benjello** [comment]
@Morendil no hurry on our side but I just ping you because it may help leximpact 

cc @magemax

**Comment by benjello** [comment]
@Morendil any update on this ?

**Comment by maukoquiroga** [comment]
@benjello How do you currently solve this problem?

**Comment by benjello** [comment]
@maukoquiroga look at the links  in my january post

**Comment by maukoquiroga** [comment]
Hey @benjello, thanks for your prompt answer.

In addition to @Morendil's remark, it seems your current solution works just fine, and that you manage to maintain it in a way that it fulfils your needs.

The @openfisca/france-contrib-dinsic teams is engaged in the improvement and maintenance of OpenFisca-Core's code base so it maximises all of it user base's satisfaction.

When introducing a new feature, we sign a symbolic contract with the community to maintain that feature in the long term. As we have a fixed amount of workforce to do so, each new feature means that a) we need to drop another one, b) we have to degrade the overall value provided to the community, or c) we have to increase the units of workforce available at any given time to maintain this package.

As including this feature into OpenFisca-Core's code base a) won't add any value to you, and b) it would decrease the overall value provided to the community, I think the wiser option is to hold on this for now.

I'm closing the issue, please do not hesitate to reopen if you think we should explore this further.
