### ISSUE TITLE
Set max and min amount of person with a given role in entities specification

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/openfisca-core#721]
> Rewritten by @fpagnoux

As a country package maintainer, I'd like to be able to specify, for each role of an entity:
- How many people can have this role? 
- If this role is mandatory

------

Currently, [I can specify a `max`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/entities.py#L71) but it doesn't work well: if I send to many people with this role, I get a very non-explicit error:

```
    yield role.subroles[legacy_role_j], legacy_role_i + legacy_role_j, individu
IndexError: list index out of range
```

There is no way right now to specify that a role is mandatory.

-----

Suggestion:

- Properly enforce the `max` of a role, and send a nice error message when a user tries to send more
- Introduce a `min` properties of role, and handle it the same way

(I have a slight preference for `min` over `mandatory` as it's more consistent with `max` and a little more versatile, but up to debate)

**Comment by Morendil** [comment]
Closing this as #782 is the same issue but the discussion has much more detail.
