### ISSUE TITLE
Add ability to specify the baseline in the yaml test files

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#724]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I want to do:

I would like to be able to use YAML test an extension package who comes on the top of a baseline tax benefit system.  I need to be able to specify the baseline model in the YAML test file.

## Context

I use [openfisca-ceq](https://github.com/openfisca/openfisca-ceq) as a boilerplate on the top of which I will insert Senegal, Mali and Cote d'Ivoire system as reforms of the boilerplate. 
I want to test those (reforms/extensions) in the country-package.
 

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.

**Comment by benjello** [comment]
@sandcha @maukoquiroga : shouldn't be that hard to implement ?

**Comment by Morendil** [comment]
The intent of reforms, according to the documentation, is to "evaluate the quantitative impact of legislation changes". Your intent is to provide a model for a specific, real country - while abstracting commonalities. The documentation states "use an extension if you want to write formulas that are based on a main tax and benefit system". Why would you prefer a reform over an extension in this case?

**Comment by benjello** [comment]
@Morendil : I use reforms/extensions equivalently. For me there are conceptually the same object.

**Comment by fpagnoux** [comment]
I'm not 100% sure I understand the feature request. 

If I run:

```sh
openfisca-run-tests --country-package  openfisca_ceq --reforms some_reform test_file.yaml
```

tests will be run against the `openfisca_ceq` baseline with the `some.reform` reform (see [doc](https://openfisca.readthedocs.io/en/latest/openfisca-run-test.html#reforms)). So the `-c` parameter is specifying the baseline.

What would you like to be done differently? Would you like to be able to omit the `-c` argument, and instead put the information in the YAML test?

**Comment by benjello** [comment]
Thanks @fpagnoux for the info.
I want to be able to specify the reform in the YAML test file so I can run openfisca-run-tests on a whole directory without using the `--reforms` option.

**Comment by fpagnoux** [comment]
Something like [that](https://github.com/openfisca/openfisca-france/blob/master/tests/allegement_fillon.yaml#L3) ?

We are already doing that on France. However, I don't think we are caching the reformed tax benefit systems right now, so if you notice performances issues, let us know!

**Comment by benjello** [comment]
Ok I will try that. Closing for now.
