### ISSUE TITLE
Shut down Python 2.7 releasing & code adaptations

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#730]
Imported from #693 cc @fpagnoux 

---

Everything seems ready, we just need to wait for January 1st to:

- [x] Shut down Python 2.7 releasing
- [x] Remove backward compatibility code 
     - [x] Remove all `from __future__`, `from builtins` and `from future` imports
     - [x] Remove OrderedDicts used to mimic Python 3 behavior
     - [x] Remove other adaptations

**Comment by benjello** [comment]
IPP is ready to move on toward total deprecation of Python 2.7.

**Comment by Br3nda** [comment]
There's some 2.7 references still in the country-template

**Comment by maukoquiroga** [comment]
I contributed with #828

**Comment by Morendil** [comment]
OrderedDict is gone from Core as of today.
