### ISSUE TITLE
Separate unit and integration tests

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#731]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I took a look at `test_holders.py`.

### Here is what I expected to happen:

To find something like:

```python
def test_set_input_enum_string():
    variable = tax_benefit_system.get_variable('housing_occupancy_status')
    entity = get_simulation(couple).get_variable_entity('housing_occupancy_status')
    storage = MockStorage()
    holder = Holder(variable, entity, storage)
    period = make_period('2017-12')
    holder.set_input(period, np.asarray(['free_lodger']))
    assert_equal(storage.get(period), HousingOccupancyStatus.free_lodger)
```

Which is more like unit testing.

### Here is what actually happened:

I found this:

```python
def test_set_input_enum_string():
    simulation = get_simulation(couple)
    status_occupancy = np.asarray(['free_lodger'])
    simulation.household.get_holder('housing_occupancy_status').set_input(period, status_occupancy)
    result = simulation.calculate('housing_occupancy_status', period)
    assert_equal(result, HousingOccupancyStatus.free_lodger)
```

Which is more like integration testing.

## Context

I identify more as a:

- Developer

**Comment by fpagnoux** [comment]
I'm not sure this deserves to be an issue. 

We can opportunistically refactor tests to reach this goal while we work on something, but I doubt we'll ever _specifically_ work on refactoring tests.

Closing.
