### ISSUE TITLE
Run testdocs

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#733]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I modified `setup.cfg` to run doctests:

```
[nosetests]
where        = .
exe          = true
with-doctest = true
```

### Here is what I expected to happen:

```
OK
```

### Here is what actually happened:

```
FAILED (errors=10, failures=38)
make: *** [test] Error 1
```

## Context

I identify more as a:

- Developer

**Comment by Morendil** [comment]
Per discussions on #806, this is not actionable as most of our doctests assume some context (fixtures, and so on) which is in fact not present.

**Comment by benjello** [comment]
Does that means that we forgot about having working doctests ?

**Comment by Morendil** [comment]
@benjello Yes, I think so :(
