### ISSUE TITLE
Improve input deleting arrays in Python

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#740]
What I have to do:

````
simulation = ...
holder = simulation.persons.get_holder('salary')
holder.delete_arrays('2018-08')
````

What I'd prefer:

````
simulation = ...
simulation.delete_arrays('salary', '2018-08')
````
What do you folks think?

**Comment by Morendil** [comment]
What's your use case for delete_arrays ? It seems to be used very sparingly at the moment (and that strikes me as a good idea).

**Comment by benjello** [comment]
When I initialise simulation with survey data, I may want to inject some data in, for example, previous years etc after having done some calculation. It is somehow like a hot initialisation.
And to be sure of what I am injecting I may want to delete all the arrays related with some variable at some period in time. 

Also used with inflators https://github.com/openfisca/openfisca-survey-manager/blob/781c1f1f434c54186c8e8597a7626c6621af4152/openfisca_survey_manager/scenarios.py#L555

**Comment by maukoquiroga** [comment]
See #725 also.

**Comment by Morendil** [comment]
Thanks @benjello !

The implementation seems straightforward - you have it in the original comment, first Python snippet. The unit test already exists in `tests/core/test_holders.py` - it only needs to be extended to calling at the simulation level.

Will you go ahead and propose a PR?

**Comment by benjello** [comment]
I was not planning to do it. But I can. I am just a bit underwater as usual right now.
Leave me a week or so than ping me back if nothing happens ;-)
