### ISSUE TITLE
Allow openfisca-run-test to get test from STDIN

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#754]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
`cat tmp.yaml | openfisca-run-test`

### Here is what I expected to happen:
The same as
`openfisca-run-test tmp.yaml`

### Here is what actually happened:
```
usage: openfisca-run-test [-h] [-c COUNTRY_PACKAGE]
                          [-e [EXTENSIONS [EXTENSIONS ...]]]
                          [-r [REFORMS [REFORMS ...]]] [-n NAME_FILTER] [-v]
                          [-o [ONLY_VARIABLES [ONLY_VARIABLES ...]]]
                          [-i [IGNORE_VARIABLES [IGNORE_VARIABLES ...]]]
                          path [path ...]
openfisca-run-test: error: too few arguments
```

### Here is data (or links to it) that can help you reproduce this issue:

```yaml
output_variables:
  rsa: 551
relative_error_margin: 0.01
period: 2018-10
```

with OpenFisca France.

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
Offhand this seems like it would require a lot of work and I'm not sure the benefits justify it. Why is the normal protocol `openfisca-run-test tmp.yaml` not sufficient? Is there something larger that you're trying to do that requires it?

**Comment by Morendil** [comment]
Closing, feel free to reopen with more information if this is blocking you.
