### ISSUE TITLE
Improve CircleCI caching policy

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-core#759]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

Diagnosed a failing buid for #751

### Here is what I expected to happen:

The [CircleCI build](https://circleci.com/gh/openfisca/openfisca-core/2856) should have built Core against the latest version of all dependencies, including Country-Template version 3.5.2 which was current at the time. The build should have been **green**.

### Here is what actually happened:

The build ran against Country-Template version 3.5.1, owing to reusing cached dependencies from [an older build](https://circleci.com/gh/openfisca/openfisca-core/2801). The build was **red**, because 3.5.1 which was since unpublished contained a crashing bug.

This build was generated by #753, an unrelated PR. However in that PR the version number was bumped to `24.6.5`. This resulted in the file `setup.py` for PR #751 being identical to the file of the same name in #753. The cache is **identified by the checksum of setup.py only**, therefore the build for the later PR reused the cached dependencies of the earlier PR.

Possible fixes include:
- using the branch name in the cache identifier (this seems standard)
- checksumming `Changelog.md` as well as `setup.py`

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by fpagnoux** [comment]
> using the branch name in the cache identifier (this seems standard)

Seems reasonable

> using the branch name in the cache identifier (this seems standard)

Meh. We would need to reinstall everything for each changelog update, which are quite common.
