### ISSUE TITLE
Unable to detect error on amount scales 

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#770]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

On `openfisca-france`, we added two amount scales in same yaml file and called them.

The first time, we forgot to add `value` attribute in brackets:
```yaml
    - amount:
         2014-01: 0.23
       threshold:
         2014-01: 6
```

Then, we added the `value` attributes. See [this commit](https://github.com/openfisca/openfisca-france/commit/e57fa6de128494de069a230db7e3567ee9f8a500#diff-e79521b2f36d9e2e8fc12f9789d0479aR4541) (call first, new parameters under).

### Here is what I expected to happen:

First time, we expected to see an error explaining that we missed the `value` attribute.

Then, we expected to see no error at amount scale call (at [this line](https://github.com/openfisca/openfisca-france/commit/e57fa6de128494de069a230db7e3567ee9f8a500#diff-e79521b2f36d9e2e8fc12f9789d0479aR4541)).

To call it, we used `make test`.

### Here is what actually happened:

The same error is raised without and with `value` attributes:
```
openfisca_core.parameters.ParameterNotFound: b"The parameter 'impot_revenu.reductions_impots.rpinel.taux.metropole' was not found in the 2017-01-01 tax and benefit system."
```

It breaks on `openfisca-france` with `pytest tests/test_api.py`.
See this [CircleCI build](https://circleci.com/gh/openfisca/openfisca-france/5957)

### Here is data (or links to it) that can help you reproduce this issue:

See `openfisca-france`, [refactor-rpinel-bottom-up](https://github.com/openfisca/openfisca-france/tree/e57fa6de128494de069a230db7e3567ee9f8a500) branch.

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by sandcha** [comment]
This might be linked to #762

**Comment by Morendil** [comment]
The cause is embarrassingly simple, we're missing a return statement in the last line of the AmountTaxScale case here:

https://github.com/openfisca/openfisca-core/blob/382491dcb03e85b5da8e87e48e520c2315a07536/openfisca_core/parameters.py#L708-L715

Now to write a unit test for that.
