### ISSUE TITLE
Improve error messages for entity role issues

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#782]
Hi there!
I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I generated a relatively big payload with 3000 families and got an error because I associate more than two people to the parent role in a family.

The error is also visible with that payload:
```json
{
    "individus": {
        "parent1": {
            "age": {
                "2018-10": null
            }
        },
        "parent2": {},
        "parent3": {}
    },
    "familles": {
        "_": {
            "parents": [
                "parent1",
                "parent2",
                "parent3"
            ]
        }
    },
    "foyers_fiscaux": {
        "_": {
            "declarants": [
                "parent1",
                "parent2",
                "parent3"
            ]
        }
    },
    "menages": {
        "_": {
            "personne_de_reference": [
                "parent1"
            ],
            "conjoint": [
                "parent2",
                "parent3"
            ]
        }
    }
}
```
### Here is what I expected to happen:
I expected to have a error message that explicit the bogus family of group entity.

### Here is what actually happened:
{"error":"Internal server error: list index out of range"} 

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

(remove this line as well as all items in the list that don't fit your situation)

**Comment by Morendil** [comment]
@fpagnoux As I look into this I notice that `iter_over_entity_members` is in `scenarios.py`, it doesn't use `conv` so we might want to move it somewhere else to isolate further the dependency on scenarios.

There is indeed no check for an out of bounds index over the `subroles` array in [Famille](https://github.com/openfisca/openfisca-france/blob/02439030d7024af1a229f38780f8f30ec082e1d2/openfisca_france/entities.py#L5): https://github.com/openfisca/openfisca-core/blob/56e31c6186e1e354d074ee1e6f4f760442b44981/openfisca_core/scenarios.py#L726

A quick and dirty fix is to change the line above to silently ignore the implied extra subroles and (as a consequence) only assign the individuals to the "parent" role:
```
if role.subroles and legacy_role_j < len(role.subroles)
```

I'm not sure how much effort is required for a "proper" test-driven fix (possibly some untangling of dependencies between classes).

It's not even clear what the desired behaviour is in this case, if it should be an error message at all. Absent a `max` specification in the `parent` role, the only thing that constrains the number of parents in a `Famille` of the France model is, in fact, the number of subroles. I could make a case that silently passing over the subroles and allowing any number of parents in a `Famille` is precisely what the vagueness of the _famille_ concept in France allows.

Or we could catch the exception somewhere, and throw a `SituationParsingError`.

@guillett I'm curious to know more about how you got into that situation originally, do you _have_ families with more than three parents, or was that the result of a bug in constructing your payload?

**Comment by guillett** [comment]
Many thanks @Morendil for your quick reply. I get a list of individuals and I created a few heuristics to map them appropriately in families. These heuristics appear to be bogus.

**Comment by Morendil** [comment]
OK, so throwing an error is acceptable. It wouldn't have been if you did have three-parent families legitimately accepted as such by whoever gives out a social benefit to them. (In a loose enough sense of "parent" this could perfectly make sense, such as with a live-in grandfather or grandmother, say.) Though I suppose there's no way to construct those in the Mes Aides UI anyway, or we'd have noticed this problem before.

**Comment by fpagnoux** [comment]
Seems connected to #560 and #721

**Comment by fpagnoux** [comment]
Fixed by https://github.com/openfisca/openfisca-core/pull/865
