### ISSUE TITLE
Improve getting holders array in python (use a simulation method)

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#788]
What I have to do:
```python
simulation = ...
holder = simulation.persons.get_holder('salary')
holder.get_array('2018-08')
```
What I'd prefer:
```python
simulation = ...
simulation.get_arrays('salary', '2018-08')
```

on the same lines as #784 and #726 .
`get_know_periods` would also be useful.

**Comment by Morendil** [comment]
For #726 I have a proposal coming. Didn't have time to make a PR yet, coming soon.

I'd like to know more about the use case, as I often do. What are you trying to achieve ?

There's a risk if too much of this gets around the code base. In the case of `delete_arrays` there weren't many "misuse cases" (that I could think of), this seems different to me. In particular if you gain access to the vector of a variable without knowing the entity, you're also uncertain about the size of the array. This increases the chance of mistakenly trying an operation on mismatched arrays.

If you're trying to check the existence of the array (perhaps before calling `delete_array`) then it's better to have something like `has_values('salary', '2018-08')`. Don't expose more information than you need.

**Comment by fpagnoux** [comment]
I think this already exists: https://openfisca.org/doc/openfisca-python-api/simulations.html#openfisca_core.simulations.Simulation.get_array
