### ISSUE TITLE
Unable to load a reform with openfisca test

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#816]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

On OpenFisca-Tunisia, I tried to run a YAML test with a reform:
```
openfisca test -c openfisca_tunisia -r openfisca_tunisia.reforms.de_net_a_salaire_de_base.de_net_a_salaire_de_base tests/reforms/de_net_a_salaire_de_base/basic.yaml 
```

> This is described in ['openfisca test' documentation](https://openfisca.org/doc/openfisca-python-api/openfisca-run-test.html?highlight=test#reforms)

### Here is what I expected to happen:

A status on `basic.yaml` test execution result.

### Here is what actually happened:

```
usage: openfisca test [-h] [-c COUNTRY_PACKAGE]
                      [-e [EXTENSIONS [EXTENSIONS ...]]]
                      [-r [REFORMS [REFORMS ...]]] [-n NAME_FILTER] [-v]
                      [-o [ONLY_VARIABLES [ONLY_VARIABLES ...]]]
                      [-i [IGNORE_VARIABLES [IGNORE_VARIABLES ...]]]
                      path [path ...]
openfisca test: error: the following arguments are required: path
```

### Here is data (or links to it) that can help you reproduce this issue:

Connected to openfisca/openfisca-tunisia#82

Note : The reform is automatically loaded when all tests are executed:
```
openfisca test -c openfisca_tunisia tests/
```

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by sandcha** [comment]
Setting the path first avoids the error : 
`openfisca test tests/reforms/de_net_a_salaire_de_base/basic.yaml  -c openfisca_tunisia -r openfisca_tunisia.reforms.de_net_a_salaire_de_base.de_net_a_salaire_de_base`
But in this example, `salaire_imposable` is still not called from the reform. 🤔

**Comment by benjello** [comment]
@sandcha @Morendil : this can be closed right ?

**Comment by Morendil** [comment]
Yes, superseded by #818. The second "part of the problem" was that the reforms key in a YAML test now needs to be a list and can no longer be a single string.
