### ISSUE TITLE
Missing unit tests for openfisca test command

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#818]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what was done:

A bug was fixed on `openfisca test` command.
Connected to #814 

### Here is what I expected to happen:

A unit test failing on the bug or an improvement of unit test coverage for the command.

### Here is what actually happened:

No clear unit test existed for `openfisca test`.

### Here is data (or links to it) that can help you reproduce this issue:

See `openfisca_core.scripts.test_runner.py` (including `_run_test` and `_check_variable` private functions).

Might also be connected to #816

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
Fixed by #825
