### ISSUE TITLE
Unify how simulations are created

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#832]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I wanted to initialise a python test.

### Here is what I expected to happen:

To see one recommended way to initialise a simulation from python code both in `openfisca_core` and the official documentation.

### Here is what actually happened:

I found [SimulationBuilder](https://openfisca.org/doc/openfisca-python-api/simulation_builder.html) python API and no example.
And [deprecated scenarios](https://openfisca.org/doc/key-concepts/input_data.html) given as the official example.

### Here is data (or links to it) that can help you:

Currently, we use all of the following code:

- [ ] SimulationBuilder.build_from*
- [ ] `new_scenario`
- [ ] `new_scenario` >` init_from_dict` (was `init_from_test_case`)
- [ ] `new_scenario` > `init_single_entity`
- [ ] `new_scenario` > `init_from_attributes`

See also #790.

> And update `init_single_entity` signature like described in [this discussion](https://github.com/openfisca/openfisca-france/pull/1227#discussion_r253724422)?

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
Closing in favor of the doc issue.
