### ISSUE TITLE
Allow a sensible default value for date variables

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-core#838]
[This line](https://github.com/openfisca/openfisca-france/blob/adfe619b4336023abf4c1bea294e2e071d0cb2d0/openfisca_france/model/prestations/aides_logement.py#L258) in OpenFisca France seems likely to cause problems at some point, it sets the default value for a date variable to `date.max`. This happens to result in the intended behavior (a date comparison returns false by default) but doesn't really make sense. Being able to set the default for date variables to a "today" value, for example, would likely be safer.

**Comment by benjello** [comment]
Why doesn't it make sense for you ?

**Comment by Morendil** [comment]
Any calculation that wants a more specific value for e.g. "how long has this person been unemployed" will have to deal with a negative number with large absolute value.

More generally, date variables model real-world dates, so sensible values will correspond to sensible real-world conditions, such as "the date isn't in the future" (unless it makes sense, for instance for a projected date when a contract ends). "The person's unemployment starts in the year 300,000" is not a sensible real-world condition.

**Comment by benjello** [comment]
@Morendil : when you do computation on different periods you cannot set today to a variable which definition_period is eternity ?

Is there a better way than `date.max` which is a proxy of `+Inf` for a date to say never ?

**Comment by Morendil** [comment]
Closing as it isn't clear this is causing any current pain.
