### ISSUE TITLE
Take into account input declared for several months

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#841]
Connected to #460
Connected to #813 

As noticed by @Morendil [here](https://github.com/openfisca/openfisca-core/pull/813#issuecomment-469718590), inputs declared for several months are not properly taken into account.

**Comment by Morendil** [comment]
What difference do you see between this and #842 ?

**Comment by fpagnoux** [comment]
This is a bug fix: some users inputs are silently ignored for no good reason. This can be fixed without taking any design decision or consensus, just by properly enforcing the currently [documented behavior](https://openfisca.org/doc/coding-the-legislation/35_periods.html#set-input-automatically-process-variable-inputs-defined-for-periods-not-matching-the-definition-period):

Implementing #842 would fix this issue too, but is also a deeper change of behavior, and probably needs some discussion. If this discussion takes a long time, I'd rather not have it on the critical path of fixing this serious bug, hence the 2 separate issues 🙂
