### ISSUE TITLE
Make "dispatch" the default set_input behavior

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#842]
As suggested by @Morendil [here](https://github.com/openfisca/openfisca-core/pull/813#issuecomment-469718590).

To be discussed among the community 🙂

**Comment by fpagnoux** [comment]
To give more context on the current behavior, and what this issue is suggesting:

# Current behavior

Most variables' `definition_period` is  `MONTH` or `YEAR`.

For a given variable, by default, if a user tries to set an input for a period that doesn't match the definition period, an error is raised. That will for instance happen if:
- `handicap` is defined for `MONTH`, and a user tries to set it for `2019`
- `social_security_contribution` is defined for `MONTH`, and a user tries to set it for the 6 months period starting in January 2019 (`month:2019-01:6`)
- `income_tax` is defined for `YEAR`, and a user tries to set it for a 2-year period.

The maintainer of a Tax and Benefit System can however choose to opt-in to a different behavior for some variables, by adding an [extra attribute](https://openfisca.org/doc/coding-the-legislation/35_periods.html#set-input-automatically-process-variable-inputs-defined-for-periods-not-matching-the-definition-period):

- `set_input = set_input_dispatch_by_period`:  Will allow to set an input for a larger period than the definition period. The input value will in that case be _dispatched_ to _every_ sub-period.
  - For instance, if a user sets a `social_security_contribution` of `6000` for `month:2019-01:6` (Jan to June 2019), OpenFisca will understand that `social_security_contribution` was 6000 in January, 6000 in February, etc.
- `set_input = set_input_dispatch_by_period`:  Will also allow to set an input for a larger period than the definition period, but will process it differently. The input value will in that case be _divided_ between sub-periods.
  - For instance, if a user sets a `social_security_contribution` of `6000` for `month:2019-01:6` (Jan to June 2019), OpenFisca will understand that `social_security_contribution` was 1000 in January, 1000 in February, etc.


# Suggested change

- Make `set_input_dispatch_by_period` the default behavior for all variables
- Keep `set_input_divide_by_period` as an opt-in mechanism


# Rationale

(@morendil fee free to pitch in addiontal arguments)

- Convenience for users (especially once base functions dissapears with https://github.com/openfisca/openfisca-core/pull/813)
- Convenience for tax benefit system maintainers 

# Possible downsides

- This makes an assumption by default, and this assumption is not always relevant
  - For instance, to `dispatch` a salary doesn't fully make sense

# Alternative implementation

- Use `dispatch` or `divide` by default depending on the type of the variable (divide for int and floats, dispatch for other types). This is similar to what was done with base functions. But relying on the type is discutable.

On a more exploratory side note, there have been discussions before about the fact that OpenFisca has fondamentally two types of variables: "state" variables, like `age` or `handicap`, that are the one we'd like to dispatch, and "exchange"/"flow"/"transfert" variables, that are the ones we'd like to divide. Not yet sure how we can make this disctinction part of our model, but could be worth thinking about it.

**Comment by fpagnoux** [comment]
@sandcha @benjello @Morendil @guillett @Br3nda @jvalduvieco what do you think?

**Comment by benjello** [comment]
I am against `set_input_dispatch_by_period` as an intangible default for monetary and or divisible variable.
The name of a variable doesn't say much about it's period and the period usually defined in openfisca is mainly based on usability ground than a real source of truth.
I am not against having an option that triggers `set_input_dispatch_by_period` as a default but I want to be able to detect the "flow" variable that I do not set correctly.

**Comment by maukoquiroga** [comment]
Given there's en explicit no-go and no current alternative to solve the issue, I'm closing for now. Thanks to all your efforts @fpagnoux.
