### ISSUE TITLE
Non helping ValueError on missing group entity in test case

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-core#849]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

A `TEST_CASE` missing one group entity (`foyers_fiscaux`).

```python
from openfisca_core.simulation_builder import SimulationBuilder
from openfisca_france import FranceTaxBenefitSystem

tax_benefit_system = FranceTaxBenefitSystem()

TEST_CASE = {
    'individus': {
        'parent1': {
            'age': {'2015-01': 30},
            'salaire_de_base': {'2015': 20000}
        },
        'enfant1': {
            'age': {'2015-01': 12}
        },
        'enfant2': {
            'age': {'2015-01': 18}
        }
    },
    'familles': {
        'famille1': {
            'parents': ['parent1'],
            'enfants': ['enfant1', 'enfant2']
        }
    },
}

simulation_builder = SimulationBuilder()
simulation = simulation_builder.build_from_entities(tax_benefit_system, TEST_CASE)

simulation.calculate('af', '2015-01')
```

### Here is what I expected to happen:

A message error saying that I need to define the information Z 
to calculate variable X on the entity Y.

> Z might be that I need to explicitly dispatch persons (individus) on group entity Y.

### Here is what actually happened:

```python
(...)
~/.local/share/virtualenvs/tut78/lib/python3.7/site-packages/openfisca_core/entities.py in check_array_compatible_with_entity(self, array)
     98         if not self.count == array.size:
     99             raise ValueError("Input {} is not a valid value for the entity {} (size = {} != {} = count)".format(
--> 100                 array, self.key, array.size, self.count))
    101 
    102     def check_role_validity(self, role):

ValueError: Input [False False] is not a valid value for the entity individu (size = 2 != 3 = count)
```

### Here is data (or links to it) that can help you reproduce this issue:

Seen during Core upgrade on openfisca/tutorial#78, `notebooks/getting_started.ipynb`, first simulation building.

The error might come from this `af` > ... > `af_eligibilite_base` calculation step:

```python
residence_dom = famille.demandeur.menage('residence_dom', period)
``` 

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
This seems due to a flaw in #835 which doesn't properly initialize the roles of the "default group entity", we need additional tests replicating the above situation.
