### ISSUE TITLE
Prevent trace content wrapping

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#869]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

`(.venv) ➜  mes-aides-ui git:(update_of) ✗ openfisca-run-test ../openfisca-paris/tests/unittests/aspeh.yaml --country-package openfisca_france --extensions openfisca_paris -v > aspeh
`

### Here is what I expected to happen:

To have an unwrapped indented trace that can easily be manipulated in Sublime Text for instance.
![Sans titre](https://user-images.githubusercontent.com/1410356/57305119-d0d33a80-70e0-11e9-9b5e-d678ac6d353e.png)

That issue is generated by the explicit enum values (changed from numbers to enum value, many thanks!).

### Here is what actually happened:

Long lines are wrapped and the trace is not easily explorable.

### Here is data (or links to it) that can help you reproduce this issue:

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/thomas/repos/openfisca-paris
collected 4 items

tests/unittests/aspeh.yaml Computation log:
  paris_logement_aspeh<2016-02> >> [0.]
    parisien<2016-02> >> [ True]
    paris_enfant_handicape<2016-02> >> [False False False False  True]
      handicap<2016-02> >> [False False False False  True]
      paris_enfant<2016-02> >> [False False  True  True  True]
        est_enfant_dans_famille<2016-02> >> [False False  True  True  True]
        enfant_place<2016-02> >> [False False False False False]
        enfant_a_charge<2016> >> [False False  True  True  True]
          age<2016-01> >> [55 55  5  7  9]
          handicap<2016-12> >> [False False False False False]
    paris_base_ressources_couple<2016-01> >> [5344.6836]
      en_couple<2016-01> >> [ True]
        nb_parents<2016-01> >> [2]
      paris_base_ressources_i<2016-01> >> [3100. 1400.    0.    0.    0.]
        ass<2016-01> >> [0. 0. 0. 0. 0.]
          ass_base_ressources<2016-01> >> [0.]
            ass_base_ressources_individu<2016-01> >> [0. 0. 0. 0. 0.]
              salaire_imposable<2015-01> >> [0. 0. 0. 0. 0.]
                salaire_de_base<2015-01> >> [0. 0. 0. 0. 0.]
                primes_salaires<2015-01> >> [0. 0. 0. 0. 0.]
                primes_fonction_publique<2015-01> >> [0. 0. 0. 0. 0.]
                  categorie_salarie<2015-01> >> ['prive_non_cadre' 'prive_non_cadre' 'prive_non_cadre' 'prive_non_cadre'
 'prive_non_cadre']
                  traitement_indiciaire_brut<2015-01> >> [0. 0. 0. 0. 0.]
                indemnite_residence<2015-01> >> [0. 0. 0. 0. 0.]
                  traitement_indiciaire_brut<2015-01> >> [0. 0. 0. 0. 0.]
                  salaire_de_base<2015-01> >> [0. 0. 0. 0. 0.]
                  categorie_salarie<2015-01> >> ['prive_non_cadre' 'prive_non_cadre' 'prive_non_cadre' 'prive_non_cadre'
 'prive_non_cadre']
```

## Context

I identify more as a:
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
This seems to be the default behaviour of Numpy when representing arrays as strings. 😱

This does the trick:
> `np.set_printoptions(linewidth=float("inf"))`

However, I'm a bit loath to put this somewhere in Core as it is a global and sticky configuration option. A better way is to change calls like `str(array)` to `np.array2string(array,max_line_width=float("inf"))`.
