### ISSUE TITLE
Better handling of memory usage

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#92]
_Issue by **[benjello](https://github.com/benjello)** from Thursday Nov 29, 2012 at 16:25 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/89_

---

3 ways of doing that:
- sparse DataFrames http://pandas.pydata.org/pandas-docs/version/0.7.1/sparse.html (see france/data/sparse_test for problem with sparseSeries)
- Wait for imporvements in pandas to work with out of memory data (see roadmap http://pandas.pydata.org/developers.html )
- load/save data when needed (mode reform with survey data)

**Comment by MattiSG** [comment]
This issue is never ending (and never started  ;)  ).

In order to increase the readability of the current active work in progress, I close this 3-years old issue.
