### ISSUE TITLE
Error when trying to encode scalar Enum arrays

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#922]
The following code fails for scalar Enum arrays (without dimension):

https://github.com/openfisca/openfisca-core/blob/871bf2007545236bc814b49dea27559bef87c584/openfisca_core/indexed_enums.py#L60

A real-life example of this bug:

https://github.com/openfisca/openfisca-france/blob/7918eec5be4c2cdeb65da9fb023cfbfcce537156/openfisca_france/model/prestations/logement_social.py#L71-L81

You can reproduce the issue with the following code:

```py
from numpy import array, atleast_1d

from openfisca_core.indexed_enums import Enum

class Greetings(Enum):
    hola = "Hola"
    chao = "Chao"

greeting = array(Greetings.hola)
greeting.size # 1
len(greeting) # TypeError: len() of unsized object
atleast_1d(greeting).size # 1
len(atleast_1d(greeting)) # 1
```

What's the expected behaviour here?

1. We're expecting an array with at least one dimension.
2. We should make sure we cast or take into account scalar arrays.

cc @Morendil @fpagnoux

**Comment by Morendil** [comment]
Are you sure? The code in France you are linking to was exercised by France tests and did not seem to be affected by this bug, prior to Core 34.5.4.

**Comment by maukoquiroga** [comment]
Not really sure, no : as there it no signature in the original code, I don't know what is the expected behaviour.

So, #923 adds tests assuming we wanted to handle scalar vectors as well.

**Comment by maukoquiroga** [comment]
So as discussed in openfisca/openfisca-france#1395, it seems the current behaviour is the expected behaviour.

I'm then :

- [ ] Closing this issue for now, do not hesitate to re-open it.
- [ ] Adapting #923 as a test-adding PR, not a bug fix.

Thanks !
