### ISSUE TITLE
Compatibility with Numpy 1.18

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#924]
[Numpy bumped to 1.18](https://numpy.org/devdocs/release/1.18.0-notes.html), [are we prepared?](https://github.com/openfisca/openfisca-france/pull/1395#pullrequestreview-337568319)

I did analysis by going through each change announced in the Numpy's 1.18 changelog, checking against OpenFisca Core's code base, and here's what I found.

This is a "theme" or "meta" issue to deal with each part of the code base that needs some work in order to ensure compatibility with Numpy 1.18.

- [x] https://github.com/openfisca/openfisca-core/blob/d47f65ad21c2de683a324378fc80a1177f0efa04/openfisca_core/simulation_builder.py#L515

- [x] https://github.com/openfisca/openfisca-core/blob/d47f65ad21c2de683a324378fc80a1177f0efa04/openfisca_core/simulation_builder.py#L520

- [x] https://github.com/openfisca/openfisca-core/blob/92ce9396e29ae5d9bac5ea604cfce88517c6b35c/openfisca_core/scripts/measure_numpy_condition_notations.py#L56

- [x] https://github.com/openfisca/openfisca-core/blob/273e17b65ccbe6941aa5576140d9c880990483bc/openfisca_core/formula_helpers.py#L31

- [x] https://github.com/openfisca/openfisca-core/blob/273e17b65ccbe6941aa5576140d9c880990483bc/openfisca_core/formula_helpers.py#L47

- [x] https://github.com/openfisca/openfisca-core/blob/5a1fd43eb16e55710d9dd84c90ff7408c765e3e6/openfisca_core/indexed_enums.py#L51

- [x] https://github.com/openfisca/openfisca-core/blob/5a1fd43eb16e55710d9dd84c90ff7408c765e3e6/openfisca_core/indexed_enums.py#L62

- [x] https://github.com/openfisca/openfisca-core/blob/5a1fd43eb16e55710d9dd84c90ff7408c765e3e6/openfisca_core/indexed_enums.py#L116

- [x] https://github.com/openfisca/openfisca-core/blob/5a1fd43eb16e55710d9dd84c90ff7408c765e3e6/openfisca_core/indexed_enums.py#L128

- [x] https://github.com/openfisca/openfisca-core/blob/c64f9083c1fae9c572282370c3d1f4164c312e1a/openfisca_core/tools/simulation_dumper.py#L80

- [x] https://github.com/openfisca/openfisca-core/blob/c64f9083c1fae9c572282370c3d1f4164c312e1a/openfisca_core/tools/simulation_dumper.py#L98

- [x] https://github.com/openfisca/openfisca-core/blob/6d9c53789f24e314fc28988a58e610ba6ca66ef4/openfisca_core/parameters.py#L685

- [x] https://github.com/openfisca/openfisca-core/blob/6d9c53789f24e314fc28988a58e610ba6ca66ef4/openfisca_core/parameters.py#L688

- [x] https://github.com/openfisca/openfisca-core/blob/6d9c53789f24e314fc28988a58e610ba6ca66ef4/openfisca_core/parameters.py#L695

- [x] https://github.com/openfisca/openfisca-core/blob/d47f65ad21c2de683a324378fc80a1177f0efa04/openfisca_core/simulation_builder.py#L198

- [x] https://github.com/openfisca/openfisca-core/blob/2fd3a2ce40df17222c2b559a49fbfba26e24d544/openfisca_core/populations.py#L159

**Comment by benjello** [comment]
For `linspace`, it should work without problem. And if it is  the `num` argument is not an integer, it will throw an error and that is ok. Should we catch that error ? What are we supposed to do ?

cc @maukoquiroga @Morendil

**Comment by benjello** [comment]
@maukoquiroga  @sandcha : we definitely need to upgrade core to numpy 1.18 ASAP since it is a major library we depend on we cannot lag too much.

**Comment by maukoquiroga** [comment]
Hello @benjello ! Most of the work is to be propagated to country packages, changes in core are quite simple actually. We need :

- To make sure it works at least in OpenFisca-France, each time
- To broadcast / announce changes to the rest of the community

**Comment by maukoquiroga** [comment]
I know you won't like what I'm going to say but ... the biggest problem here is country package's direct dependency on numpy.

For other command-line packages like survey manager is less of an issue, but for country packages it is quite problematic, as live web apps as MesAides.org could suffer from surreptitious false calculation results caused by silent logical castings.

**Comment by sandcha** [comment]
It seems that there isn't official documentation on how to upgrade our code besides the error messages. So, here is some information on the [select](https://numpy.org/doc/1.18/reference/generated/numpy.select.html) routine: 
we have two deprecations,`np.select([]) and np.select(a) where a.dtype is integer-type` [[src](https://github.com/numpy/numpy/issues/11521)]

* `np.select([])` 
=> select with an empty condition list is not possible with numpy 1.18
[Before numpy 1.18](https://github.com/numpy/numpy/pull/14583/files#diff-9d44603693b9544b900e135a203b3ae2L689), we got this result `np.asarray(default)[()]`
**Example:** `np.select([], [])` result was `0` (for a `default` argument value set to `0`)
With numpy 1.18 we get a `ValueError`.
As I see it, we might have to catch the error or adapt its message in Core (as we build conditions in [formula_helpers.py](https://github.com/openfisca/openfisca-core/blob/87b14483dc1c473767ba41ba298ddb9a9c572bb8/openfisca_core/formula_helpers.py), etc.). In a Country module the `ValueError` message should be clear enough, if it happens in a formula.

* `np.select(a) where a.dtype is integer-type`
[Before numpy 1.18](https://github.com/numpy/numpy/pull/14583/files#diff-9d44603693b9544b900e135a203b3ae2L712) integer conditions where transformed to booleans. 
**Example:** `np.select([0, 1, 0], ['a', 'b', 'c'])` result was `array('b', dtype='<U21')`
Here, we have a migration task as we should update such code to: `np.select(np.array([0, 1, 0]).astype(bool), ['a', 'b', 'c'])` 
(or we will get a [TypeError](https://github.com/numpy/numpy/pull/14583/files#diff-5d647ef56aa534f743ca416ef3ee37a1R433)...`use .astype(bool) to  convert to bools`)

**Comment by benjello** [comment]
@maukoquiroga : I am always happy to hear about what you have to say ;-)

My point is that openfisca relying on numpy is a feature not a bug. We need that flexibility to avoid reinventing the wheel.

For the upgrade, let's try to detect the more risky country package (France, Barcelona ? NZ ?), all the one I a involved in I can manage them especially if a good error message pops out.

I am also ok if, as @sandcha seems to suggest, you want to go on some deprecation route, by, for example, monky-patching `np.select` upon detecting that numpy version is 1.18.

**Comment by benjello** [comment]
@maukoquiroga @sandcha : relying on lagging version of numpy is also a source of troubles for people using openfisca on windows. They usually need to manually install standard packages with conda  to have all the compiled windows libraries installed and finish the work with pip when no conda packages exists (and pip and conda do not get along very well). 

It is a real pain :-(. 
Maybe we should think of a conda package ...

**Comment by benjello** [comment]
@sandcha @maukoquiroga : could we move on and merge ? It is painful for many user me included ;-)

**Comment by benjello** [comment]
@guillett : are you ok with this ?

**Comment by benjello** [comment]
@sandcha : je pense que l'on peut valider tous les select qui utilisent des vecteurs de booléens.

**Comment by benjello** [comment]
@sandcha : je les ai passé en revue et cela me semble bon.
