### ISSUE TITLE
Have a clear product/technical roadmap for OpenFisca Core

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/openfisca-core#942]
![Image](https://user-images.githubusercontent.com/329236/73535641-58f23080-4424-11ea-8d27-f330597b6d58.jpeg)

cc @Morendil @sandcha

**Comment by maukoquiroga** [comment]
I've tried to distill what could be a short-mid term roadmap for OpenFisca-Core here:

* https://github.com/openfisca/openfisca-core/milestone/2
* https://github.com/openfisca/openfisca-core/milestone/3
* https://github.com/openfisca/openfisca-core/milestone/4
* https://github.com/openfisca/openfisca-core/milestone/5
* https://github.com/openfisca/openfisca-core/milestone/6

@MattiSG I see that you've been successfully running RFCs lately, I would love to have your help/opinion on this one, most of it are elements we've been discussing for a while now.

**Comment by bonjourmauko** [comment]
Because you forgot to click the accept button 🤣 

Joking, closing this issue as is not actionable.

**Comment by bonjourmauko** [comment]
I consolidated current efforts in the wiki:
https://github.com/openfisca/openfisca-core/wiki/Ongoing-Efforts
