### ISSUE TITLE
`this_month` does not exist on object Period

### ISSUE THREAD

**Issue by CalvinRodo** [openfisca/openfisca-core#952]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Tried to calculate the period using `period.this_month` in a formula

### Here is what I expected to happen:
The variable to calculate the period for this_month. 
I expected this to be available as per OpenFisca documentation for periods https://openfisca.org/doc/coding-the-legislation/35_periods.html

### Here is what actually happened:
Recieved an error that stated that object Period does not a have a method this_month. 
Looking at the code there is no method named this_month in openfisca-core in the file periods.py

### Here is data (or links to it) that can help you reproduce this issue:
https://openfisca.org/doc/coding-the-legislation/35_periods.html
https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/periods.py

## Context

I identify more as a:

- Business expert _(I create tests and model legislation)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
Thanks @CalvinRodo ! This is a missing doc update; the method was renamed `period.first_month`.

**Comment by maukoquiroga** [comment]
Thanks @CalvinRodo! Documentation was just fixed :)
