### ISSUE TITLE
Update the Web API Swagger 2.0 specification to OpenAPI 3.0

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#988]
The Web API specification is currently described in the Swagger 2.0 format, which has been [improved upon significantly](https://medium.com/@tgtshanika/open-api-3-0-vs-swagger-2-0-94a80f121022) in OpenAPI 3.0.

![](https://miro.medium.com/max/1400/1*ovjrmZWTENmEyuDLPrGfmw.png)

There is no known immediate use case for this update, but we should expect maintenance to be made easier, and the tooling ecosystem to move towards the more recent standard.

As a reuser, please use this issue to mention your interest in this update if your integration would be made easier with it 🙂

**Comment by MattiSG** [comment]
As an author of the spec, I can tell it would be very useful to be able to use `oneOf` as a consequence of #982, which is not supported in Swagger 2.0 as specified in https://github.com/OAI/OpenAPI-Specification/issues/333.

**Comment by MattiSG** [comment]
This would also [enable](https://stackoverflow.com/a/50476201/594053) spec-compliant reuse of headers, which are currently defined under `commons` and is not valid.

**Comment by maukoquiroga** [comment]
Thanks @MattiSG ! I think this a much waited change, and maybe also a fix for https://github.com/openfisca/legislation-explorer/issues/227 ✨

**Comment by bonjourmauko** [comment]
Hello @MattiSG , has this been fixed by #989?

**Comment by MattiSG** [comment]
Yes!
