### ISSUE TITLE
Bug // web_api does not handle `ParameterNotFound` error gracefully. Instead it returns no response.

### ISSUE THREAD

**Issue by RamParameswaran** [openfisca/openfisca-core#991]
### Here is what I did:

- I have discovered a bug while calling the `/calculate` endpoint. It occurs when you provide an invalid "period" value, but the web_api does not return a meaningful error response. 
- I've created a failing test [in this branch](https://github.com/openfisca/openfisca-core/tree/bug-webapi-parameter-indexerror)

### Here is what I expected to happen:

- I expect the web_api to return an error response (400 error, or even 500 error)
- I expect a meaningful error message indicating the "period" provided is invalid based on the parameter values specified.

### Here is what actually happened:

- The web_api returns no response. Instead it halts due to the IndexError.
- Upon receiving no response, Chrome assumes it is a CORS error. The screenshot below shows the frontend error.
![image](https://user-images.githubusercontent.com/33742989/113245768-54185d80-9303-11eb-9c31-68cd4ac31977.png)

- Here is the backend stack trace:
![image](https://user-images.githubusercontent.com/33742989/113245826-7611e000-9303-11eb-8ab5-60515c3a8f1f.png)

## Context

I identify more as a:

- Developer - I create frontend applications which ingest OpenFisca rulesets 

Thanks in advance!

**Comment by maukoquiroga** [comment]
Thanks for reporting this, I would have expected a 404 with an explanation.
