### ISSUE TITLE
Use Python warnings package instead of logging.warning

### ISSUE THREAD

**Issue by benoit-cty** [openfisca/openfisca-core#995]
Hi there!

I'm working at the French Parliament (Assemblée Nationale) in the LexImpact team who help members of the parliament to evaluate the impact of laws projects. We use OpenFisca to compute the income tax.

We compute  income taxes for the whole population. Doing so, we see many of these warnings:

```
WARNING:openfisca_core.simulations:Intermediate results will be stored on disk in /tmp/openfisca_c1rkeofp in case of memory overflow. You should remove this directory once you're done with your simulation.

WARNING:openfisca_core.memory_config:Memory configuration is a feature that is still currently under experimentation. You are very welcome to use it and send us precious feedback, but keep in mind that the way it is used might change without any major version bump.
```

I'd like to be able to hide these warnings.

I could make a PR to use warnings package like this:

```
class OpenFiscaMemoryWarning(UserWarning):
...     pass
... 
... warnings.warn('Memory configuration is a feature that is still currently under experimentation.', OpenFiscaMemoryWarning)
```
So I could hide the warnings like this:
`warnings.simplefilter(action="ignore", category=OpenFiscaMemoryWarning)`

What do you think of this proposition ?

**Comment by maukoquiroga** [comment]
Hello @benoit-cty ! Thanks for your proposal.

If you take a look at the core's source code, the `warning` library is actually being used in more "modern" parts of the code, for instance here:

```python
from __future__ import annotations

import typing
import warnings

import numpy

from openfisca_core.taxscales import RateTaxScaleLike


class AbstractRateTaxScale(RateTaxScaleLike):
    """
    Base class for various types of rate-based tax scales: marginal rate, linear
    average rate...
    """

    def __init__(self, name: typing.Optional[str] = None, option = None, unit = None) -> None:
        message = [
            "The 'AbstractRateTaxScale' class has been deprecated since version",
            "34.7.0, and will be removed in the future.",
            ]
        warnings.warn(" ".join(message), DeprecationWarning)
        super(AbstractRateTaxScale, self).__init__(name, option, unit)
```

I think an uniformisation of warnings with either `logging` or `warning` would be very much welcome 😃
